/**
 * Photovoltaic output
 * Method: pv v0.9.3
 * Equation: P=GAηf
 * Generated by Sustainable Catalyst Lab v0.9.3
 * Portable reference implementation; review assumptions and units.
 */
export type Result = { power_w: number };

export function calculate(irradiance: number = 800, area: number = 20, efficiency: number = 0.21, system_factor: number = 0.82): Result {
  const power_w = (irradiance * area * efficiency * system_factor);
  return { power_w };
}

console.log(calculate());
