"""Photovoltaic output
Method: pv v0.9.3
Equation: P=GAηf
Generated by Sustainable Catalyst Lab v0.9.3
Portable reference implementation; review assumptions and units."""
import math

def calculate(irradiance: float = 800, area: float = 20, efficiency: float = 0.21, system_factor: float = 0.82) -> dict[str, float]:
    power_w = (irradiance * area * efficiency * system_factor)
    return {"power_w": power_w}

if __name__ == "__main__":
    print(calculate())
