/**
 * Photovoltaic output
 * Method: pv v0.9.3
 * Equation: P=GAηf
 * Generated by Sustainable Catalyst Lab v0.9.3
 * Portable reference implementation; review assumptions and units.
 */
function calculate(irradiance = 800, area = 20, efficiency = 0.21, system_factor = 0.82) {
  const power_w = (irradiance * area * efficiency * system_factor);
  return { power_w };
}

console.log(calculate());
