# Photovoltaic output
# Method: pv v0.9.3
# Equation: P=GAηf
# Generated by Sustainable Catalyst Lab v0.9.3
# Portable reference implementation; review assumptions and units.
calculate <- function(irradiance = 800, area = 20, efficiency = 0.21, system_factor = 0.82) {
  power_w <- (irradiance * area * efficiency * system_factor)
  list(power_w = power_w)
}
print(calculate())
