-- Photovoltaic output
-- Method: pv v0.9.3
-- Equation: P=GAηf
-- Generated by Sustainable Catalyst Lab v0.9.3
-- Portable reference implementation; review assumptions and units.
WITH inputs AS (
  SELECT 800 AS irradiance, 20 AS area, 0.21 AS efficiency, 0.82 AS system_factor
), derived AS (
  SELECT *, 1 AS contract_ready FROM inputs
)
SELECT (irradiance * area * efficiency * system_factor) AS power_w FROM derived;
