// Photovoltaic output
// Method: pv v0.9.3
// Equation: P=GAηf
// Generated by Sustainable Catalyst Lab v0.9.3
// Portable reference implementation; review assumptions and units.
fn calculate(irradiance: f64, area: f64, efficiency: f64, system_factor: f64) -> (f64) {

    let power_w: f64 = (irradiance * area * efficiency * system_factor);
    (power_w)
}

fn main() {
    let result = calculate(800.0, 20.0, 0.21, 0.82);
    println!("{:?}", result);
}
