# Photovoltaic output
# Method: pv v0.9.3
# Equation: P=GAηf
# Generated by Sustainable Catalyst Lab v0.9.3
# Portable reference implementation; review assumptions and units.
function calculate(irradiance::Float64 = 800, area::Float64 = 20, efficiency::Float64 = 0.21, system_factor::Float64 = 0.82)
    power_w = (irradiance * area * efficiency * system_factor)
    return Dict("power_w" => power_w)
end
println(calculate())
