/* Photovoltaic output
 * Method: pv v0.9.3
 * Equation: P=GAηf
 * Generated by Sustainable Catalyst Lab v0.9.3
 * Portable reference implementation; review assumptions and units. */
#include <math.h>
#include <stdio.h>

int main(void) {
  double irradiance = 800.0;
  double area = 20.0;
  double efficiency = 0.21;
  double system_factor = 0.82;

  double power_w = (irradiance * area * efficiency * system_factor);
  printf("power_w=%.12g\n", power_w);
  return 0;
}
