! Photovoltaic output
! Method: pv v0.9.3
! Equation: P=GAηf
! Generated by Sustainable Catalyst Lab v0.9.3
! Portable reference implementation; review assumptions and units.
program sc_lab_method
  implicit none
  real(8) :: irradiance = 8.0000000000000000d+2
  real(8) :: area = 2.0000000000000000d+1
  real(8) :: efficiency = 2.0999999999999999d-1
  real(8) :: system_factor = 8.1999999999999995d-1

  real(8) :: power_w
  power_w = (irradiance * area * efficiency * system_factor)
  print *, 'power_w=', power_w
end program sc_lab_method
