// Photovoltaic output
// Method: pv v0.9.3
// Equation: P=GAηf
// Generated by Sustainable Catalyst Lab v0.9.3
// Portable reference implementation; review assumptions and units.
package main

import (
  "fmt"
  "math"
)

var _ = math.Pi

func calculate(irradiance float64, area float64, efficiency float64, system_factor float64) (power_w float64) {

  power_w = (irradiance * area * efficiency * system_factor)
  return
}

func main() {
  fmt.Println(calculate(800.0, 20.0, 0.21, 0.82))
}
