// Photovoltaic output
// Method: pv v0.9.3
// Equation: P=GAηf
// Generated by Sustainable Catalyst Lab v0.9.3
// Portable reference implementation; review assumptions and units.
#include <cmath>
#include <iostream>
#include <numbers>

int main() {
  double irradiance = 800.0;
  double area = 20.0;
  double efficiency = 0.21;
  double system_factor = 0.82;

  double power_w = (irradiance * area * efficiency * system_factor);
  std::cout << "power_w=" << power_w << '\n';
}
