-- Photovoltaic output
-- Method: pv v0.9.3
-- Equation: P=GAηf
-- Generated by Sustainable Catalyst Lab v0.9.3
-- Portable reference implementation; review assumptions and units.
module Main where

calculate :: Double -> Double -> Double -> Double -> (Double)
calculate irradiance area efficiency system_factor =
  let

    power_w = (irradiance * area * efficiency * system_factor)
  in (power_w)

main :: IO ()
main = print (calculate 800.0 20.0 0.21 0.82)
