const fs=require('fs');const assert=require('assert');
const read=p=>fs.readFileSync(p,'utf8');
const js=read('assets/js/modules/carbon-mrv-monitoring-v0970.js');
const css=read('assets/css/sc-lab-carbon-mrv-monitoring-v0970.css');
const tpl=read('templates/lab-app.php');
const plugin=read('includes/class-sc-lab-plugin.php');
const rest=read('includes/class-sc-lab-rest.php');
const main=read('sustainable-catalyst-lab.php');
assert(js.includes("VERSION='0.97.0',DOMAIN='0.14.0'"));
assert(js.includes('recommended_planning_sample_size'));
assert(js.includes('stratified_allocation'));
assert(js.includes('sampling-frame'));
assert(css.includes('.sc-mrv1400'));
assert(tpl.includes('Monitoring Plan &amp; Sampling Designer'));
assert(tpl.includes('data-mrv-v1400-sample-calc'));
assert(tpl.includes('data-mrv-v1400-allocate'));
assert(tpl.includes('Sampling boundary:'));
assert(plugin.includes("'carbon-mrv-monitoring-v0970'"));
assert(plugin.includes("'carbonMrvMonitoring'"));
assert(rest.includes('/carbon-nature/mrv/v1400/monitoring/build'));
assert(main.includes('class-sc-lab-carbon-mrv-monitoring-v0970.php'));
console.log('PASS - Lab v0.97.0 / Carbon & Nature v0.14.0 browser contracts');
