<?php
define('ABSPATH',__DIR__);if(!function_exists('add_action')){function add_action(){}}if(!function_exists('add_shortcode')){function add_shortcode(){}}
$root=dirname(__DIR__);function v0232_assert($condition,$message){if(!$condition){fwrite(STDERR,"FAIL: {$message}\n");exit(1);}}
$contract=json_decode(file_get_contents($root.'/contracts/biosignal-visualization-comparison-v0232.json'),true);$runtime=file_get_contents($root.'/assets/js/modules/biosignal-visualization-comparison-v0232.js');$style=file_get_contents($root.'/assets/css/sc-lab-biosignal-visualization-comparison-v0232.css');$ui=file_get_contents($root.'/includes/class-sc-lab-biosignal-visualization-comparison-v0232.php');$rest=file_get_contents($root.'/includes/class-sc-lab-biosignal-visualization-rest-v0232.php');
v0232_assert($contract['version']==='0.23.2','Contract version');v0232_assert(count($contract['modes'])===8,'Eight visualization modes');v0232_assert(count($contract['analysisMethods'])===16,'Sixteen analysis methods');v0232_assert(count($contract['benchmarks'])===16,'Sixteen benchmarks');v0232_assert(count($contract['annotationTypes'])===6,'Six annotation types');v0232_assert($contract['preservedEngine']['methodCount']===48&&$contract['preservedEngine']['benchmarkCount']===48&&$contract['preservedEngine']['categoryCount']===8,'Preserved v0.23.0 contract');
v0232_assert(strpos($runtime,"const VERSION = '0.23.2';")!==false&&strpos($runtime,'buildSvg')!==false&&strpos($runtime,'bestLagCorrelation')!==false&&strpos($runtime,'BioprocessValidationProvenance')!==false,'Browser visualization workflow');v0232_assert(strpos($style,'@media (max-width:760px)')!==false&&strpos($style,'min-height:44px')!==false&&strpos($style,'overflow-x:auto')!==false,'Mobile chart fallback');v0232_assert(strpos($ui,'sc_lab_biosignal_visualization_comparison')!==false,'Focused shortcode');v0232_assert(strpos($rest,'/compute/biomedical/biosignals/visualization/compare')!==false,'Comparison REST route');
require_once $root.'/includes/class-sc-lab-biosignal-visualization-rest-v0232.php';
function v0232_equivalent($actual,$expected){if(is_float($expected)){return abs((float)$actual-$expected)<=max(1.0e-8,abs($expected)*1.0e-8);}if(is_int($expected)||is_string($expected)||is_bool($expected)||$expected===null){return $actual===$expected;}if(is_array($expected)){if(!is_array($actual)||count($actual)!==count($expected)){return false;}foreach($expected as $key=>$value){if(!array_key_exists($key,$actual)||!v0232_equivalent($actual[$key],$value)){return false;}}return true;}return $actual===$expected;}
foreach($contract['benchmarks'] as $benchmark){$result=SC_Lab_Biosignal_Visualization_REST_V0232::execute($benchmark['methodId'],$benchmark['inputs']);v0232_assert(v0232_equivalent($result['value'],$benchmark['expected']),'Benchmark: '.$benchmark['methodId']);}
$lag=SC_Lab_Biosignal_Visualization_REST_V0232::best_lag_correlation(array(1,4,2,5,0,3),array(4,2,5,0,3,9),2);v0232_assert($lag['bestLagSamples']===1&&abs($lag['bestCorrelation']-1.0)<1.0e-12,'Unique lag detection');
$coverage=SC_Lab_Biosignal_Visualization_REST_V0232::annotation_coverage(array(array('type'=>'artifact','startSeconds'=>1,'endSeconds'=>3),array('type'=>'event','startSeconds'=>2,'endSeconds'=>4)),0,10);v0232_assert($coverage['coveredSeconds']===3.0&&$coverage['coveragePercent']===30.0,'Annotation union coverage');
$health=SC_Lab_Biosignal_Visualization_REST_V0232::health_payload();v0232_assert($health['ok']===true&&$health['modeCount']===8&&$health['analysisMethodCount']===16&&$health['benchmarkCount']===16&&$health['annotationTypeCount']===6,'Health contract');
echo "Lab v0.23.2 PHP tests passed: 8 modes, 16 methods, 16 benchmarks, annotations, lag analysis, comparison.\n";
