const fs=require('fs');const assert=require('assert');
const read=p=>fs.readFileSync(p,'utf8');
const js=read('assets/js/modules/carbon-mrv-verification-ledger-v0990.js');
const css=read('assets/css/sc-lab-carbon-mrv-verification-ledger-v0990.css');
const tpl=read('templates/lab-app.php');
const plugin=read('includes/class-sc-lab-plugin.php');
const rest=read('includes/class-sc-lab-rest.php');
const main=read('sustainable-catalyst-lab.php');
assert(js.includes("VERSION='0.99.0',DOMAIN='0.16.0'"));
assert(js.includes('ledger_root_hash'));
assert(js.includes('chainCheckUrl'));
assert(js.includes('verification-record'));
assert(css.includes('.sc-mrv1600'));
assert(tpl.includes('Verification Evidence Ledger'));
assert(tpl.includes('data-mrv-v1600-chain-check'));
assert(tpl.includes('data-mrv-v1600-requirements'));
assert(plugin.includes("'carbon-mrv-verification-ledger-v0990'"));
assert(plugin.includes("'carbonMrvVerificationLedger'"));
assert(rest.includes('/carbon-nature/mrv/v1600/verification-ledger/build'));
assert(main.includes('class-sc-lab-carbon-mrv-verification-ledger-v0990.php'));
console.log('PASS - Lab v0.99.0 / Carbon & Nature v0.16.0 browser contracts');
