const fs=require('fs'),vm=require('vm'),assert=require('assert');
const calls=[];
const pass={setPipeline(p){calls.push(['setPipeline',p.label||''])},setBindGroup(){},setVertexBuffer(){},setIndexBuffer(){calls.push('setIndexBuffer')},draw(n,i){calls.push(['draw',n,i])},drawIndexed(n,i){calls.push(['drawIndexed',n,i])},end(){calls.push('passEnd')}};
const device={
 createShaderModule(x){calls.push(['shader',x.label]);return {label:x.label}},
 createRenderPipeline(x){calls.push(['pipeline',x.label,x.primitive.topology]);return {label:x.label,getBindGroupLayout(){return {}}}},
 createBuffer(x){let mapped=new ArrayBuffer(x.size);return {getMappedRange(){return mapped},unmap(){},destroy(){}}},
 createBindGroup(){return {}},
 createTexture(){return {createView(){return {}}}},
 createCommandEncoder(){return {beginRenderPass(){return pass},finish(){return {}}}},
 queue:{writeBuffer(){calls.push('writeBuffer')},submit(){calls.push('submit')}},destroy(){}
};
const adapter={features:new Set(['core-features-and-limits']),limits:{maxBufferSize:1073741824},adapterInfo:{vendor:'apple',architecture:'metal-3'},async requestDevice(){calls.push('requestDevice');return device}};
const gpu={async requestAdapter(){calls.push('requestAdapter');return adapter},getPreferredCanvasFormat(){return 'bgra8unorm'}};
const contextGPU={configure(){calls.push('configure')},getCurrentTexture(){return {createView(){return {}}}}};
const canvas={width:960,height:540,getContext(t){return t==='webgpu'?contextGPU:null},addEventListener(){},removeEventListener(){}};
const document={readyState:'complete',querySelector(){return null},addEventListener(){}};
const window={document,navigator:{gpu},GPUBufferUsage:{UNIFORM:64,COPY_DST:8,VERTEX:32,INDEX:16},GPUTextureUsage:{RENDER_ATTACHMENT:16},SCLab:{},window:null,THREE:null};window.window=window;
const ctx={window,document,globalThis:window,navigator:window.navigator,console,JSON,Math,Error,String,Array,Object,Number,Set,Map,Float32Array,Uint32Array,ArrayBuffer,Promise};vm.createContext(ctx);vm.runInContext(fs.readFileSync('assets/js/modules/advanced-scientific-scene-v0880.js','utf8'),ctx);
(async()=>{const R=window.SCLabAdvancedScientificSceneV0880;assert(R);assert.strictEqual(R.version,'0.88.0');assert.strictEqual(R.engineVersion,'2.14.0');assert.strictEqual(R.nativeWebGPUSceneRendererReady,true);assert.strictEqual(R.threeJSAdapterReady,true);assert.strictEqual(R.threeJSRuntimeBundled,false);const d=await R.diagnostics();assert.strictEqual(d.webgpuSupported,true);assert.strictEqual(d.deviceAcquired,true);const s={cameras:[{id:'c',position:[4,3,6],target:[0,0,0],up:[0,1,0],near:.01,far:100}],activeCameraId:'c',materials:[{id:'m',color:[.2,.7,.9,1]}],nodes:[{id:'root',type:'group',children:['p','l','m']},{id:'p',type:'point-cloud',materialId:'m',geometry:{positions:[0,0,0,1,0,0],colors:[1,0,0,1,0,1,0,1]}},{id:'l',type:'line-segments',materialId:'m',geometry:{positions:[0,0,0,0,1,0]}},{id:'m',type:'mesh',materialId:'m',geometry:{positions:[0,0,0,1,0,0,0,1,0],normals:[0,0,1,0,0,1,0,0,1],indices:[0,1,2]}}]};const renderer=await R.createRenderer(canvas);const out=await renderer.render(s);assert.strictEqual(out.ok,true);assert.strictEqual(out.renderer,'native-webgpu-advanced-3d');assert.strictEqual(out.drawCalls,3);assert(calls.some(x=>Array.isArray(x)&&x[0]==='pipeline'&&x[2]==='point-list'));assert(calls.some(x=>Array.isArray(x)&&x[0]==='pipeline'&&x[2]==='line-list'));assert(calls.some(x=>Array.isArray(x)&&x[0]==='pipeline'&&x[2]==='triangle-list'));assert(calls.some(x=>Array.isArray(x)&&x[0]==='drawIndexed'));assert(calls.includes('submit'));assert.throws(()=>R.createThreeJSAdapter(canvas),/Three\.js runtime is not present/);assert.strictEqual(R.boundaries.interactionCreatesObservation,false);assert.strictEqual(R.boundaries.arbitraryShaderSource,false);console.log('PASS - v0.88.0 browser Advanced 3D native WebGPU scene graph, mesh/line/point pipelines, instancing contract and explicit Three.js adapter boundary');})().catch(e=>{console.error(e);process.exit(1)});
