const fs = require('fs');
const path = require('path');
const vm = require('vm');
const source = fs.readFileSync(path.join(__dirname, '../assets/js/modules/comparative-economics-development-systems-lab.js'), 'utf8');
const context = {window:{SCLab:{}},globalThis:{},console,CustomEvent:function(type,init){this.type=type;this.detail=init&&init.detail;}};
vm.createContext(context); vm.runInContext(source, context);
const Lab=context.window.SCLab.ComparativeEconomicsDevelopmentSystemsLab;
if(!Lab||Lab.VERSION!=='0.17.0') throw new Error('ComparativeEconomicsDevelopmentSystemsLab export/version failed.');
if(Lab.definitions.length!==48) throw new Error(`Expected 48 methods, found ${Lab.definitions.length}.`);
const missing=Lab.definitions.filter((method)=>!method.equation||!String(method.equation).trim());
if(missing.length) throw new Error(`Methods without visible formulas: ${missing.map((item)=>item.id).join(', ')}`);
const rows=Lab.runBenchmarks(); const failed=rows.filter((row)=>!row.passed);
if(failed.length) throw new Error(JSON.stringify(failed,null,2));
const record=Lab.run('de.gdp_per_capita',{gdpMillionUsd:12,population:1000});
if(record.outputs.gdpPerCapitaUsd!==12000) throw new Error('GDP-per-capita calculation failed.');
if(!source.includes('Economic or development-systems formula')||!source.includes('Executable output expressions')||!source.includes('autoInit')) throw new Error('Formula-visible interface markers are missing.');
console.log(`Comparative economics/development systems JS tests passed: ${Lab.definitions.length} methods, ${rows.length} benchmarks.`);
