const fs=require('fs');const assert=require('assert');
const read=p=>fs.readFileSync(p,'utf8');
const js=read('assets/js/modules/carbon-mrv-protocol-v0960.js');
const css=read('assets/css/sc-lab-carbon-mrv-protocol-v0960.css');
const tpl=read('templates/lab-app.php');
const plugin=read('includes/class-sc-lab-plugin.php');
const rest=read('includes/class-sc-lab-rest.php');
const main=read('sustainable-catalyst-lab.php');
assert(js.includes("VERSION='0.96.0',DOMAIN='0.13.0'"));
assert(js.includes('ready_for_internal_review'));
assert(js.includes('library-methodology:soc-direct-measurement'));
assert(css.includes('.sc-mrv1300'));
assert(tpl.includes('MRV Protocol Builder'));
assert(tpl.includes('data-mrv-v1300-build'));
assert(tpl.includes('data-mrv-v1300-section-uncertainty_plan'));
assert(tpl.includes('Protocol boundary:'));
assert(plugin.includes("'carbon-mrv-protocol-v0960'"));
assert(plugin.includes("'carbonMrvProtocol'"));
assert(rest.includes('/carbon-nature/mrv/v1300/protocol/build'));
assert(main.includes('class-sc-lab-carbon-mrv-protocol-v0960.php'));
console.log('PASS - Lab v0.96.0 / Carbon & Nature v0.13.0 browser contracts');
