const fs=require('fs'),vm=require('vm'),assert=require('assert');
const calls=[];
function fakeGL(){let id=1;const obj=()=>({id:id++});return {
 VERTEX_SHADER:1,FRAGMENT_SHADER:2,COMPILE_STATUS:3,LINK_STATUS:4,ARRAY_BUFFER:5,ELEMENT_ARRAY_BUFFER:6,STATIC_DRAW:7,STREAM_DRAW:8,FLOAT:9,UNSIGNED_INT:10,POINTS:11,LINES:12,TRIANGLES:13,TEXTURE_2D:14,TEXTURE0:15,RGBA:16,RGBA8:17,UNSIGNED_BYTE:18,LINEAR:19,NEAREST:20,CLAMP_TO_EDGE:21,TEXTURE_MIN_FILTER:22,TEXTURE_MAG_FILTER:23,TEXTURE_WRAP_S:24,TEXTURE_WRAP_T:25,DEPTH_TEST:26,BLEND:27,SRC_ALPHA:28,ONE_MINUS_SRC_ALPHA:29,CULL_FACE:30,FRONT:31,BACK:32,LEQUAL:33,COLOR_BUFFER_BIT:1,DEPTH_BUFFER_BIT:2,FRAMEBUFFER:34,RENDERBUFFER:35,DEPTH_COMPONENT24:36,DEPTH_ATTACHMENT:37,COLOR_ATTACHMENT0:38,FRAMEBUFFER_COMPLETE:39,
 createShader:obj,shaderSource(){},compileShader(){},getShaderParameter(){return true},getShaderInfoLog(){return''},deleteShader(){},createProgram:obj,attachShader(){},linkProgram(){},getProgramParameter(){return true},getProgramInfoLog(){return''},deleteProgram(){},createVertexArray:obj,bindVertexArray(){},createBuffer:obj,bindBuffer(){},bufferData(){},enableVertexAttribArray(){},vertexAttribPointer(){},vertexAttribDivisor(){},disableVertexAttribArray(){},vertexAttrib3f(){},useProgram(){},getUniformLocation(){return{}},uniformMatrix4fv(){},uniform1f(){},uniform1i(){},uniform4fv(){},drawElementsInstanced(){calls.push('drawElementsInstanced')},drawElements(){calls.push('drawElements')},drawArraysInstanced(){calls.push('drawArraysInstanced')},drawArrays(){calls.push('drawArrays')},viewport(){},clearColor(){},enable(){},disable(){},depthMask(){},blendFunc(){},cullFace(){},depthFunc(){},clear(){},createTexture:obj,activeTexture(){},bindTexture(){},texParameteri(){},texImage2D(){},createFramebuffer:obj,createRenderbuffer:obj,bindRenderbuffer(){},renderbufferStorage(){},bindFramebuffer(){},framebufferTexture2D(){},framebufferRenderbuffer(){},checkFramebufferStatus(){return 39},readPixels(x,y,w,h,fmt,type,p){p[0]=1;p[1]=0;p[2]=0;p[3]=0},deleteFramebuffer(){},deleteTexture(){},deleteRenderbuffer(){},isBuffer(){return false},isVertexArray(){return false},isTexture(){return false}
};}
const gl=fakeGL(),canvas={width:960,height:540,clientWidth:960,clientHeight:540,getContext(type){return type==='webgl2'?gl:null},getBoundingClientRect(){return{left:0,top:0,width:960,height:540}}};
const document={createElement(){return canvas},readyState:'complete',querySelector(){return null}};const window={document,devicePixelRatio:1,SCLab:{GPURendererArchitectureV0840:{getRegistry(){return{renderers:[{id:'webgl2',implementationReady:false},{id:'canvas3d',implementationReady:true}]}}}},window:null};window.window=window;
const context={window,document,globalThis:window,console,JSON,Math,Error,String,Array,Object,Number,Set,Float32Array,Uint32Array,Uint8Array};vm.createContext(context);vm.runInContext(fs.readFileSync('assets/js/modules/webgl2-scientific-renderer-v0850.js','utf8'),context);
const R=window.SCLabWebGL2ScientificRendererV0850;assert(R);assert.strictEqual(R.version,'0.85.0');assert.strictEqual(R.engineVersion,'2.12.0');assert.strictEqual(R.renderer,'webgl2');assert.strictEqual(R.supported(canvas),true);
const reg=R.registry(),webgl2=reg.renderers.find(x=>x.id==='webgl2');assert.strictEqual(webgl2.implementationReady,true);assert.strictEqual(webgl2.productionRendererReady,true);assert.strictEqual(reg.webgpuProductionRendererReady,false);
const renderer=R.createRenderer(canvas),scene={camera:{eye:[3,3,3],target:[0,0,0],up:[0,0,1]},objects:[{id:'pts',sourceObjectId:'dataset-A',type:'point-cloud',positions:[0,0,0,1,0,0,0,1,0],colors:[1,0,0,1,0,1,0,1,0,0,1,1]}]};const out=renderer.render(scene);assert.strictEqual(out.ok,true);assert.strictEqual(out.depthBuffer,true);assert(calls.includes('drawArrays'));
const pick=renderer.pick(100,100);assert.strictEqual(pick.strategy,'rgba8-framebuffer-object-id');assert.strictEqual(pick.createsObservation,false);assert.strictEqual(pick.hit.sourceObjectId,'dataset-A');
assert.strictEqual(R.boundaries.gpuRequiredForScientificCorrectness,false);assert.strictEqual(R.boundaries.arbitraryShaderSource,false);console.log('PASS - v0.85.0 browser WebGL2 production renderer, depth draw and framebuffer picking');
