<?php
$root=dirname(__DIR__);$bootstrap=file_get_contents($root.'/sustainable-catalyst-lab.php');$plugin=file_get_contents($root.'/includes/class-sc-lab-plugin.php');$template=file_get_contents($root.'/templates/lab-app.php');$class=file_get_contents($root.'/includes/class-sc-lab-scientific-literature-v0630.php');$compute=file_get_contents($root.'/includes/class-sc-lab-python-compute-core-v0261.php');
$checks=array(
 'v0.63 scientific literature PHP class'=>is_file($root.'/includes/class-sc-lab-scientific-literature-v0630.php'),
 'v0.63 backend module'=>is_file($root.'/backend/app/scientific_literature_provenance_v0630.py'),
 'v0.63 backend regression test'=>is_file($root.'/backend/tests/test_scientific_literature_provenance_v0630.py'),
 'v0.63 JS module'=>is_file($root.'/assets/js/modules/scientific-literature-v0630.js'),
 'v0.63 stylesheet'=>is_file($root.'/assets/css/sc-lab-scientific-literature-v0630.css'),
 'Literature source schema'=>is_file($root.'/contracts/scientific-literature-source-v0630.schema.json'),
 'Literature review schema'=>is_file($root.'/contracts/scientific-literature-review-v0630.schema.json'),
 'Source claim provenance schema'=>is_file($root.'/contracts/source-claim-provenance-v0630.schema.json'),
 'Citation graph schema'=>is_file($root.'/contracts/scientific-citation-graph-v0630.schema.json'),
 'Literature packet schema'=>is_file($root.'/contracts/scientific-literature-provenance-packet-v0630.schema.json'),
 'Literature policy'=>is_file($root.'/contracts/scientific-literature-policy-v0630.json'),
 'WordPress plugin header reports v0.63.0'=>preg_match('/^\s*\*\s*Version:\s*0\.63\.0\s*$/m',$bootstrap)===1,
 'Release constant reports v0.63.0'=>strpos($bootstrap,"define('SC_LAB_RELEASE_VERSION', '0.63.0')")!==false,
 'Platform compatibility remains v1.0.0'=>strpos($bootstrap,"define('SC_LAB_PLATFORM_VERSION', '1.0.0')")!==false,
 'Bootstrap initializes scientific literature'=>strpos($bootstrap,'SC_Lab_Scientific_Literature_V0630::init()')!==false,
 'v0.62 scientific claims retained'=>strpos($bootstrap,'SC_Lab_Scientific_Claims_V0620::init()')!==false,
 'Literature provenance remains contextual in workflow workspace'=>strpos($template,'data-scientific-literature-v0630')!==false,
 'Three application row preserved'=>strpos($template,'Prototyping Workbench')!==false&&strpos($template,'Decision Studio')!==false&&strpos($template,'Site Intelligence')!==false,
 'Six destination rail preserved'=>substr_count($template,'data-v0483-primary=')===6,
 'Health requires human source review'=>strpos($class,"'humanSourceReviewRequired'=>true")!==false,
 'Health disables automatic truth scoring'=>strpos($class,"'automaticTruthScoring'=>false")!==false,
 'Health disables authority ranking'=>strpos($class,"'automaticAuthorityRanking'=>false")!==false,
 'Health disables automatic retraction verification'=>strpos($class,"'automaticRetractionVerification'=>false")!==false,
 'Health disables network fetch during evaluation'=>strpos($class,"'networkFetchDuringEvaluation'=>false")!==false,
 'Literature evaluate proxy route'=>strpos($compute,"/compute/core/scientific-literature/v0630/evaluate")!==false,
 'Source review proxy route'=>strpos($compute,"/compute/core/scientific-literature/v0630/review-source")!==false,
 'Literature packet proxy route'=>strpos($compute,"/compute/core/scientific-literature/v0630/packet")!==false,
 'v0.63 stylesheet enqueued'=>strpos($plugin,'sc-lab-scientific-literature-v0630')!==false,
 'v0.63 JS module registered'=>strpos($plugin,"'scientific-literature-v0630'")!==false,
);
foreach($checks as $label=>$ok){if(!$ok){fwrite(STDERR,"FAIL - $label\n");exit(1);}echo "PASS - $label\n";}
