<?php
$root=dirname(__DIR__);$bootstrap=file_get_contents($root.'/sustainable-catalyst-lab.php');$plugin=file_get_contents($root.'/includes/class-sc-lab-plugin.php');$template=file_get_contents($root.'/templates/lab-app.php');$class=file_get_contents($root.'/includes/class-sc-lab-scientific-claims-v0620.php');$compute=file_get_contents($root.'/includes/class-sc-lab-python-compute-core-v0261.php');
$checks=array(
 'v0.62 scientific claims PHP class'=>is_file($root.'/includes/class-sc-lab-scientific-claims-v0620.php'),
 'v0.62 backend module'=>is_file($root.'/backend/app/scientific_claims_traceability_v0620.py'),
 'v0.62 backend regression test'=>is_file($root.'/backend/tests/test_scientific_claims_traceability_v0620.py'),
 'v0.62 JS module'=>is_file($root.'/assets/js/modules/scientific-claims-v0620.js'),
 'v0.62 stylesheet'=>is_file($root.'/assets/css/sc-lab-scientific-claims-v0620.css'),
 'Scientific claim schema'=>is_file($root.'/contracts/scientific-claim-v0620.schema.json'),
 'Scientific conclusion schema'=>is_file($root.'/contracts/scientific-conclusion-v0620.schema.json'),
 'Evidence matrix schema'=>is_file($root.'/contracts/scientific-evidence-matrix-v0620.schema.json'),
 'Claim review schema'=>is_file($root.'/contracts/scientific-claim-review-v0620.schema.json'),
 'Conclusion traceability packet schema'=>is_file($root.'/contracts/conclusion-traceability-packet-v0620.schema.json'),
 'Claims policy'=>is_file($root.'/contracts/scientific-claims-policy-v0620.json'),
 'WordPress plugin header reports v0.62.0'=>preg_match('/^\s*\*\s*Version:\s*0\.62\.0\s*$/m',$bootstrap)===1,
 'Release constant reports v0.62.0'=>strpos($bootstrap,"define('SC_LAB_RELEASE_VERSION', '0.62.0')")!==false,
 'Platform compatibility remains v1.0.0'=>strpos($bootstrap,"define('SC_LAB_PLATFORM_VERSION', '1.0.0')")!==false,
 'Bootstrap initializes scientific claims'=>strpos($bootstrap,'SC_Lab_Scientific_Claims_V0620::init()')!==false,
 'v0.61 scientific study lifecycle retained'=>strpos($bootstrap,'SC_Lab_Scientific_Study_Lifecycle_V0610::init()')!==false,
 'Claims traceability remains contextual in workflow workspace'=>strpos($template,'data-scientific-claims-v0620')!==false,
 'Three application row preserved'=>strpos($template,'Prototyping Workbench')!==false&&strpos($template,'Decision Studio')!==false&&strpos($template,'Site Intelligence')!==false,
 'Six destination rail preserved'=>substr_count($template,'data-v0483-primary=')===6,
 'Health requires human claim review'=>strpos($class,"'humanClaimReviewRequired'=>true")!==false,
 'Health requires human conclusion review'=>strpos($class,"'humanConclusionReviewRequired'=>true")!==false,
 'Health disables automatic claim inference'=>strpos($class,"'automaticClaimInference'=>false")!==false,
 'Health disables automatic causal claims'=>strpos($class,"'automaticCausalClaim'=>false")!==false,
 'Health disables automatic conclusion generation'=>strpos($class,"'automaticConclusionGeneration'=>false")!==false,
 'Claim evaluate proxy route'=>strpos($compute,"/compute/core/scientific-claims/v0620/evaluate")!==false,
 'Claim review proxy route'=>strpos($compute,"/compute/core/scientific-claims/v0620/review-claim")!==false,
 'Traceability packet proxy route'=>strpos($compute,"/compute/core/scientific-claims/v0620/packet")!==false,
 'v0.62 stylesheet enqueued'=>strpos($plugin,'sc-lab-scientific-claims-v0620')!==false,
 'v0.62 JS module registered'=>strpos($plugin,"'scientific-claims-v0620'")!==false,
);
foreach($checks as $label=>$ok){if(!$ok){fwrite(STDERR,"FAIL - $label\n");exit(1);}echo "PASS - $label\n";}
