const fs=require('fs');const assert=require('assert');
const read=p=>fs.readFileSync(p,'utf8');
const js=read('assets/js/modules/carbon-mrv-uncertainty-v0980.js');
const css=read('assets/css/sc-lab-carbon-mrv-uncertainty-v0980.css');
const tpl=read('templates/lab-app.php');
const plugin=read('includes/class-sc-lab-plugin.php');
const rest=read('includes/class-sc-lab-rest.php');
const main=read('sustainable-catalyst-lab.php');
assert(js.includes("VERSION='0.98.0',DOMAIN='0.15.0'"));
assert(js.includes('combined_standard_uncertainty'));
assert(js.includes('detection_threshold'));
assert(js.includes('recommended_pairs'));
assert(css.includes('.sc-mrv1500'));
assert(tpl.includes('MRV Uncertainty &amp; Detection Engine'));
assert(tpl.includes('data-mrv-v1500-budget-calc'));
assert(tpl.includes('data-mrv-v1500-detect'));
assert(tpl.includes('data-mrv-v1500-plan-calc'));
assert(plugin.includes("'carbon-mrv-uncertainty-v0980'"));
assert(plugin.includes("'carbonMrvUncertainty'"));
assert(rest.includes('/carbon-nature/mrv/v1500/uncertainty/build'));
assert(main.includes('class-sc-lab-carbon-mrv-uncertainty-v0980.php'));
console.log('PASS - Lab v0.98.0 / Carbon & Nature v0.15.0 browser contracts');
