const fs=require('fs'),vm=require('vm');
const ctx={window:{}};vm.createContext(ctx);
vm.runInContext(fs.readFileSync('assets/js/modules/scientific-research-operating-system-v01400.js','utf8'),ctx);
const api=ctx.window.SCLabScientificResearchOperatingSystemV01400;
if(!api||api.version!=='0.140.0') throw new Error('Research OS client missing');
const p=api.packet({projectId:'p1',phase:'analysis'});
if(p.declaredPhase!=='analysis'||p.automaticPhaseAdvance!==false||p.automaticScientificValidity!==false) throw new Error('Research OS client boundary failure');
vm.runInContext(fs.readFileSync('assets/js/modules/project-workspace-research-os-v01400.js','utf8'),ctx);
const h=ctx.window.SCLabProjectWorkspaceResearchOSV01400.handoff({projectId:'p1',fingerprint:'abc'});
if(h.automaticImport!==false||h.sourceAuthorityPreserved!==true) throw new Error('handoff boundary failure');
console.log('PASS: Lab v0.140.0 JS contracts');
