const fs=require('fs'),vm=require('vm'),assert=require('assert');
const source=fs.readFileSync('assets/js/modules/scientific-data-binding-v0750.js','utf8');
const graphSource=fs.readFileSync('assets/js/modules/graph-studio-v0750.js','utf8');
const context={console,window:{SCLab:{ScientificVisualizationEngineV0740:{normalize:s=>{const out=JSON.parse(JSON.stringify(s));out.schema='sc-lab-scientific-visualization/0.74.0';out.version='0.74.0';out.renderer=out.kind==='surface-4d'?'canvas4d':'svg2d';out.rendering=out.rendering||{renderer:'svg2d',adapter:'v0740',coordinateSystem:'cartesian-2d',interactive:true};return out;},render:()=>({ok:true})}}},document:{},ResizeObserver:function(){this.observe=()=>{};}};
context.window.window=context.window;context.window.document=context.document;context.window.ResizeObserver=context.ResizeObserver;
vm.createContext(context);vm.runInContext(source,context);
const E=context.window.SCLab.ScientificDataBindingV0750;
assert(E,'v0.75 browser data-binding runtime exported');
assert.strictEqual(E.version,'0.75.0');assert.strictEqual(E.engineVersion,'2.2.0');
const dataset={id:'d1',title:'Observed',units:{time:'s',response:'mg'},rows:[{time:1,response:2,group:'A',z:.2,w:0},{time:2,response:4,group:'A',z:.4,w:.5},{time:3,response:6,group:'B',z:.7,w:1}]};
const transformed=E.executePipeline(dataset,{operations:[{type:'derive',name:'ratio',unit:'mg/s',expression:{op:'divide',args:[{field:'response'},{field:'time'}]}},{type:'sort',by:[{column:'time',direction:'desc'}]}]});
assert.strictEqual(transformed.rows[0].time,3);assert.strictEqual(transformed.rows[0].ratio,2);assert.strictEqual(transformed.lineage.length,2);assert(/^[a-f0-9]{64}$/.test(transformed.fingerprint));
const bound=E.bind({dataset,pipeline:{operations:[{type:'filter',column:'time',operator:'gte',value:2}]},binding:{kind:'line',mappings:{x:'time',y:'response',group:'group'}},figure:{title:'Bound line'}});
assert.strictEqual(bound.spec.schema,'sc-lab-scientific-visualization/0.75.0');assert.strictEqual(bound.spec.visualizationEngine,'2.2.0');assert.strictEqual(bound.spec.rendering.dataMode,'project-data-bound');assert.strictEqual(bound.spec.series.length,2);assert.strictEqual(bound.provenance.datasetId,'d1');
const four=E.bind({dataset,binding:{kind:'surface-4d',mappings:{x:'time',y:'response',z:'z',w:'w',label:'group'}},figure:{title:'4D observed'}});
assert.strictEqual(four.spec.profile,'project-data');assert.strictEqual(four.spec.dataBinding.pointCount,3);assert.strictEqual(four.spec.surface.layers.surface,false);assert(four.spec.dataBoundary.includes('does not interpolate'));
for(const needle of ["q75('pipeline')","q75('dataset-id')","q75('surface-mode')",'scientific-figure-v0750','Engine ${ENGINE}'])assert(graphSource.includes(needle),`Graph Studio v0.75 missing ${needle}`);
console.log('PASS - Scientific Data Binding v0.75 browser contract');
console.log('PASS - governed transformation lineage and structured derive');
console.log('PASS - Graph Studio v0.75 dataset / pipeline / binding controls');
console.log('PASS - project-data 4D point projection boundary');
