const fs=require('fs');const assert=require('assert');
const read=p=>fs.readFileSync(p,'utf8');
const js=read('assets/js/modules/carbon-mrv-reporting-v01000.js');
const css=read('assets/css/sc-lab-carbon-mrv-reporting-v01000.css');
const tpl=read('templates/lab-app.php');
const plugin=read('includes/class-sc-lab-plugin.php');
const rest=read('includes/class-sc-lab-rest.php');
const main=read('sustainable-catalyst-lab.php');
assert(js.includes("VERSION='0.100.0',DOMAIN='0.17.0'"));
assert(js.includes('auditPacketUrl'));
assert(js.includes('verification-record'));
assert(js.includes('calculation_reperformed')===false || js.includes('does not silently recalculate'));
assert(css.includes('.sc-mrv1700'));
assert(tpl.includes('MRV Reporting &amp; Audit Packets'));
assert(tpl.includes('data-mrv-v1700-audit'));
assert(tpl.includes('data-mrv-v1700-artifacts'));
assert(plugin.includes("'carbon-mrv-reporting-v01000'"));
assert(plugin.includes("'carbonMrvReporting'"));
assert(rest.includes('/carbon-nature/mrv/v1700/reporting/audit-packet/build'));
assert(main.includes('class-sc-lab-carbon-mrv-reporting-v01000.php'));
console.log('PASS - Lab v0.100.0 / Carbon & Nature v0.17.0 browser contracts');
