! Kinetic energy and momentum
! Method: kinetic v0.9.3
! Equation: KE = 1/2 mv²; p = mv
! Generated by Sustainable Catalyst Lab v0.9.3
! Portable reference implementation; review assumptions and units.
program sc_lab_method
  implicit none
  real(8) :: mass = 1.0000000000000000d+1
  real(8) :: velocity = 5.0000000000000000d+0

  real(8) :: kinetic_energy_j
  real(8) :: momentum_kg_ms
  kinetic_energy_j = (5.0000000000000000d-1 * mass * (velocity) ** (2.0000000000000000d+0))
  momentum_kg_ms = (mass * velocity)
  print *, 'kinetic_energy_j=', kinetic_energy_j
  print *, 'momentum_kg_ms=', momentum_kg_ms
end program sc_lab_method
