/**
 * Kinetic energy and momentum
 * Method: kinetic v0.9.3
 * Equation: KE = 1/2 mv²; p = mv
 * Generated by Sustainable Catalyst Lab v0.9.3
 * Portable reference implementation; review assumptions and units.
 */
function calculate(mass = 10, velocity = 5) {
  const kinetic_energy_j = (0.5 * mass * (velocity) ** (2));
  const momentum_kg_ms = (mass * velocity);
  return { kinetic_energy_j, momentum_kg_ms };
}

console.log(calculate());
