// Kinetic energy and momentum
// Method: kinetic v0.9.3
// Equation: KE = 1/2 mv²; p = mv
// Generated by Sustainable Catalyst Lab v0.9.3
// Portable reference implementation; review assumptions and units.
package main

import (
  "fmt"
  "math"
)

var _ = math.Pi

func calculate(mass float64, velocity float64) (kinetic_energy_j float64, momentum_kg_ms float64) {

  kinetic_energy_j = (0.5 * mass * math.Pow(velocity, 2.0))
  momentum_kg_ms = (mass * velocity)
  return
}

func main() {
  fmt.Println(calculate(10.0, 5.0))
}
