/* Kinetic energy and momentum
 * Method: kinetic v0.9.3
 * Equation: KE = 1/2 mv²; p = mv
 * Generated by Sustainable Catalyst Lab v0.9.3
 * Portable reference implementation; review assumptions and units. */
#include <math.h>
#include <stdio.h>

int main(void) {
  double mass = 10.0;
  double velocity = 5.0;

  double kinetic_energy_j = (0.5 * mass * pow(velocity, 2.0));
  double momentum_kg_ms = (mass * velocity);
  printf("kinetic_energy_j=%.12g\n", kinetic_energy_j);
  printf("momentum_kg_ms=%.12g\n", momentum_kg_ms);
  return 0;
}
