-- Kinetic energy and momentum
-- Method: kinetic v0.9.3
-- Equation: KE = 1/2 mv²; p = mv
-- Generated by Sustainable Catalyst Lab v0.9.3
-- Portable reference implementation; review assumptions and units.
module Main where

calculate :: Double -> Double -> (Double, Double)
calculate mass velocity =
  let

    kinetic_energy_j = (0.5 * mass * (velocity) ** (2.0))
    momentum_kg_ms = (mass * velocity)
  in (kinetic_energy_j, momentum_kg_ms)

main :: IO ()
main = print (calculate 10.0 5.0)
