// Kinetic energy and momentum
// Method: kinetic v0.9.3
// Equation: KE = 1/2 mv²; p = mv
// Generated by Sustainable Catalyst Lab v0.9.3
// Portable reference implementation; review assumptions and units.
fn calculate(mass: f64, velocity: f64) -> (f64, f64) {

    let kinetic_energy_j: f64 = (0.5 * mass * (velocity).powf(2.0));
    let momentum_kg_ms: f64 = (mass * velocity);
    (kinetic_energy_j, momentum_kg_ms)
}

fn main() {
    let result = calculate(10.0, 5.0);
    println!("{:?}", result);
}
