-- Kinetic energy and momentum
-- Method: kinetic v0.9.3
-- Equation: KE = 1/2 mv²; p = mv
-- Generated by Sustainable Catalyst Lab v0.9.3
-- Portable reference implementation; review assumptions and units.
WITH inputs AS (
  SELECT 10 AS mass, 5 AS velocity
), derived AS (
  SELECT *, 1 AS contract_ready FROM inputs
)
SELECT (0.5 * mass * POWER(velocity, 2)) AS kinetic_energy_j, (mass * velocity) AS momentum_kg_ms FROM derived;
