// Kinetic energy and momentum
// Method: kinetic v0.9.3
// Equation: KE = 1/2 mv²; p = mv
// Generated by Sustainable Catalyst Lab v0.9.3
// Portable reference implementation; review assumptions and units.
#include <cmath>
#include <iostream>
#include <numbers>

int main() {
  double mass = 10.0;
  double velocity = 5.0;

  double kinetic_energy_j = (0.5 * mass * std::pow(velocity, 2.0));
  double momentum_kg_ms = (mass * velocity);
  std::cout << "kinetic_energy_j=" << kinetic_energy_j << '\n';
  std::cout << "momentum_kg_ms=" << momentum_kg_ms << '\n';
}
