# Kinetic energy and momentum
# Method: kinetic v0.9.3
# Equation: KE = 1/2 mv²; p = mv
# Generated by Sustainable Catalyst Lab v0.9.3
# Portable reference implementation; review assumptions and units.
function calculate(mass::Float64 = 10, velocity::Float64 = 5)
    kinetic_energy_j = (0.5 * mass * (velocity) ^ (2))
    momentum_kg_ms = (mass * velocity)
    return Dict("kinetic_energy_j" => kinetic_energy_j, "momentum_kg_ms" => momentum_kg_ms)
end
println(calculate())
