// Projectile motion
// Method: projectile v0.9.3
// Equation: y = h + v_y t - 1/2 gt²
// Generated by Sustainable Catalyst Lab v0.9.3
// Portable reference implementation; review assumptions and units.
#include <cmath>
#include <iostream>
#include <numbers>

int main() {
  double speed = 20.0;
  double angle_deg = 45.0;
  double height = 0.0;
  constexpr double g = 9.80665;
  double angle_rad = (angle_deg * (std::numbers::pi / 180.0));
  double velocity_y = (speed * std::sin(angle_rad));
  double flight_time_s = ((velocity_y + std::sqrt((std::pow(velocity_y, 2.0) + (2.0 * g * height)))) / g);
  double range_m = (speed * std::cos(angle_rad) * flight_time_s);
  double max_height_m = (height + (std::pow(velocity_y, 2.0) / (2.0 * g)));
  std::cout << "flight_time_s=" << flight_time_s << '\n';
  std::cout << "range_m=" << range_m << '\n';
  std::cout << "max_height_m=" << max_height_m << '\n';
}
