// Projectile motion
// Method: projectile v0.9.3
// Equation: y = h + v_y t - 1/2 gt²
// Generated by Sustainable Catalyst Lab v0.9.3
// Portable reference implementation; review assumptions and units.
package main

import (
  "fmt"
  "math"
)

var _ = math.Pi

func calculate(speed float64, angle_deg float64, height float64) (flight_time_s float64, range_m float64, max_height_m float64) {
  g := 9.80665
  angle_rad := (angle_deg * (math.Pi / 180.0))
  velocity_y := (speed * math.Sin(angle_rad))
  flight_time_s = ((velocity_y + math.Sqrt((math.Pow(velocity_y, 2.0) + (2.0 * g * height)))) / g)
  range_m = (speed * math.Cos(angle_rad) * flight_time_s)
  max_height_m = (height + (math.Pow(velocity_y, 2.0) / (2.0 * g)))
  return
}

func main() {
  fmt.Println(calculate(20.0, 45.0, 0.0))
}
