/* Projectile motion
 * Method: projectile v0.9.3
 * Equation: y = h + v_y t - 1/2 gt²
 * Generated by Sustainable Catalyst Lab v0.9.3
 * Portable reference implementation; review assumptions and units. */
#include <math.h>
#include <stdio.h>

int main(void) {
  double speed = 20.0;
  double angle_deg = 45.0;
  double height = 0.0;
  const double g = 9.80665;
  double angle_rad = (angle_deg * (acos(-1.0) / 180.0));
  double velocity_y = (speed * sin(angle_rad));
  double flight_time_s = ((velocity_y + sqrt((pow(velocity_y, 2.0) + (2.0 * g * height)))) / g);
  double range_m = (speed * cos(angle_rad) * flight_time_s);
  double max_height_m = (height + (pow(velocity_y, 2.0) / (2.0 * g)));
  printf("flight_time_s=%.12g\n", flight_time_s);
  printf("range_m=%.12g\n", range_m);
  printf("max_height_m=%.12g\n", max_height_m);
  return 0;
}
