-- Projectile motion
-- Method: projectile v0.9.3
-- Equation: y = h + v_y t - 1/2 gt²
-- Generated by Sustainable Catalyst Lab v0.9.3
-- Portable reference implementation; review assumptions and units.
WITH inputs AS (
  SELECT 20 AS speed, 45 AS angle_deg, 0 AS height, 9.80665 AS g
), derived AS (
  SELECT *, (angle_deg * (PI() / 180)) AS angle_rad, (speed * SIN(angle_rad)) AS velocity_y FROM inputs
)
SELECT ((velocity_y + SQRT((POWER(velocity_y, 2) + (2 * g * height)))) / g) AS flight_time_s, (speed * COS(angle_rad) * flight_time_s) AS range_m, (height + (POWER(velocity_y, 2) / (2 * g))) AS max_height_m FROM derived;
