# Projectile motion
# Method: projectile v0.9.3
# Equation: y = h + v_y t - 1/2 gt²
# Generated by Sustainable Catalyst Lab v0.9.3
# Portable reference implementation; review assumptions and units.
calculate <- function(speed = 20, angle_deg = 45, height = 0) {
  g <- 9.80665
  angle_rad <- (angle_deg * (pi / 180))
  velocity_y <- (speed * sin(angle_rad))
  flight_time_s <- ((velocity_y + sqrt(((velocity_y) ^ (2) + (2 * g * height)))) / g)
  range_m <- (speed * cos(angle_rad) * flight_time_s)
  max_height_m <- (height + ((velocity_y) ^ (2) / (2 * g)))
  list(flight_time_s = flight_time_s, range_m = range_m, max_height_m = max_height_m)
}
print(calculate())
