-- Projectile motion
-- Method: projectile v0.9.3
-- Equation: y = h + v_y t - 1/2 gt²
-- Generated by Sustainable Catalyst Lab v0.9.3
-- Portable reference implementation; review assumptions and units.
module Main where

calculate :: Double -> Double -> Double -> (Double, Double, Double)
calculate speed angle_deg height =
  let
    g = 9.80665
    angle_rad = (angle_deg * (pi / 180.0))
    velocity_y = (speed * sin(angle_rad))
    flight_time_s = ((velocity_y + sqrt(((velocity_y) ** (2.0) + (2.0 * g * height)))) / g)
    range_m = (speed * cos(angle_rad) * flight_time_s)
    max_height_m = (height + ((velocity_y) ** (2.0) / (2.0 * g)))
  in (flight_time_s, range_m, max_height_m)

main :: IO ()
main = print (calculate 20.0 45.0 0.0)
