/**
 * Projectile motion
 * Method: projectile v0.9.3
 * Equation: y = h + v_y t - 1/2 gt²
 * Generated by Sustainable Catalyst Lab v0.9.3
 * Portable reference implementation; review assumptions and units.
 */
function calculate(speed = 20, angle_deg = 45, height = 0) {
  const g = 9.80665;
  const angle_rad = (angle_deg * (Math.PI / 180));
  const velocity_y = (speed * Math.sin(angle_rad));
  const flight_time_s = ((velocity_y + Math.sqrt(((velocity_y) ** (2) + (2 * g * height)))) / g);
  const range_m = (speed * Math.cos(angle_rad) * flight_time_s);
  const max_height_m = (height + ((velocity_y) ** (2) / (2 * g)));
  return { flight_time_s, range_m, max_height_m };
}

console.log(calculate());
