// Projectile motion
// Method: projectile v0.9.3
// Equation: y = h + v_y t - 1/2 gt²
// Generated by Sustainable Catalyst Lab v0.9.3
// Portable reference implementation; review assumptions and units.
fn calculate(speed: f64, angle_deg: f64, height: f64) -> (f64, f64, f64) {
    let g: f64 = 9.80665;
    let angle_rad: f64 = (angle_deg * (std::f64::consts::PI / 180.0));
    let velocity_y: f64 = (speed * (angle_rad).sin());
    let flight_time_s: f64 = ((velocity_y + (((velocity_y).powf(2.0) + (2.0 * g * height))).sqrt()) / g);
    let range_m: f64 = (speed * (angle_rad).cos() * flight_time_s);
    let max_height_m: f64 = (height + ((velocity_y).powf(2.0) / (2.0 * g)));
    (flight_time_s, range_m, max_height_m)
}

fn main() {
    let result = calculate(20.0, 45.0, 0.0);
    println!("{:?}", result);
}
