"""Projectile motion
Method: projectile v0.9.3
Equation: y = h + v_y t - 1/2 gt²
Generated by Sustainable Catalyst Lab v0.9.3
Portable reference implementation; review assumptions and units."""
import math

def calculate(speed: float = 20, angle_deg: float = 45, height: float = 0) -> dict[str, float]:
    g = 9.80665
    angle_rad = (angle_deg * (math.pi / 180))
    velocity_y = (speed * math.sin(angle_rad))
    flight_time_s = ((velocity_y + math.sqrt(((velocity_y) ** (2) + (2 * g * height)))) / g)
    range_m = (speed * math.cos(angle_rad) * flight_time_s)
    max_height_m = (height + ((velocity_y) ** (2) / (2 * g)))
    return {"flight_time_s": flight_time_s, "range_m": range_m, "max_height_m": max_height_m}

if __name__ == "__main__":
    print(calculate())
