! Projectile motion
! Method: projectile v0.9.3
! Equation: y = h + v_y t - 1/2 gt²
! Generated by Sustainable Catalyst Lab v0.9.3
! Portable reference implementation; review assumptions and units.
program sc_lab_method
  implicit none
  real(8) :: speed = 2.0000000000000000d+1
  real(8) :: angle_deg = 4.5000000000000000d+1
  real(8) :: height = 0.0000000000000000d+0
  real(8), parameter :: g = 9.8066499999999994d+0
  real(8) :: angle_rad
  real(8) :: velocity_y
  real(8) :: flight_time_s
  real(8) :: range_m
  real(8) :: max_height_m
  angle_rad = (angle_deg * (acos(-1.0d0) / 1.8000000000000000d+2))
  velocity_y = (speed * sin(angle_rad))
  flight_time_s = ((velocity_y + sqrt(((velocity_y) ** (2.0000000000000000d+0) + (2.0000000000000000d+0 * g * height)))) / g)
  range_m = (speed * cos(angle_rad) * flight_time_s)
  max_height_m = (height + ((velocity_y) ** (2.0000000000000000d+0) / (2.0000000000000000d+0 * g)))
  print *, 'flight_time_s=', flight_time_s
  print *, 'range_m=', range_m
  print *, 'max_height_m=', max_height_m
end program sc_lab_method
