from __future__ import annotations

from typing import Any

from .expressions import assignments, literal, snake

EXECUTABLE_LANGUAGES = {
    "python",
    "javascript",
    "typescript",
    "c",
    "cpp",
    "fortran",
    "rust",
    "go",
}


def _header(contract: dict[str, Any], language: str) -> str:
    return (
        f"{contract.get('name')}\n"
        f"Method: {contract.get('id')} v{contract.get('version')}\n"
        f"Equation: {contract.get('equation')}\n"
        "Generated by Sustainable Catalyst Lab compute dispatcher v0.9.3\n"
        f"Curated {language} implementation; arbitrary source execution is disabled."
    )


def generate_source(contract: dict[str, Any], language: str, inputs: dict[str, float]) -> tuple[str, str]:
    if language not in EXECUTABLE_LANGUAGES:
        raise ValueError(f"Native execution is not enabled for {language} in v0.9.3.")

    rows = assignments(contract, language)
    outputs = [row for row in rows if row["output"]]
    constants = [
        (snake(key), literal(float(value), language))
        for key, value in (contract.get("constants") or {}).items()
    ]
    values = [(snake(key), literal(value, language)) for key, value in inputs.items()]
    header = _header(contract, language)

    if language == "python":
        source = f'''"""{header}"""
import json
import math

{chr(10).join(f"{name} = {value}" for name, value in values)}
{chr(10).join(f"{name} = {value}" for name, value in constants)}
{chr(10).join(f"{row['name']} = {row['expression']}" for row in rows)}
result = {{{", ".join(repr(row['id']) + ": " + row['name'] for row in outputs)}}}
print("SC_RESULT " + json.dumps(result, sort_keys=True, separators=(",", ":")))
'''
        return "method.py", source

    if language in {"javascript", "typescript"}:
        type_suffix = ": number" if language == "typescript" else ""
        declarations = [f"const {name}{type_suffix} = {value};" for name, value in values]
        declarations += [f"const {name}{type_suffix} = {value};" for name, value in constants]
        declarations += [f"const {row['name']}{type_suffix} = {row['expression']};" for row in rows]
        source = f'''/**
 * {header.replace(chr(10), chr(10) + " * ")}
 */
{chr(10).join(declarations)}
const result = {{ {", ".join(repr(row['id']) + ": " + row['name'] for row in outputs)} }};
console.log("SC_RESULT " + JSON.stringify(result));
'''
        return ("method.ts" if language == "typescript" else "method.js"), source

    if language == "c":
        source = f'''/* {header.replace(chr(10), chr(10) + " * ")} */
#include <math.h>
#include <stdio.h>

int main(void) {{
{chr(10).join(f"  double {name} = {value};" for name, value in values)}
{chr(10).join(f"  const double {name} = {value};" for name, value in constants)}
{chr(10).join(f"  double {row['name']} = {row['expression']};" for row in rows)}
{chr(10).join(f'  printf("SC_RESULT {row["id"]}=%.17g\\n", {row["name"]});' for row in outputs)}
  return 0;
}}
'''
        return "method.c", source

    if language == "cpp":
        source = f'''// {header.replace(chr(10), chr(10) + "// ")}
#include <cmath>
#include <iomanip>
#include <iostream>
#include <numbers>

int main() {{
{chr(10).join(f"  double {name} = {value};" for name, value in values)}
{chr(10).join(f"  constexpr double {name} = {value};" for name, value in constants)}
{chr(10).join(f"  double {row['name']} = {row['expression']};" for row in rows)}
  std::cout << std::setprecision(17);
{chr(10).join(f'  std::cout << "SC_RESULT {row["id"]}=" << {row["name"]} << "\\n";' for row in outputs)}
  return 0;
}}
'''
        return "method.cpp", source

    if language == "fortran":
        declarations = [f"  real(8) :: {name} = {value}" for name, value in values]
        declarations += [f"  real(8), parameter :: {name} = {value}" for name, value in constants]
        declarations += [f"  real(8) :: {row['name']}" for row in rows]
        calculations = [f"  {row['name']} = {row['expression']}" for row in rows]
        prints = [f"  print '(A,ES26.17E3)', 'SC_RESULT {row['id']}=', {row['name']}" for row in outputs]
        source = f'''! {header.replace(chr(10), chr(10) + "! ")}
program sc_lab_method
  implicit none
{chr(10).join(declarations)}
{chr(10).join(calculations)}
{chr(10).join(prints)}
end program sc_lab_method
'''
        return "method.f90", source

    if language == "rust":
        source = f'''// {header.replace(chr(10), chr(10) + "// ")}
fn main() {{
{chr(10).join(f"    let {name}: f64 = {value};" for name, value in values)}
{chr(10).join(f"    let {name}: f64 = {value};" for name, value in constants)}
{chr(10).join(f"    let {row['name']}: f64 = {row['expression']};" for row in rows)}
{chr(10).join(f'    println!("SC_RESULT {row["id"]}={{:.17e}}", {row["name"]});' for row in outputs)}
}}
'''
        return "method.rs", source

    if language == "go":
        source = f'''// {header.replace(chr(10), chr(10) + "// ")}
package main

import (
    "fmt"
    "math"
)

var _ = math.Pi

func main() {{
{chr(10).join(f"    {name} := {value}" for name, value in values)}
{chr(10).join(f"    {name} := {value}" for name, value in constants)}
{chr(10).join(f"    {row['name']} := {row['expression']}" for row in rows)}
{chr(10).join(f'    fmt.Printf("SC_RESULT {row["id"]}=%.17g\\n", {row["name"]})' for row in outputs)}
}}
'''
        return "method.go", source

    raise ValueError(f"Source generation is unavailable for {language}.")
