// Michaelis-Menten kinetics
// Method: michaelis v0.9.3
// Equation: v = Vmax[S]/(Km+[S])
// Generated by Sustainable Catalyst Lab v0.9.3
// Portable reference implementation; review assumptions and units.
fn calculate(vmax: f64, substrate: f64, km: f64) -> (f64) {

    let rate: f64 = ((vmax * substrate) / (km + substrate));
    (rate)
}

fn main() {
    let result = calculate(100.0, 8.0, 2.0);
    println!("{:?}", result);
}
