// Michaelis-Menten kinetics
// Method: michaelis v0.9.3
// Equation: v = Vmax[S]/(Km+[S])
// Generated by Sustainable Catalyst Lab v0.9.3
// Portable reference implementation; review assumptions and units.
package main

import (
  "fmt"
  "math"
)

var _ = math.Pi

func calculate(vmax float64, substrate float64, km float64) (rate float64) {

  rate = ((vmax * substrate) / (km + substrate))
  return
}

func main() {
  fmt.Println(calculate(100.0, 8.0, 2.0))
}
