/**
 * Michaelis-Menten kinetics
 * Method: michaelis v0.9.3
 * Equation: v = Vmax[S]/(Km+[S])
 * Generated by Sustainable Catalyst Lab v0.9.3
 * Portable reference implementation; review assumptions and units.
 */
export type Result = { rate: number };

export function calculate(vmax: number = 100, substrate: number = 8, km: number = 2): Result {
  const rate = ((vmax * substrate) / (km + substrate));
  return { rate };
}

console.log(calculate());
