! Michaelis-Menten kinetics
! Method: michaelis v0.9.3
! Equation: v = Vmax[S]/(Km+[S])
! Generated by Sustainable Catalyst Lab v0.9.3
! Portable reference implementation; review assumptions and units.
program sc_lab_method
  implicit none
  real(8) :: vmax = 1.0000000000000000d+2
  real(8) :: substrate = 8.0000000000000000d+0
  real(8) :: km = 2.0000000000000000d+0

  real(8) :: rate
  rate = ((vmax * substrate) / (km + substrate))
  print *, 'rate=', rate
end program sc_lab_method
