# Michaelis-Menten kinetics
# Method: michaelis v0.9.3
# Equation: v = Vmax[S]/(Km+[S])
# Generated by Sustainable Catalyst Lab v0.9.3
# Portable reference implementation; review assumptions and units.
function calculate(vmax::Float64 = 100, substrate::Float64 = 8, km::Float64 = 2)
    rate = ((vmax * substrate) / (km + substrate))
    return Dict("rate" => rate)
end
println(calculate())
