-- Michaelis-Menten kinetics
-- Method: michaelis v0.9.3
-- Equation: v = Vmax[S]/(Km+[S])
-- Generated by Sustainable Catalyst Lab v0.9.3
-- Portable reference implementation; review assumptions and units.
WITH inputs AS (
  SELECT 100 AS vmax, 8 AS substrate, 2 AS km
), derived AS (
  SELECT *, 1 AS contract_ready FROM inputs
)
SELECT ((vmax * substrate) / (km + substrate)) AS rate FROM derived;
