/* Michaelis-Menten kinetics
 * Method: michaelis v0.9.3
 * Equation: v = Vmax[S]/(Km+[S])
 * Generated by Sustainable Catalyst Lab v0.9.3
 * Portable reference implementation; review assumptions and units. */
#include <math.h>
#include <stdio.h>

int main(void) {
  double vmax = 100.0;
  double substrate = 8.0;
  double km = 2.0;

  double rate = ((vmax * substrate) / (km + substrate));
  printf("rate=%.12g\n", rate);
  return 0;
}
