"""Michaelis-Menten kinetics
Method: michaelis v0.9.3
Equation: v = Vmax[S]/(Km+[S])
Generated by Sustainable Catalyst Lab v0.9.3
Portable reference implementation; review assumptions and units."""
import math

def calculate(vmax: float = 100, substrate: float = 8, km: float = 2) -> dict[str, float]:
    rate = ((vmax * substrate) / (km + substrate))
    return {"rate": rate}

if __name__ == "__main__":
    print(calculate())
