/**
 * Michaelis-Menten kinetics
 * Method: michaelis v0.9.3
 * Equation: v = Vmax[S]/(Km+[S])
 * Generated by Sustainable Catalyst Lab v0.9.3
 * Portable reference implementation; review assumptions and units.
 */
function calculate(vmax = 100, substrate = 8, km = 2) {
  const rate = ((vmax * substrate) / (km + substrate));
  return { rate };
}

console.log(calculate());
