-- Michaelis-Menten kinetics
-- Method: michaelis v0.9.3
-- Equation: v = Vmax[S]/(Km+[S])
-- Generated by Sustainable Catalyst Lab v0.9.3
-- Portable reference implementation; review assumptions and units.
module Main where

calculate :: Double -> Double -> Double -> (Double)
calculate vmax substrate km =
  let

    rate = ((vmax * substrate) / (km + substrate))
  in (rate)

main :: IO ()
main = print (calculate 100.0 8.0 2.0)
