# Michaelis-Menten kinetics
# Method: michaelis v0.9.3
# Equation: v = Vmax[S]/(Km+[S])
# Generated by Sustainable Catalyst Lab v0.9.3
# Portable reference implementation; review assumptions and units.
calculate <- function(vmax = 100, substrate = 8, km = 2) {
  rate <- ((vmax * substrate) / (km + substrate))
  list(rate = rate)
}
print(calculate())
