<?php
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Visual_Research_Narrative_Figure_Composer_V01180 {
 const VERSION='0.118.0'; const ENGINE_VERSION='3.4.0'; const SCHEMA='sc-lab-visual-research-narrative-figure-composer/0.118.0';
 public static function init(){ add_action('rest_api_init',array(__CLASS__,'routes')); }
 public static function routes(){ $ns='sc-lab/v1/visualization/v01180'; foreach(array('health','manifest','schema','catalog') as $r){register_rest_route($ns,'/'.$r,array('methods'=>'GET','callback'=>array(__CLASS__,$r),'permission_callback'=>'__return_true'));}}
 private static function state($r){$p=SC_LAB_DIR.$r;return array('exists'=>is_file($p),'sha256'=>is_file($p)?hash_file('sha256',$p):null);}
 public static function schema(){return rest_ensure_response(array('ok'=>true,'schema'=>self::SCHEMA,'version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'sectionLimit'=>64,'figureLimit'=>256,'blockLimit'=>1024,'apiRouteCount'=>19));}
 public static function catalog(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'sectionTypes'=>array('abstract','introduction','methods','results','discussion','conclusion','limitations','figure-story','evidence','appendix','supplement'),'figureKinds'=>array('statistical-figure','scientific-figure','dashboard','small-multiples','scientific-3d-4d-scene','map','table','equation','image','diagram','model-view','uncertainty-view'),'narrativeFormats'=>array('journal-article','research-report','technical-memo','methods-note','slide-narrative','web-story','supplement')));}
 public static function manifest(){return rest_ensure_response(array('ok'=>true,'status'=>'visual-research-narrative-figure-composer-ready','version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'referenceFirstFigureRegistry'=>true,'figurePlates'=>true,'declaredCaptions'=>true,'evidenceAwareAnnotations'=>true,'provenanceTrace'=>true,'publicationLayoutPlans'=>true,'publicationPackagePlans'=>true,'revisionSnapshots'=>true,'coreVisualBridge'=>true,'automaticScientificConclusionGeneration'=>false,'automaticFigureMutation'=>false,'automaticCaptionInference'=>false,'automaticRelationshipInference'=>false,'automaticEvidenceWeighting'=>false,'automaticPublication'=>false,'automaticCoreSubmission'=>false,'scientificValidityCertified'=>false));}
 public static function health(){ $req=array('contracts/visual-research-narrative-figure-composer-v01180.schema.json','contracts/visual-research-narrative-figure-composer-policy-v01180.json','includes/class-sc-lab-visual-research-narrative-figure-composer-v01180.php','assets/js/modules/visual-research-narrative-figure-composer-v01180.js','assets/css/sc-lab-visual-research-narrative-figure-composer-v01180.css');$files=array();$ok=true;foreach($req as $r){$files[$r]=self::state($r);if(empty($files[$r]['exists']))$ok=false;}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'visual-research-narrative-figure-composer-ready':'incomplete','version'=>self::VERSION,'labReleaseVersion'=>defined('SC_LAB_RELEASE_VERSION')?SC_LAB_RELEASE_VERSION:self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'sectionTypeCount'=>11,'figureKindCount'=>12,'narrativeFormatCount'=>7,'files'=>$files,'automaticCoreSubmission'=>false,'scientificValidityCertified'=>false,'time'=>gmdate('c')));}
}
SC_Lab_Visual_Research_Narrative_Figure_Composer_V01180::init();
