<?php
/** Biosignal visualization and comparative-analysis REST engine. */
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Biosignal_Visualization_REST_V0232 {
    const VERSION='0.23.2';
    const NAMESPACE='sc-lab/v1';
    public static function boot(){ add_action('rest_api_init',array(__CLASS__,'register_routes')); }
    private static function contract_path(){ return dirname(__DIR__).'/contracts/biosignal-visualization-comparison-v0232.json'; }
    public static function contract(){ $path=self::contract_path(); if(!is_file($path)){return array('version'=>self::VERSION,'modes'=>array(),'analysisMethods'=>array(),'benchmarks'=>array(),'annotationTypes'=>array());} $decoded=json_decode(file_get_contents($path),true); return is_array($decoded)?$decoded:array(); }
    private static function finite($value,$label){ if(!is_numeric($value)||!is_finite((float)$value)){throw new InvalidArgumentException($label.' must be numerical and finite.');} return (float)$value; }
    private static function positive($value,$label){$number=self::finite($value,$label);if($number<=0){throw new InvalidArgumentException($label.' must be greater than zero.');}return $number;}
    private static function values($value,$label,$minimum=1){ if(is_string($value)){ $trimmed=trim($value); if(str_starts_with($trimmed,'[')){ $decoded=json_decode($trimmed,true); if(is_array($decoded)){$value=$decoded;} } else {$value=preg_split('/[,\s]+/',$trimmed,-1,PREG_SPLIT_NO_EMPTY);} } if(!is_array($value)){throw new InvalidArgumentException($label.' must be an array.');} $numbers=array(); foreach($value as $index=>$item){$numbers[]=self::finite($item,$label.'['.$index.']');} if(count($numbers)<$minimum){throw new InvalidArgumentException($label.' requires at least '.$minimum.' values.');} return $numbers; }
    private static function paired($left,$right){$a=self::values($left,'reference',2);$b=self::values($right,'comparison',2);if(count($a)!==count($b)){throw new InvalidArgumentException('reference and comparison must have equal length.');}return array($a,$b);}
    private static function mean($values){return array_sum($values)/count($values);}
    private static function sd($values){if(count($values)<2){return 0.0;}$mean=self::mean($values);$sum=0.0;foreach($values as $value){$sum+=($value-$mean)**2;}return sqrt($sum/(count($values)-1));}
    private static function rms($values){$sum=0.0;foreach($values as $value){$sum+=$value*$value;}return sqrt($sum/count($values));}
    public static function descriptive_features($samples,$sample_rate_hz=1){$values=self::values($samples,'samples',2);$rate=self::positive($sample_rate_hz,'sampleRateHz');$rms=self::rms($values);$crossings=0;for($i=1;$i<count($values);$i++){if(($values[$i-1]<0&&$values[$i]>=0)||($values[$i-1]>=0&&$values[$i]<0)){$crossings++;}}return array('sampleCount'=>count($values),'sampleRateHz'=>$rate,'durationSeconds'=>(count($values)-1)/$rate,'mean'=>self::mean($values),'standardDeviation'=>self::sd($values),'rms'=>$rms,'minimum'=>min($values),'maximum'=>max($values),'peakToPeak'=>max($values)-min($values),'zeroCrossingCount'=>$crossings,'zeroCrossingRate'=>$crossings/(count($values)-1)*$rate,'crestFactor'=>$rms!=0.0?max(array_map('abs',$values))/$rms:0.0);}
    public static function min_max_normalize($samples){$values=self::values($samples,'samples');$minimum=min($values);$span=max($values)-$minimum;if($span==0.0){return array_fill(0,count($values),0.0);}return array_map(static fn($value)=>($value-$minimum)/$span,$values);}
    public static function z_score_normalize($samples){$values=self::values($samples,'samples',2);$mean=self::mean($values);$sd=self::sd($values);if($sd==0.0){return array_fill(0,count($values),0.0);}return array_map(static fn($value)=>($value-$mean)/$sd,$values);}
    public static function moving_average($samples,$window_size){$values=self::values($samples,'samples');$window=(int)self::positive($window_size,'windowSize');if($window>count($values)){throw new InvalidArgumentException('windowSize cannot exceed the sample count.');}$result=array();for($i=0;$i<count($values);$i++){$slice=array_slice($values,max(0,$i-$window+1),min($window,$i+1));$result[]=self::mean($slice);}return $result;}
    public static function linear_resample($samples,$source_rate_hz,$target_rate_hz){$values=self::values($samples,'samples',2);$source=self::positive($source_rate_hz,'sourceRateHz');$target=self::positive($target_rate_hz,'targetRateHz');$duration=(count($values)-1)/$source;$count=max(2,(int)round($duration*$target)+1);$result=array();for($i=0;$i<$count;$i++){$position=($i/$target)*$source;$left=min(count($values)-1,(int)floor($position));$right=min(count($values)-1,$left+1);$fraction=$position-$left;$result[]=$values[$left]+($values[$right]-$values[$left])*$fraction;}return $result;}
    public static function pearson_correlation($reference,$comparison){list($a,$b)=self::paired($reference,$comparison);$am=self::mean($a);$bm=self::mean($b);$numerator=0.0;$as=0.0;$bs=0.0;foreach($a as $i=>$value){$ad=$value-$am;$bd=$b[$i]-$bm;$numerator+=$ad*$bd;$as+=$ad*$ad;$bs+=$bd*$bd;}$denominator=sqrt($as*$bs);if($denominator==0.0){throw new InvalidArgumentException('Correlation requires non-constant arrays.');}return $numerator/$denominator;}
    public static function mean_absolute_error($reference,$comparison){list($a,$b)=self::paired($reference,$comparison);$errors=array();foreach($a as $i=>$value){$errors[]=abs($value-$b[$i]);}return self::mean($errors);}
    public static function root_mean_square_error($reference,$comparison){list($a,$b)=self::paired($reference,$comparison);$errors=array();foreach($a as $i=>$value){$errors[]=($value-$b[$i])**2;}return sqrt(self::mean($errors));}
    public static function normalized_rmse($reference,$comparison){list($a,$b)=self::paired($reference,$comparison);$span=max($a)-min($a);if($span==0.0){throw new InvalidArgumentException('Normalized RMSE requires a non-zero reference range.');}return self::root_mean_square_error($a,$b)/$span;}
    public static function shift_series($reference,$comparison,$lag_samples){list($a,$b)=self::paired($reference,$comparison);$lag=(int)self::finite($lag_samples,'lagSamples');if(abs($lag)>=count($a)-1){throw new InvalidArgumentException('Absolute lag must leave at least two overlapping samples.');}if($lag>0){$aa=array_slice($a,$lag);$bb=array_slice($b,0,-$lag);}elseif($lag<0){$aa=array_slice($a,0,$lag);$bb=array_slice($b,-$lag);}else{$aa=$a;$bb=$b;}return array('lagSamples'=>$lag,'reference'=>array_values($aa),'comparison'=>array_values($bb),'overlapCount'=>count($aa));}
    public static function best_lag_correlation($reference,$comparison,$max_lag_samples){list($a,$b)=self::paired($reference,$comparison);$maximum=min(abs((int)self::finite($max_lag_samples,'maxLagSamples')),count($a)-2);$scan=array();$best=null;for($lag=-$maximum;$lag<=$maximum;$lag++){$aligned=self::shift_series($a,$b,$lag);try{$correlation=self::pearson_correlation($aligned['reference'],$aligned['comparison']);}catch(Throwable $error){$correlation=0.0;}$item=array('lagSamples'=>$lag,'correlation'=>$correlation,'overlapCount'=>$aligned['overlapCount']);$scan[]=$item;if($best===null||abs($correlation)>abs($best['correlation'])||(abs($correlation)==abs($best['correlation'])&&abs($lag)<abs($best['lagSamples']))){$best=$item;}}return array('bestLagSamples'=>$best['lagSamples'],'bestCorrelation'=>$best['correlation'],'overlapCount'=>$best['overlapCount'],'scan'=>$scan);}
    public static function event_rate($event_count,$duration_seconds){return self::finite($event_count,'eventCount')*60/self::positive($duration_seconds,'durationSeconds');}
    public static function interval_summary($intervals){if(!is_array($intervals)||count($intervals)===0){throw new InvalidArgumentException('intervals must contain at least one interval.');}$durations=array();$starts=array();$ends=array();foreach($intervals as $index=>$interval){if(!is_array($interval)){throw new InvalidArgumentException('intervals['.$index.'] must be an object.');}$start=self::finite($interval['startSeconds']??null,'intervals['.$index.'].startSeconds');$end=self::finite($interval['endSeconds']??null,'intervals['.$index.'].endSeconds');if($end<$start){throw new InvalidArgumentException('intervals['.$index.'] ends before it starts.');}$starts[]=$start;$ends[]=$end;$durations[]=$end-$start;}$span=max($ends)-min($starts);$total=array_sum($durations);return array('intervalCount'=>count($intervals),'totalDurationSeconds'=>$total,'meanDurationSeconds'=>self::mean($durations),'minimumDurationSeconds'=>min($durations),'maximumDurationSeconds'=>max($durations),'coveredSpanSeconds'=>$span,'burdenPercent'=>$span>0?$total/$span*100:0.0);}
    public static function annotation_coverage($annotations,$window_start_seconds,$window_end_seconds){if(!is_array($annotations)){throw new InvalidArgumentException('annotations must be an array.');}$start=self::finite($window_start_seconds,'windowStartSeconds');$end=self::finite($window_end_seconds,'windowEndSeconds');if($end<=$start){throw new InvalidArgumentException('windowEndSeconds must exceed windowStartSeconds.');}$clipped=array();$type_counts=array();foreach($annotations as $index=>$annotation){if(!is_array($annotation)){throw new InvalidArgumentException('annotations['.$index.'] must be an object.');}$as=self::finite($annotation['startSeconds']??null,'annotations['.$index.'].startSeconds');$ae=self::finite($annotation['endSeconds']??$as,'annotations['.$index.'].endSeconds');if($ae<$as){throw new InvalidArgumentException('annotations['.$index.'] ends before it starts.');}$cs=max($start,$as);$ce=min($end,$ae);if($ce>$cs){$clipped[]=array($cs,$ce);}$type=(string)($annotation['type']??'note');$type_counts[$type]=($type_counts[$type]??0)+1;}usort($clipped,static fn($a,$b)=>$a[0]<=>$b[0]);$merged=array();foreach($clipped as $interval){if(count($merged)===0||$interval[0]>$merged[count($merged)-1][1]){$merged[]=array($interval[0],$interval[1]);}else{$last=count($merged)-1;$merged[$last][1]=max($merged[$last][1],$interval[1]);}}$covered=0.0;$records=array();foreach($merged as $interval){$covered+=$interval[1]-$interval[0];$records[]=array('startSeconds'=>$interval[0],'endSeconds'=>$interval[1]);}return array('annotationCount'=>count($annotations),'coveredSeconds'=>$covered,'coveragePercent'=>$covered/($end-$start)*100,'typeCounts'=>$type_counts,'mergedIntervals'=>$records);}
    public static function common_time_window($run_a,$run_b){if(!is_array($run_a)||!is_array($run_b)){throw new InvalidArgumentException('runA and runB must be objects.');}$as=self::finite($run_a['startSeconds']??0,'runA.startSeconds');$bs=self::finite($run_b['startSeconds']??0,'runB.startSeconds');$ad=self::positive($run_a['durationSeconds']??null,'runA.durationSeconds');$bd=self::positive($run_b['durationSeconds']??null,'runB.durationSeconds');$start=max($as,$bs);$end=min($as+$ad,$bs+$bd);return array('startSeconds'=>$start,'endSeconds'=>$end,'durationSeconds'=>max(0.0,$end-$start),'overlap'=>$end>$start);}
    public static function compare_runs($reference,$comparison,$sample_rate_hz=1){list($a,$b)=self::paired($reference,$comparison);return array('sampleCount'=>count($a),'sampleRateHz'=>self::positive($sample_rate_hz,'sampleRateHz'),'correlation'=>self::pearson_correlation($a,$b),'meanAbsoluteError'=>self::mean_absolute_error($a,$b),'rootMeanSquareError'=>self::root_mean_square_error($a,$b),'normalizedRootMeanSquareError'=>self::normalized_rmse($a,$b),'referenceFeatures'=>self::descriptive_features($a,$sample_rate_hz),'comparisonFeatures'=>self::descriptive_features($b,$sample_rate_hz));}
    public static function execute($method_id,$inputs){$i=is_array($inputs)?$inputs:array();switch($method_id){case'descriptive-features':$value=self::descriptive_features($i['samples']??null,$i['sampleRateHz']??1);break;case'min-max-normalize':$value=self::min_max_normalize($i['samples']??null);break;case'z-score-normalize':$value=self::z_score_normalize($i['samples']??null);break;case'moving-average':$value=self::moving_average($i['samples']??null,$i['windowSize']??null);break;case'linear-resample':$value=self::linear_resample($i['samples']??null,$i['sourceRateHz']??null,$i['targetRateHz']??null);break;case'pearson-correlation':$value=self::pearson_correlation($i['reference']??null,$i['comparison']??null);break;case'mean-absolute-error':$value=self::mean_absolute_error($i['reference']??null,$i['comparison']??null);break;case'root-mean-square-error':$value=self::root_mean_square_error($i['reference']??null,$i['comparison']??null);break;case'normalized-rmse':$value=self::normalized_rmse($i['reference']??null,$i['comparison']??null);break;case'shift-series':$value=self::shift_series($i['reference']??null,$i['comparison']??null,$i['lagSamples']??null);break;case'best-lag-correlation':$value=self::best_lag_correlation($i['reference']??null,$i['comparison']??null,$i['maxLagSamples']??null);break;case'event-rate':$value=self::event_rate($i['eventCount']??null,$i['durationSeconds']??null);break;case'interval-summary':$value=self::interval_summary($i['intervals']??null);break;case'annotation-coverage':$value=self::annotation_coverage($i['annotations']??null,$i['windowStartSeconds']??null,$i['windowEndSeconds']??null);break;case'common-time-window':$value=self::common_time_window($i['runA']??null,$i['runB']??null);break;case'compare-runs':$value=self::compare_runs($i['reference']??null,$i['comparison']??null,$i['sampleRateHz']??1);break;default:throw new InvalidArgumentException('Unknown visualization analysis method: '.$method_id);}return array('schema'=>'sc-lab-biosignal-visualization-result/1.0','version'=>self::VERSION,'methodId'=>$method_id,'inputs'=>$inputs,'value'=>$value);}
    public static function health_payload(){ $c=self::contract();$ready=(($c['version']??null)===self::VERSION&&count($c['modes']??array())===8&&count($c['analysisMethods']??array())===16&&count($c['benchmarks']??array())===16&&count($c['annotationTypes']??array())===6);return array('ok'=>$ready,'status'=>$ready?'ready':'contract-incomplete','release'=>self::VERSION,'modeCount'=>count($c['modes']??array()),'analysisMethodCount'=>count($c['analysisMethods']??array()),'benchmarkCount'=>count($c['benchmarks']??array()),'annotationTypeCount'=>count($c['annotationTypes']??array()),'preservedEngine'=>$c['preservedEngine']??array(),'productionLayer'=>$c['productionLayer']??array());}
    public static function register_routes(){register_rest_route(self::NAMESPACE,'/compute/biomedical/biosignals/visualization/methods',array('methods'=>'GET','callback'=>array(__CLASS__,'methods_response'),'permission_callback'=>'__return_true'));register_rest_route(self::NAMESPACE,'/compute/biomedical/biosignals/visualization/health',array('methods'=>'GET','callback'=>array(__CLASS__,'health_response'),'permission_callback'=>'__return_true'));register_rest_route(self::NAMESPACE,'/compute/biomedical/biosignals/visualization/analyze',array('methods'=>'POST','callback'=>array(__CLASS__,'analyze_response'),'permission_callback'=>'__return_true'));register_rest_route(self::NAMESPACE,'/compute/biomedical/biosignals/visualization/compare',array('methods'=>'POST','callback'=>array(__CLASS__,'compare_response'),'permission_callback'=>'__return_true'));register_rest_route(self::NAMESPACE,'/compute/biomedical/biosignals/visualization/annotations',array('methods'=>'POST','callback'=>array(__CLASS__,'annotations_response'),'permission_callback'=>'__return_true'));}
    public static function methods_response(){return rest_ensure_response(self::contract());} public static function health_response(){return rest_ensure_response(self::health_payload());}
    public static function analyze_response($request){try{$p=$request->get_json_params();return rest_ensure_response(self::execute((string)($p['methodId']??''),$p['inputs']??array()));}catch(Throwable $e){return new WP_Error('sc_lab_v0232_analysis_error',$e->getMessage(),array('status'=>422));}}
    public static function compare_response($request){try{$p=$request->get_json_params();return rest_ensure_response(array('schema'=>'sc-lab-biosignal-comparison/1.0','version'=>self::VERSION,'comparison'=>self::compare_runs($p['reference']??null,$p['comparison']??null,$p['sampleRateHz']??1),'lag'=>self::best_lag_correlation($p['reference']??null,$p['comparison']??null,$p['maxLagSamples']??10)));}catch(Throwable $e){return new WP_Error('sc_lab_v0232_compare_error',$e->getMessage(),array('status'=>422));}}
    public static function annotations_response($request){try{$p=$request->get_json_params();return rest_ensure_response(self::annotation_coverage($p['annotations']??array(),$p['windowStartSeconds']??null,$p['windowEndSeconds']??null));}catch(Throwable $e){return new WP_Error('sc_lab_v0232_annotation_error',$e->getMessage(),array('status'=>422));}}
}
SC_Lab_Biosignal_Visualization_REST_V0232::boot();
