<?php
/** Sustainable Catalyst Lab v0.163.0 — Institutional Research Governance & Review Federation. */
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Institutional_Research_Governance_Review_Federation_V01630 {
 const VERSION='0.163.0'; private static $initialized=false;
 public static function init(){if(self::$initialized)return;self::$initialized=true;add_action('wp_enqueue_scripts',array(__CLASS__,'enqueue'),PHP_INT_MAX);add_action('wp_print_footer_scripts',array(__CLASS__,'enqueue'),PHP_INT_MAX);add_action('rest_api_init',array(__CLASS__,'routes'));}
 private static function is_lab_request(){if(is_admin())return false;global $post;if($post instanceof WP_Post&&has_shortcode((string)$post->post_content,'sc_lab_app'))return true;if(function_exists('is_page')&&is_page('lab'))return true;$path=isset($_SERVER['REQUEST_URI'])?(string)parse_url((string)$_SERVER['REQUEST_URI'],PHP_URL_PATH):'';return(bool)preg_match('~/(?:lab)/?$~',$path);}
 private static function asset_token($r){$p=SC_LAB_DIR.ltrim((string)$r,'/');return self::VERSION.'.'.(is_file($p)?substr(hash_file('sha256',$p),0,16):'missing');}
 public static function enqueue(){if(!self::is_lab_request())return;$css='assets/css/sc-lab-institutional-governance-review-federation-v01630.css';$js='assets/js/sc-lab-institutional-governance-review-federation-v01630.js';wp_enqueue_style('sc-lab-institutional-governance-v01630',SC_LAB_URL.$css,array('sc-lab-cross-project-resource-planning-v01620'),self::asset_token($css));wp_enqueue_script('sc-lab-institutional-governance-v01630',SC_LAB_URL.$js,array('sc-lab-cross-project-resource-planning-v01620','sc-lab-canonical-repair-v015701'),self::asset_token($js),true);wp_localize_script('sc-lab-institutional-governance-v01630','SCLabInstitutionalGovernanceV01630',array('version'=>self::VERSION,'baseUrl'=>esc_url_raw(rest_url('sc-lab/v1/workspace/institutional-governance/v01630')),'defaultInstitutionId'=>is_user_logged_in()?'institution:wp-user-'.get_current_user_id():'','nonce'=>wp_create_nonce('wp_rest')));}
 public static function operations_permission(){return is_user_logged_in();}
 private static function settings(){return wp_parse_args((array)get_option('sc_lab_settings',array()),SC_Lab_Admin::defaults());}
 private static function clean_id($v){return substr(preg_replace('/[^A-Za-z0-9._:-]/','',(string)$v),0,180);}
 private static function clean_tree($v,$depth=0,&$nodes=0){$nodes++;if($nodes>30000||$depth>24)return null;if(is_null($v)||is_bool($v)||is_int($v)||is_float($v))return $v;if(is_string($v))return substr(wp_check_invalid_utf8($v,true),0,150000);if(!is_array($v))return null;$out=array();$count=0;foreach($v as $k=>$x){if(++$count>10000)break;$key=is_int($k)?$k:substr(preg_replace('/[^A-Za-z0-9._:-]/','',(string)$k),0,128);if($key===''&&!is_int($k))continue;$out[$key]=self::clean_tree($x,$depth+1,$nodes);}return $out;}
 private static function body(WP_REST_Request $r){$b=$r->get_json_params();$n=0;return self::clean_tree(is_array($b)?$b:array(),0,$n);}
 private static function proxy($path,$method='GET',$payload=null,$limit=8388608){$s=self::settings();if(empty($s['enable_remote_compute'])||empty($s['compute_backend_url']))return new WP_Error('compute_disabled','The Python Compute Core is not enabled or configured.',array('status'=>503));if(!class_exists('SC_Lab_Python_Compute_Core_V0261'))return new WP_Error('compute_proxy_unavailable','The Python Compute Core signing bridge is unavailable.',array('status'=>503));$body=null===$payload?'':wp_json_encode($payload);$args=array('method'=>$method,'timeout'=>max(5,min(120,absint($s['compute_timeout_seconds']))),'redirection'=>2,'sslverify'=>!empty($s['compute_verify_ssl']),'headers'=>SC_Lab_Python_Compute_Core_V0261::signed_headers($path,$method,$body,$s),'limit_response_size'=>max(262144,min(16777216,absint($limit))));if(null!==$payload)$args['body']=$body;$response=wp_safe_remote_request(untrailingslashit($s['compute_backend_url']).$path,$args);if(is_wp_error($response))return new WP_Error('institutional_governance_backend_unavailable',$response->get_error_message(),array('status'=>502));$status=wp_remote_retrieve_response_code($response);$decoded=json_decode(wp_remote_retrieve_body($response),true);if(!is_array($decoded)){$decoded=array('detail'=>'The institutional-governance backend returned invalid JSON.');$status=502;}return new WP_REST_Response($decoded,$status);}
 private static function base(){return '/v1/institutional-research-governance-review-federation/v01630';}
 private static function inst_path(WP_REST_Request $r,$suffix=''){return self::base().'/institutions/'.rawurlencode(self::clean_id($r['id'])).$suffix;}
 public static function routes(){register_rest_route('sc-lab/v1','/workspace/institutional-governance/v01630/health',array('methods'=>'GET','callback'=>function(){return self::proxy(self::base().'/health');},'permission_callback'=>array(__CLASS__,'operations_permission')));register_rest_route('sc-lab/v1','/workspace/institutional-governance/v01630/institutions',array(array('methods'=>'GET','callback'=>function($r){return self::proxy(self::base().'/institutions?limit='.absint($r->get_param('limit')?:1000));},'permission_callback'=>array(__CLASS__,'operations_permission')),array('methods'=>'POST','callback'=>function($r){return self::proxy(self::base().'/institutions','POST',self::body($r));},'permission_callback'=>array(__CLASS__,'operations_permission'))));
 foreach(array('bodies','federation-links','cases','command-center','manifest','timeline') as $name){register_rest_route('sc-lab/v1','/workspace/institutional-governance/v01630/institutions/(?P<id>[A-Za-z0-9._:-]+)/'.$name,array('methods'=>'GET','callback'=>function($r)use($name){return self::proxy(self::inst_path($r,'/'.$name));},'permission_callback'=>array(__CLASS__,'operations_permission')));} 
 register_rest_route('sc-lab/v1','/workspace/institutional-governance/v01630/institutions/(?P<id>[A-Za-z0-9._:-]+)/bodies',array('methods'=>'POST','callback'=>function($r){return self::proxy(self::inst_path($r,'/bodies'),'POST',self::body($r));},'permission_callback'=>array(__CLASS__,'operations_permission')));
 register_rest_route('sc-lab/v1','/workspace/institutional-governance/v01630/institutions/(?P<id>[A-Za-z0-9._:-]+)/cases',array('methods'=>'POST','callback'=>function($r){return self::proxy(self::inst_path($r,'/cases'),'POST',self::body($r));},'permission_callback'=>array(__CLASS__,'operations_permission')));
 register_rest_route('sc-lab/v1','/workspace/institutional-governance/v01630/institutions/(?P<id>[A-Za-z0-9._:-]+)/snapshot',array('methods'=>'POST','callback'=>function($r){return self::proxy(self::inst_path($r,'/snapshot'),'POST',self::body($r));},'permission_callback'=>array(__CLASS__,'operations_permission')));
 register_rest_route('sc-lab/v1','/workspace/institutional-governance/v01630/federation-links',array('methods'=>'POST','callback'=>function($r){return self::proxy(self::base().'/federation-links','POST',self::body($r));},'permission_callback'=>array(__CLASS__,'operations_permission')));
 foreach(array('assignments','decisions','attestations','transition') as $name){register_rest_route('sc-lab/v1','/workspace/institutional-governance/v01630/cases/(?P<id>[A-Za-z0-9._:-]+)/'.$name,array('methods'=>'POST','callback'=>function($r)use($name){return self::proxy(self::base().'/cases/'.rawurlencode(self::clean_id($r['id'])).'/'.$name,'POST',self::body($r));},'permission_callback'=>array(__CLASS__,'operations_permission')));} }
}
