<?php
/** Sustainable Catalyst Lab v0.38.2 Public API, Webhooks, Embeds, and Research SDK. */
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Public_Research_Integrations_V0382 {
    const VERSION='0.38.2'; private static $initialized=false;
    public static function init(){ if(self::$initialized)return; self::$initialized=true; add_action('rest_api_init',array(__CLASS__,'routes')); add_filter('sc_lab_module_aliases_v02631',array(__CLASS__,'aliases')); add_filter('sc_lab_panel_aliases_v02631',array(__CLASS__,'aliases')); add_shortcode('sc_lab_public_research_api',array(__CLASS__,'shortcode')); add_shortcode('sc_lab_research_integration_studio',array(__CLASS__,'shortcode')); }
    public static function aliases($aliases){$aliases=is_array($aliases)?$aliases:array();foreach(array('public-research-integrations','public-research-api','research-integration-studio','webhook-studio','research-sdk') as $alias){$aliases[$alias]='public-research-integrations';}return $aliases;}
    public static function shortcode(){return do_shortcode('[sc_lab_app module="public-research-integrations"]');}
    public static function routes(){register_rest_route('sc-lab/v1','/public-research-integrations/v0382/health',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'health'),'permission_callback'=>'__return_true'));register_rest_route('sc-lab/v1','/public-research-integrations/v0382/catalog',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'catalog'),'permission_callback'=>'__return_true'));}
    private static function state($relative){$path=SC_LAB_DIR.$relative;return array('exists'=>is_file($path),'sha256'=>is_file($path)?hash_file('sha256',$path):null);}
    public static function catalog(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'apiVersion'=>'v1','openApi'=>'/openapi.json','pythonSdk'=>'sdk/python','typescriptSdk'=>'sdk/typescript','webhookSigning'=>'HMAC-SHA256','signedEmbeds'=>true));}
    public static function health(){ $required=array('backend/app/public_research_integrations.py','backend/tests/test_public_research_integrations_v0382.py','assets/js/modules/public-research-integrations.js','assets/css/sc-lab-public-research-integrations-v0382.css','contracts/public-research-integration-policy-v0382.json','contracts/webhook-subscription-v0382.schema.json','contracts/webhook-delivery-v0382.schema.json','contracts/research-webhook-event-v0382.schema.json','contracts/research-embed-manifest-v0382.schema.json','contracts/research-sdk-manifest-v0382.schema.json','sdk/python/sustainable_catalyst_lab/client.py','sdk/typescript/src/index.ts','sdk/embed/sc-lab-research-embed.js');$files=array();$ok=true;foreach($required as $r){$files[$r]=self::state($r);if(empty($files[$r]['exists']))$ok=false;}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'ready':'incomplete','version'=>self::VERSION,'release'=>defined('SC_LAB_VERSION')?SC_LAB_VERSION:null,'apiVersion'=>'v1','scopedIntegrationAuth'=>true,'ssrfProtectedWebhooks'=>true,'signedExpiringEmbeds'=>true,'pythonSdk'=>true,'typescriptSdk'=>true,'files'=>$files,'time'=>gmdate('c'))); }
}
SC_Lab_Public_Research_Integrations_V0382::init();
