<?php
/** Sustainable Catalyst Lab v0.28.2 Reproducible Computational Runs. */
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Reproducible_Runs_V0282 {
    const VERSION='0.28.2'; private static $initialized=false;
    public static function init(){if(self::$initialized){return;}self::$initialized=true;add_action('rest_api_init',array(__CLASS__,'routes'));add_filter('sc_lab_module_aliases_v02631',array(__CLASS__,'aliases'));}
    public static function aliases($aliases){$aliases=is_array($aliases)?$aliases:array();foreach(array('reproducible-runs','reproducibility','computational-runs','run-manifests') as $alias){$aliases[$alias]='reproducible-runs';}return $aliases;}
    public static function routes(){register_rest_route('sc-lab/v1','/reproducibility/v0282/health',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'health'),'permission_callback'=>'__return_true'));register_rest_route('sc-lab/v1','/reproducibility/v0282/schema',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'schema'),'permission_callback'=>'__return_true'));}
    private static function file_state($rel){$p=SC_LAB_DIR.$rel;return array('exists'=>is_file($p),'sha256'=>is_file($p)?hash_file('sha256',$p):null);}
    public static function schema(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'schema'=>'sc-lab-reproducible-run/0.28.2','bundleSchema'=>'sc-lab-reproducibility-bundle/0.28.2','comparisonSchema'=>'sc-lab-run-comparison/0.28.2','projectWorkspace'=>'0.28.0','datasetRegistry'=>'0.28.1','storage'=>'browser-local-project-records','serverBackedRegistry'=>false,'capabilities'=>array('frozenRequests'=>true,'frozenResults'=>true,'environmentFingerprints'=>true,'checksums'=>true,'rerunCompare'=>true,'failureHistory'=>true,'portableBundles'=>true)));}
    public static function health(){ $required=array('assets/js/modules/reproducible-runs-v0282.js','assets/css/sc-lab-reproducible-runs-v0282.css','contracts/reproducible-run-v0282.schema.json','contracts/reproducibility-bundle-v0282.schema.json','contracts/run-comparison-v0282.schema.json','contracts/reproducibility-policy-v0282.json','includes/class-sc-lab-reproducible-runs-v0282.php');$files=array();foreach($required as $rel){$files[$rel]=self::file_state($rel);} $ok=!in_array(false,array_map(function($row){return !empty($row['exists']);},$files),true);return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'ready':'incomplete','version'=>self::VERSION,'release'=>defined('SC_LAB_VERSION')?SC_LAB_VERSION:null,'architecture'=>'browser-project-run-registry-with-python-verification','serverBackedRegistry'=>false,'pythonVerification'=>true,'files'=>$files,'time'=>gmdate('c')));}
}
