<?php
/** Sustainable Catalyst Lab v0.82.0 — Uncertainty, Ensemble & Distribution Visualization. */
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Uncertainty_Ensemble_Distribution_V0820 {
 const VERSION='0.82.0'; const ENGINE_VERSION='2.9.0'; private static $initialized=false;
 public static function init(){if(self::$initialized){return;}self::$initialized=true;add_action('rest_api_init',array(__CLASS__,'routes'));}
 public static function routes(){register_rest_route('sc-lab/v1','/visualization/v0820/health',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'health'),'permission_callback'=>'__return_true'));register_rest_route('sc-lab/v1','/visualization/v0820/schema',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'schema'),'permission_callback'=>'__return_true'));}
 private static function file_state($r){$p=SC_LAB_DIR.ltrim((string)$r,'/');return array('exists'=>is_file($p),'sha256'=>is_file($p)?hash_file('sha256',$p):null);}
 public static function schema(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'rendererOverlay'=>'uncertainty-distribution','uncertaintySchema'=>'sc-lab-uncertainty-series/0.82.0','distributionSchema'=>'sc-lab-empirical-distribution/0.82.0','ensembleSchema'=>'sc-lab-ensemble-visualization/0.82.0','layerSchema'=>'sc-lab-uncertainty-layer/0.82.0','figureSchema'=>'sc-lab-uncertainty-figure/0.82.0','workspaceSchema'=>'sc-lab-figure-workspace/0.82.0','intervalSemantics'=>array('confidence','credible','prediction','bootstrap','custom'),'distributionSemantics'=>array('observed','bootstrap','posterior','ensemble','residual','custom'),'capabilities'=>array('intervalBands'=>true,'confidenceIntervals'=>true,'credibleIntervals'=>true,'predictionIntervals'=>true,'quantileRibbons'=>true,'empiricalHistogram'=>true,'ecdf'=>true,'boxSummary'=>true,'posteriorSamples'=>true,'ensembleTrajectories'=>true,'ensembleEnvelopes'=>true,'uncertaintyProvenance'=>true,'baseFigurePreservation'=>true),'boundaries'=>array('automaticUncertaintyInference'=>false,'automaticDistributionAssumption'=>false,'automaticParametricFit'=>false,'automaticKDE'=>false,'automaticIntervalConversion'=>false,'automaticEnsembleAlignment'=>false,'temporalInterpolation'=>false,'spatialInterpolation'=>false,'syntheticSamples'=>false,'forecasting'=>false,'arbitraryCode'=>false)));}
 public static function health(){ $required=array('backend/app/uncertainty_ensemble_distribution_v0820.py','backend/tests/test_uncertainty_ensemble_distribution_v0820.py','assets/js/modules/uncertainty-ensemble-distribution-v0820.js','assets/js/modules/graph-studio-v0820.js','assets/css/sc-lab-uncertainty-v0820.css','contracts/uncertainty-series-v0820.schema.json','contracts/empirical-distribution-v0820.schema.json','contracts/ensemble-visualization-v0820.schema.json','contracts/uncertainty-layer-v0820.schema.json','contracts/uncertainty-figure-v0820.schema.json','contracts/figure-workspace-v0820.schema.json');$files=array();$ok=true;foreach($required as $r){$files[$r]=self::file_state($r);if(empty($files[$r]['exists'])){$ok=false;}} return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'uncertainty-ensemble-distribution-ready':'incomplete','version'=>self::VERSION,'release'=>defined('SC_LAB_RELEASE_VERSION')?SC_LAB_RELEASE_VERSION:null,'platformVersion'=>defined('SC_LAB_VERSION')?SC_LAB_VERSION:null,'engineVersion'=>self::ENGINE_VERSION,'rendererOverlay'=>'uncertainty-distribution','intervalBands'=>true,'confidenceIntervals'=>true,'credibleIntervals'=>true,'predictionIntervals'=>true,'quantileRibbons'=>true,'empiricalHistogram'=>true,'ecdf'=>true,'boxSummary'=>true,'posteriorSamples'=>true,'ensembleTrajectories'=>true,'ensembleEnvelopes'=>true,'uncertaintyProvenance'=>true,'baseFigurePreservation'=>true,'v0810MarkupCompatibility'=>true,'v0800SpatialCompatibility'=>true,'v0790LinkedViewsCompatibility'=>true,'v0780TimeParameterCompatibility'=>true,'v0770SceneCompatibility'=>true,'v0760AdaptiveCompatibility'=>true,'v0750DataBindingCompatibility'=>true,'automaticUncertaintyInference'=>false,'automaticDistributionAssumption'=>false,'automaticParametricFit'=>false,'automaticKDE'=>false,'automaticIntervalConversion'=>false,'automaticEnsembleAlignment'=>false,'temporalInterpolation'=>false,'spatialInterpolation'=>false,'syntheticSamples'=>false,'forecasting'=>false,'arbitraryCode'=>false,'files'=>$files));}
}
