<?php
/** Sustainable Catalyst Lab v0.158.0 — Scientific Reproduction & Independent Replication Network. */
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Scientific_Reproduction_Independent_Replication_Network_V01580 {
    const VERSION='0.158.0'; private static $initialized=false;
    public static function init(){ if(self::$initialized)return; self::$initialized=true; add_action('wp_enqueue_scripts',array(__CLASS__,'enqueue'),PHP_INT_MAX); add_action('wp_print_footer_scripts',array(__CLASS__,'enqueue'),PHP_INT_MAX); add_action('rest_api_init',array(__CLASS__,'routes')); }
    private static function is_lab_request(){ if(is_admin())return false; global $post; if($post instanceof WP_Post && has_shortcode((string)$post->post_content,'sc_lab_app'))return true; if(function_exists('is_page')&&is_page('lab'))return true; $path=isset($_SERVER['REQUEST_URI'])?(string)parse_url((string)$_SERVER['REQUEST_URI'],PHP_URL_PATH):''; return (bool)preg_match('~/(?:lab)/?$~',$path); }
    private static function asset_token($relative){$path=SC_LAB_DIR.ltrim((string)$relative,'/');return self::VERSION.'.'.(is_file($path)?substr(hash_file('sha256',$path),0,16):'missing');}
    public static function enqueue(){ if(!self::is_lab_request())return; $css='assets/css/sc-lab-scientific-reproduction-independent-replication-network-v01580.css';$js='assets/js/sc-lab-scientific-reproduction-independent-replication-network-v01580.js'; wp_enqueue_style('sc-lab-replication-network-v01580',SC_LAB_URL.$css,array('sc-lab-cross-study-meta-v01570'),self::asset_token($css)); wp_enqueue_script('sc-lab-replication-network-v01580',SC_LAB_URL.$js,array('sc-lab-cross-study-meta-v01570','sc-lab-canonical-repair-v015701'),self::asset_token($js),true); wp_localize_script('sc-lab-replication-network-v01580','SCLabReplicationNetworkV01580',array('version'=>self::VERSION,'healthUrl'=>esc_url_raw(rest_url('sc-lab/v1/workspace/replication-network/v01580/health')),'nodesUrl'=>esc_url_raw(rest_url('sc-lab/v1/workspace/replication-network/v01580/nodes')),'networksUrl'=>esc_url_raw(rest_url('sc-lab/v1/workspace/replication-network/v01580/networks')),'verifyUrl'=>esc_url_raw(rest_url('sc-lab/v1/workspace/replication-network/v01580/manifests/verify')),'defaultProjectId'=>is_user_logged_in()?'project:wp-user-'.get_current_user_id():'','nonce'=>wp_create_nonce('wp_rest'))); }
    public static function operations_permission(){return is_user_logged_in();}
    private static function settings(){return wp_parse_args((array)get_option('sc_lab_settings',array()),SC_Lab_Admin::defaults());}
    private static function clean_id($v){return substr(preg_replace('/[^A-Za-z0-9._:-]/','',(string)$v),0,180);}
    private static function clean_tree($v,$depth=0,&$nodes=0){$nodes++;if($nodes>30000||$depth>24)return null;if(is_null($v)||is_bool($v)||is_int($v)||is_float($v))return $v;if(is_string($v))return substr(wp_check_invalid_utf8($v,true),0,150000);if(!is_array($v))return null;$out=array();$count=0;foreach($v as $k=>$x){if(++$count>10000)break;$key=is_int($k)?$k:substr(preg_replace('/[^A-Za-z0-9._:-]/','',(string)$k),0,128);if($key===''&&!is_int($k))continue;$out[$key]=self::clean_tree($x,$depth+1,$nodes);}return $out;}
    private static function body(WP_REST_Request $r){$b=$r->get_json_params();$n=0;return self::clean_tree(is_array($b)?$b:array(),0,$n);}
    private static function proxy($path,$method='GET',$payload=null,$limit=8388608){$s=self::settings();if(empty($s['enable_remote_compute'])||empty($s['compute_backend_url']))return new WP_Error('compute_disabled','The Python Compute Core is not enabled or configured.',array('status'=>503));if(!class_exists('SC_Lab_Python_Compute_Core_V0261'))return new WP_Error('compute_proxy_unavailable','The Python Compute Core signing bridge is unavailable.',array('status'=>503));$body=null===$payload?'':wp_json_encode($payload);$url=untrailingslashit($s['compute_backend_url']).$path;$args=array('method'=>$method,'timeout'=>max(5,min(120,absint($s['compute_timeout_seconds']))),'redirection'=>2,'sslverify'=>!empty($s['compute_verify_ssl']),'headers'=>SC_Lab_Python_Compute_Core_V0261::signed_headers($path,$method,$body,$s),'limit_response_size'=>max(262144,min(16777216,absint($limit))));if(null!==$payload)$args['body']=$body;$response=wp_safe_remote_request($url,$args);if(is_wp_error($response))return new WP_Error('replication_network_backend_unavailable',$response->get_error_message(),array('status'=>502));$status=wp_remote_retrieve_response_code($response);$decoded=json_decode(wp_remote_retrieve_body($response),true);if(!is_array($decoded)){$decoded=array('detail'=>'The replication-network backend returned invalid JSON.');$status=502;}return new WP_REST_Response($decoded,$status);}
    private static function pq(WP_REST_Request $r){return '?project_id='.rawurlencode(self::clean_id($r->get_param('project_id'))).'&include_archived='.($r->get_param('include_archived')?'true':'false').'&limit='.max(1,min(1000,absint($r->get_param('limit')?:100)));}
    public static function routes(){
      register_rest_route('sc-lab/v1','/workspace/replication-network/v01580/health',array('methods'=>'GET','callback'=>array(__CLASS__,'health'),'permission_callback'=>'__return_true'));
      register_rest_route('sc-lab/v1','/workspace/replication-network/v01580/nodes',array(array('methods'=>'GET','callback'=>array(__CLASS__,'nodes'),'permission_callback'=>array(__CLASS__,'operations_permission')),array('methods'=>'POST','callback'=>array(__CLASS__,'node_create'),'permission_callback'=>array(__CLASS__,'operations_permission'))));
      register_rest_route('sc-lab/v1','/workspace/replication-network/v01580/networks',array(array('methods'=>'GET','callback'=>array(__CLASS__,'networks'),'permission_callback'=>array(__CLASS__,'operations_permission')),array('methods'=>'POST','callback'=>array(__CLASS__,'network_create'),'permission_callback'=>array(__CLASS__,'operations_permission'))));
      foreach(array('view'=>'GET','coverage'=>'GET','manifest'=>'GET','timeline'=>'GET','freeze'=>'POST','archive'=>'POST') as $suffix=>$method)register_rest_route('sc-lab/v1','/workspace/replication-network/v01580/networks/(?P<id>[A-Za-z0-9._:-]{1,180})/'.$suffix,array('methods'=>$method,'callback'=>array(__CLASS__,$suffix),'permission_callback'=>array(__CLASS__,'operations_permission')));
      register_rest_route('sc-lab/v1','/workspace/replication-network/v01580/networks/(?P<id>[A-Za-z0-9._:-]{1,180})/nodes',array('methods'=>'POST','callback'=>array(__CLASS__,'network_node'),'permission_callback'=>array(__CLASS__,'operations_permission')));
      register_rest_route('sc-lab/v1','/workspace/replication-network/v01580/networks/(?P<id>[A-Za-z0-9._:-]{1,180})/plans',array('methods'=>'POST','callback'=>array(__CLASS__,'plan_create'),'permission_callback'=>array(__CLASS__,'operations_permission')));
      register_rest_route('sc-lab/v1','/workspace/replication-network/v01580/networks/(?P<id>[A-Za-z0-9._:-]{1,180})/reviews',array('methods'=>'POST','callback'=>array(__CLASS__,'review'),'permission_callback'=>array(__CLASS__,'operations_permission')));
      register_rest_route('sc-lab/v1','/workspace/replication-network/v01580/plans/(?P<plan>[A-Za-z0-9._:-]{1,180})/handoff',array('methods'=>'GET','callback'=>array(__CLASS__,'handoff'),'permission_callback'=>array(__CLASS__,'operations_permission')));
      register_rest_route('sc-lab/v1','/workspace/replication-network/v01580/plans/(?P<plan>[A-Za-z0-9._:-]{1,180})/results',array('methods'=>'POST','callback'=>array(__CLASS__,'result'),'permission_callback'=>array(__CLASS__,'operations_permission')));
      register_rest_route('sc-lab/v1','/workspace/replication-network/v01580/manifests/verify',array('methods'=>'POST','callback'=>array(__CLASS__,'verify_manifest'),'permission_callback'=>array(__CLASS__,'operations_permission')));
    }
    public static function health(){return self::proxy('/v1/scientific-reproduction-independent-replication-network/v01580/health');}
    public static function nodes(WP_REST_Request $r){return self::proxy('/v1/scientific-reproduction-independent-replication-network/v01580/nodes'.self::pq($r));}
    public static function node_create(WP_REST_Request $r){$b=self::body($r);$pid=self::clean_id($b['project_id']??'');unset($b['project_id']);return self::proxy('/v1/scientific-reproduction-independent-replication-network/v01580/projects/'.rawurlencode($pid).'/nodes','POST',$b);}
    public static function networks(WP_REST_Request $r){return self::proxy('/v1/scientific-reproduction-independent-replication-network/v01580/networks'.self::pq($r));}
    public static function network_create(WP_REST_Request $r){$b=self::body($r);$pid=self::clean_id($b['project_id']??'');unset($b['project_id']);return self::proxy('/v1/scientific-reproduction-independent-replication-network/v01580/projects/'.rawurlencode($pid).'/networks','POST',$b);}
    public static function network_node(WP_REST_Request $r){return self::proxy('/v1/scientific-reproduction-independent-replication-network/v01580/networks/'.rawurlencode($r['id']).'/nodes','POST',self::body($r));}
    public static function plan_create(WP_REST_Request $r){return self::proxy('/v1/scientific-reproduction-independent-replication-network/v01580/networks/'.rawurlencode($r['id']).'/plans','POST',self::body($r));}
    public static function review(WP_REST_Request $r){return self::proxy('/v1/scientific-reproduction-independent-replication-network/v01580/networks/'.rawurlencode($r['id']).'/reviews','POST',self::body($r));}
    public static function handoff(WP_REST_Request $r){return self::proxy('/v1/scientific-reproduction-independent-replication-network/v01580/plans/'.rawurlencode($r['plan']).'/handoff');}
    public static function result(WP_REST_Request $r){return self::proxy('/v1/scientific-reproduction-independent-replication-network/v01580/plans/'.rawurlencode($r['plan']).'/results','POST',self::body($r));}
    public static function view(WP_REST_Request $r){return self::proxy('/v1/scientific-reproduction-independent-replication-network/v01580/networks/'.rawurlencode($r['id']).'/view');}
    public static function coverage(WP_REST_Request $r){return self::proxy('/v1/scientific-reproduction-independent-replication-network/v01580/networks/'.rawurlencode($r['id']).'/coverage');}
    public static function manifest(WP_REST_Request $r){return self::proxy('/v1/scientific-reproduction-independent-replication-network/v01580/networks/'.rawurlencode($r['id']).'/manifest');}
    public static function timeline(WP_REST_Request $r){return self::proxy('/v1/scientific-reproduction-independent-replication-network/v01580/networks/'.rawurlencode($r['id']).'/timeline');}
    public static function freeze(WP_REST_Request $r){return self::proxy('/v1/scientific-reproduction-independent-replication-network/v01580/networks/'.rawurlencode($r['id']).'/freeze','POST',array());}
    public static function archive(WP_REST_Request $r){return self::proxy('/v1/scientific-reproduction-independent-replication-network/v01580/networks/'.rawurlencode($r['id']).'/archive','POST',array());}
    public static function verify_manifest(WP_REST_Request $r){return self::proxy('/v1/scientific-reproduction-independent-replication-network/v01580/manifests/verify','POST',self::body($r));}
}
