<?php
/** Sustainable Catalyst Lab v0.83.0 — Provenance-Aware Scientific Figures. */
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Provenance_Aware_Figures_V0830 {
 const VERSION='0.83.0'; const ENGINE_VERSION='2.10.0'; private static $initialized=false;
 public static function init(){if(self::$initialized){return;}self::$initialized=true;add_action('rest_api_init',array(__CLASS__,'routes'));}
 public static function routes(){register_rest_route('sc-lab/v1','/visualization/v0830/health',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'health'),'permission_callback'=>'__return_true'));register_rest_route('sc-lab/v1','/visualization/v0830/schema',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'schema'),'permission_callback'=>'__return_true'));}
 private static function file_state($r){$p=SC_LAB_DIR.ltrim((string)$r,'/');return array('exists'=>is_file($p),'sha256'=>is_file($p)?hash_file('sha256',$p):null);}
 public static function schema(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'rendererOverlay'=>'figure-provenance','provenanceSchema'=>'sc-lab-figure-provenance/0.83.0','figureSchema'=>'sc-lab-provenance-aware-figure/0.83.0','exportSchema'=>'sc-lab-figure-export-manifest/0.83.0','workspaceSchema'=>'sc-lab-figure-workspace/0.83.0','capabilities'=>array('datasetFingerprinting'=>true,'transformationFingerprinting'=>true,'modelFingerprinting'=>true,'rendererProvenance'=>true,'interactionStateFingerprinting'=>true,'annotationLineage'=>true,'uncertaintyLineage'=>true,'exportManifest'=>true,'lineageVerification'=>true,'baseFigurePreservation'=>true),'boundaries'=>array('automaticSourceInference'=>false,'automaticProvenanceRepair'=>false,'silentFingerprintOverride'=>false,'hiddenTransformations'=>false,'unverifiableClaimAsVerified'=>false,'arbitraryCode'=>false)));}
 public static function health(){ $required=array('backend/app/provenance_aware_figures_v0830.py','backend/tests/test_provenance_aware_figures_v0830.py','assets/js/modules/provenance-aware-figures-v0830.js','assets/js/modules/graph-studio-v0830.js','assets/css/sc-lab-provenance-v0830.css','contracts/figure-provenance-v0830.schema.json','contracts/provenance-aware-figure-v0830.schema.json','contracts/figure-export-manifest-v0830.schema.json','contracts/figure-workspace-v0830.schema.json');$files=array();$ok=true;foreach($required as $r){$files[$r]=self::file_state($r);if(empty($files[$r]['exists'])){$ok=false;}}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'provenance-aware-scientific-figures-ready':'incomplete','version'=>self::VERSION,'release'=>defined('SC_LAB_RELEASE_VERSION')?SC_LAB_RELEASE_VERSION:null,'platformVersion'=>defined('SC_LAB_VERSION')?SC_LAB_VERSION:null,'engineVersion'=>self::ENGINE_VERSION,'rendererOverlay'=>'figure-provenance','datasetFingerprinting'=>true,'transformationFingerprinting'=>true,'modelFingerprinting'=>true,'rendererProvenance'=>true,'interactionStateFingerprinting'=>true,'annotationLineage'=>true,'uncertaintyLineage'=>true,'exportManifest'=>true,'lineageVerification'=>true,'baseFigurePreservation'=>true,'v0820UncertaintyCompatibility'=>true,'v0810MarkupCompatibility'=>true,'v0800SpatialCompatibility'=>true,'v0790LinkedViewsCompatibility'=>true,'v0780TimeParameterCompatibility'=>true,'v0770SceneCompatibility'=>true,'v0760AdaptiveCompatibility'=>true,'v0750DataBindingCompatibility'=>true,'automaticSourceInference'=>false,'automaticProvenanceRepair'=>false,'silentFingerprintOverride'=>false,'hiddenTransformations'=>false,'unverifiableClaimAsVerified'=>false,'arbitraryCode'=>false,'files'=>$files));}
}
