<?php
/** Sustainable Catalyst Lab v0.40.1 accessibility, mobile, offline, and interface finalization. */
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Interface_Finalization_V0401 {
    const VERSION='0.40.1'; private static $initialized=false;
    public static function init(){if(self::$initialized){return;}self::$initialized=true;add_action('rest_api_init',array(__CLASS__,'routes'));add_filter('sc_lab_module_aliases_v02631',array(__CLASS__,'aliases'));add_filter('sc_lab_panel_aliases_v02631',array(__CLASS__,'aliases'));add_shortcode('sc_lab_interface_finalization',array(__CLASS__,'shortcode'));add_shortcode('sc_lab_offline_research_workspace',array(__CLASS__,'shortcode'));add_filter('query_vars',array(__CLASS__,'query_vars'));add_action('template_redirect',array(__CLASS__,'serve_worker'));}
    public static function aliases($aliases){$aliases=is_array($aliases)?$aliases:array();foreach(array('interface-finalization','accessible-lab','mobile-lab','offline-research-workspace','offline-project-access','connection-recovery') as $alias){$aliases[$alias]='interface-finalization-v0401';}return $aliases;}
    public static function shortcode(){return do_shortcode('[sc_lab_app module="interface-finalization-v0401"]');}
    public static function query_vars($vars){$vars[]='sc_lab_sw_v0401';return $vars;}
    public static function serve_worker(){if(!get_query_var('sc_lab_sw_v0401') && empty($_GET['sc_lab_sw_v0401'])){return;}nocache_headers();header('Content-Type: application/javascript; charset=UTF-8');header('Service-Worker-Allowed: /');header('X-Content-Type-Options: nosniff');readfile(SC_LAB_DIR.'assets/js/sc-lab-offline-shell-v0401.js');exit;}
    public static function routes(){register_rest_route('sc-lab/v1','/interface-finalization/v0401/health',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'health'),'permission_callback'=>'__return_true'));}
    private static function state($relative){$path=SC_LAB_DIR.$relative;return array('exists'=>is_file($path),'sha256'=>is_file($path)?hash_file('sha256',$path):null);}
    public static function health(){$required=array('backend/app/interface_finalization.py','backend/tests/test_interface_finalization_v0401.py','assets/js/modules/interface-finalization-v0401.js','assets/js/sc-lab-offline-shell-v0401.js','assets/css/sc-lab-interface-finalization-v0401.css','contracts/interface-finalization-audit-v0401.schema.json','contracts/accessibility-preferences-v0401.schema.json','contracts/offline-project-snapshot-v0401.schema.json','contracts/offline-operation-v0401.schema.json','contracts/offline-reconciliation-receipt-v0401.schema.json','contracts/interface-finalization-policy-v0401.json');$files=array();$ok=true;foreach($required as $relative){$files[$relative]=self::state($relative);if(empty($files[$relative]['exists'])){$ok=false;}}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'interface-ready':'incomplete','version'=>self::VERSION,'wcagTarget'=>'WCAG 2.2 AA oriented; not a certification claim','responsiveAudits'=>true,'preferenceProfiles'=>true,'browserLocalSnapshots'=>true,'offlineQueue'=>true,'explicitReconciliation'=>true,'offlineShellOptIn'=>true,'restrictedDataMayBeCached'=>false,'serviceWorkerUrl'=>home_url('/?sc_lab_sw_v0401=1'),'files'=>$files,'time'=>gmdate('c')));}
}
SC_Lab_Interface_Finalization_V0401::init();
