<?php
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Experimental_Design_Power_Analysis_V01280 {
 const VERSION='0.128.0'; const ENGINE_VERSION='9.0.0'; const SCHEMA='sc-lab-experimental-design-power-analysis/0.128.0';
 public static function init(){ add_action('rest_api_init',array(__CLASS__,'routes')); }
 public static function routes(){ $ns='sc-lab/v1/analysis/v01280'; foreach(array('health','manifest','schema','catalog') as $r){register_rest_route($ns,'/'.$r,array('methods'=>'GET','callback'=>array(__CLASS__,$r),'permission_callback'=>'__return_true'));}}
 private static function state($r){$p=SC_LAB_DIR.$r;return array('exists'=>is_file($p),'sha256'=>is_file($p)?hash_file('sha256',$p):null);}
 public static function schema(){return rest_ensure_response(array('ok'=>true,'schema'=>self::SCHEMA,'version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'maxGroups'=>64,'maxFactors'=>12,'maxSimulations'=>200000,'apiRouteCount'=>30));}
 public static function catalog(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'methodFamilyCount'=>15,'figureFamilyCount'=>16,'automaticEffectSizeSelection'=>false,'automaticDesignSelection'=>false,'automaticSignificanceClaims'=>false,'automaticPowerGuarantee'=>false));}
 public static function manifest(){return rest_ensure_response(array('ok'=>true,'status'=>'experimental-design-power-analysis-ready','version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'analyticalPower'=>true,'simulationPower'=>true,'factorialDesign'=>true,'blockedRandomization'=>true,'clusterDesign'=>true,'sequentialPlanning'=>true,'adaptivePlanning'=>true,'precisionPlanning'=>true,'automaticEffectSizeSelection'=>false,'automaticDesignSelection'=>false,'automaticSampleSizeGuarantee'=>false,'automaticSignificanceClaims'=>false,'automaticScientificValidityCertification'=>false,'automaticCoreSubmission'=>false,'determineTruth'=>false));}
 public static function health(){ $req=array('contracts/experimental-design-power-analysis-v01280.schema.json','contracts/experimental-design-power-analysis-policy-v01280.json','includes/class-sc-lab-experimental-design-power-analysis-v01280.php','assets/js/modules/experimental-design-power-analysis-v01280.js','assets/css/sc-lab-experimental-design-power-analysis-v01280.css');$files=array();$ok=true;foreach($req as $r){$files[$r]=self::state($r);if(empty($files[$r]['exists']))$ok=false;}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'experimental-design-power-analysis-ready':'incomplete','version'=>self::VERSION,'labReleaseVersion'=>defined('SC_LAB_RELEASE_VERSION')?SC_LAB_RELEASE_VERSION:self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'methodFamilyCount'=>15,'figureFamilyCount'=>16,'apiRouteCount'=>30,'files'=>$files,'automaticDesignSelection'=>false,'automaticSignificanceClaims'=>false,'automaticScientificValidityCertification'=>false,'time'=>gmdate('c')));}
}
SC_Lab_Experimental_Design_Power_Analysis_V01280::init();
