<?php
/** Sustainable Catalyst Lab v0.76.0 Large-Data Visualization & Adaptive Rendering. */
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Large_Data_Visualization_V0760 {
    const VERSION = '0.76.0'; const ENGINE_VERSION = '2.3.0'; private static $initialized = false;
    public static function init(){ if(self::$initialized){return;} self::$initialized=true; add_action('rest_api_init',array(__CLASS__,'routes')); }
    public static function routes(){ register_rest_route('sc-lab/v1','/visualization/v0760/health',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'health'),'permission_callback'=>'__return_true')); register_rest_route('sc-lab/v1','/visualization/v0760/schema',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'schema'),'permission_callback'=>'__return_true')); }
    private static function file_state($relative){$path=SC_LAB_DIR.ltrim((string)$relative,'/');return array('exists'=>is_file($path),'sha256'=>is_file($path)?hash_file('sha256',$path):null);}
    public static function schema(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'planSchema'=>'sc-lab-adaptive-render-plan/0.76.0','resultSchema'=>'sc-lab-adaptive-render-result/0.76.0','specSchema'=>'sc-lab-scientific-visualization/0.76.0','figureSchema'=>'sc-lab-scientific-figure/0.76.0','workspaceSchema'=>'sc-lab-figure-workspace/0.76.0','strategies'=>array('auto','full','stride','lttb','grid','quantile'),'progressiveLevels'=>array('preview','interactive','detail'),'limits'=>array('backendSourceRows'=>250000,'browserInlineRows'=>50000,'renderPoints'=>5000,'defaultRenderPoints'=>2000),'capabilities'=>array('largeDataVisualization'=>true,'adaptiveRendering'=>true,'progressiveRendering'=>true,'deterministicReduction'=>true,'sourceDatasetPreserved'=>true,'v0750DataBindingCompatibility'=>true,'realProjectData4dPointProjection'=>true),'boundaries'=>array('silentDataMutation'=>false,'transformAfterSampling'=>false,'streaming'=>false,'serverSideTiles'=>false,'webgl'=>false,'interpolation'=>false,'forecasting'=>false,'arbitraryCode'=>false)));}
    public static function health(){ $required=array('backend/app/large_data_visualization_v0760.py','backend/tests/test_large_data_visualization_v0760.py','assets/js/modules/large-data-visualization-v0760.js','assets/js/modules/graph-studio-v0760.js','assets/css/sc-lab-large-data-visualization-v0760.css','contracts/adaptive-render-plan-v0760.schema.json','contracts/adaptive-render-result-v0760.schema.json','contracts/scientific-visualization-v0760.schema.json','contracts/scientific-figure-v0760.schema.json','contracts/figure-workspace-v0760.schema.json');$files=array();$ok=true;foreach($required as $relative){$files[$relative]=self::file_state($relative);if(empty($files[$relative]['exists'])){$ok=false;}}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'large-data-adaptive-rendering-ready':'incomplete','version'=>self::VERSION,'release'=>defined('SC_LAB_RELEASE_VERSION')?SC_LAB_RELEASE_VERSION:null,'platformVersion'=>defined('SC_LAB_PLATFORM_VERSION')?SC_LAB_PLATFORM_VERSION:null,'engineVersion'=>self::ENGINE_VERSION,'largeDataVisualization'=>true,'adaptiveRendering'=>true,'progressiveRendering'=>true,'deterministicReduction'=>true,'sourceRowLimit'=>250000,'renderPointLimit'=>5000,'v0750DataBindingCompatibility'=>true,'advanced2dCompatibility'=>true,'canvas4dCompatibility'=>true,'silentDataMutation'=>false,'streaming'=>false,'webgl'=>false,'arbitraryCode'=>false,'files'=>$files,'time'=>gmdate('c')));}
}
