<?php
/** Sustainable Catalyst Lab v0.160.0 — Computational Research Operating System II. */
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Computational_Research_Operating_System_II_V01600 {
 const VERSION='0.160.0'; private static $initialized=false;
 public static function init(){if(self::$initialized)return;self::$initialized=true;add_action('wp_enqueue_scripts',array(__CLASS__,'enqueue'),PHP_INT_MAX);add_action('wp_print_footer_scripts',array(__CLASS__,'enqueue'),PHP_INT_MAX);add_action('rest_api_init',array(__CLASS__,'routes'));}
 private static function is_lab_request(){if(is_admin())return false;global $post;if($post instanceof WP_Post&&has_shortcode((string)$post->post_content,'sc_lab_app'))return true;if(function_exists('is_page')&&is_page('lab'))return true;$path=isset($_SERVER['REQUEST_URI'])?(string)parse_url((string)$_SERVER['REQUEST_URI'],PHP_URL_PATH):'';return(bool)preg_match('~/(?:lab)/?$~',$path);}
 private static function asset_token($relative){$path=SC_LAB_DIR.ltrim((string)$relative,'/');return self::VERSION.'.'.(is_file($path)?substr(hash_file('sha256',$path),0,16):'missing');}
 public static function enqueue(){if(!self::is_lab_request())return;$css='assets/css/sc-lab-computational-research-os-ii-v01600.css';$js='assets/js/sc-lab-computational-research-os-ii-v01600.js';wp_enqueue_style('sc-lab-research-os-v01600',SC_LAB_URL.$css,array('sc-lab-review-gate-v01590'),self::asset_token($css));wp_enqueue_script('sc-lab-research-os-v01600',SC_LAB_URL.$js,array('sc-lab-review-gate-v01590','sc-lab-canonical-repair-v015701'),self::asset_token($js),true);wp_localize_script('sc-lab-research-os-v01600','SCLabResearchOSV01600',array('version'=>self::VERSION,'healthUrl'=>esc_url_raw(rest_url('sc-lab/v1/workspace/research-os/v01600/health')),'projectsUrl'=>esc_url_raw(rest_url('sc-lab/v1/workspace/research-os/v01600/projects')),'packagesUrl'=>esc_url_raw(rest_url('sc-lab/v1/workspace/research-os/v01600/packages')),'verifyUrl'=>esc_url_raw(rest_url('sc-lab/v1/workspace/research-os/v01600/manifests/verify')),'defaultProjectId'=>is_user_logged_in()?'research:wp-user-'.get_current_user_id():'','nonce'=>wp_create_nonce('wp_rest')));}
 public static function operations_permission(){return is_user_logged_in();}
 private static function settings(){return wp_parse_args((array)get_option('sc_lab_settings',array()),SC_Lab_Admin::defaults());}
 private static function clean_id($v){return substr(preg_replace('/[^A-Za-z0-9._:-]/','',(string)$v),0,180);}
 private static function clean_tree($v,$depth=0,&$nodes=0){$nodes++;if($nodes>30000||$depth>24)return null;if(is_null($v)||is_bool($v)||is_int($v)||is_float($v))return $v;if(is_string($v))return substr(wp_check_invalid_utf8($v,true),0,150000);if(!is_array($v))return null;$out=array();$count=0;foreach($v as $k=>$x){if(++$count>10000)break;$key=is_int($k)?$k:substr(preg_replace('/[^A-Za-z0-9._:-]/','',(string)$k),0,128);if($key===''&&!is_int($k))continue;$out[$key]=self::clean_tree($x,$depth+1,$nodes);}return $out;}
 private static function body(WP_REST_Request $r){$b=$r->get_json_params();$n=0;return self::clean_tree(is_array($b)?$b:array(),0,$n);}
 private static function proxy($path,$method='GET',$payload=null,$limit=8388608){$s=self::settings();if(empty($s['enable_remote_compute'])||empty($s['compute_backend_url']))return new WP_Error('compute_disabled','The Python Compute Core is not enabled or configured.',array('status'=>503));if(!class_exists('SC_Lab_Python_Compute_Core_V0261'))return new WP_Error('compute_proxy_unavailable','The Python Compute Core signing bridge is unavailable.',array('status'=>503));$body=null===$payload?'':wp_json_encode($payload);$url=untrailingslashit($s['compute_backend_url']).$path;$args=array('method'=>$method,'timeout'=>max(5,min(120,absint($s['compute_timeout_seconds']))),'redirection'=>2,'sslverify'=>!empty($s['compute_verify_ssl']),'headers'=>SC_Lab_Python_Compute_Core_V0261::signed_headers($path,$method,$body,$s),'limit_response_size'=>max(262144,min(16777216,absint($limit))));if(null!==$payload)$args['body']=$body;$response=wp_safe_remote_request($url,$args);if(is_wp_error($response))return new WP_Error('research_os_backend_unavailable',$response->get_error_message(),array('status'=>502));$status=wp_remote_retrieve_response_code($response);$decoded=json_decode(wp_remote_retrieve_body($response),true);if(!is_array($decoded)){$decoded=array('detail'=>'The research OS backend returned invalid JSON.');$status=502;}return new WP_REST_Response($decoded,$status);}
 private static function ppath(WP_REST_Request $r,$suffix=''){return '/v1/computational-research-operating-system-ii/v01600/projects/'.rawurlencode(self::clean_id($r['id'])).$suffix;}
 public static function routes(){
  register_rest_route('sc-lab/v1','/workspace/research-os/v01600/health',array('methods'=>'GET','callback'=>array(__CLASS__,'health'),'permission_callback'=>'__return_true'));
  register_rest_route('sc-lab/v1','/workspace/research-os/v01600/projects',array(array('methods'=>'GET','callback'=>array(__CLASS__,'projects'),'permission_callback'=>array(__CLASS__,'operations_permission')),array('methods'=>'POST','callback'=>array(__CLASS__,'project_create'),'permission_callback'=>array(__CLASS__,'operations_permission'))));
  register_rest_route('sc-lab/v1','/workspace/research-os/v01600/projects/(?P<id>[A-Za-z0-9._:-]{1,180})',array('methods'=>'GET','callback'=>array(__CLASS__,'project_get'),'permission_callback'=>array(__CLASS__,'operations_permission')));
  foreach(array('objects'=>'POST','transition'=>'POST','command-center'=>'GET','validate'=>'GET','packages'=>'POST','manifest'=>'GET','timeline'=>'GET','archive'=>'POST') as $suffix=>$method)register_rest_route('sc-lab/v1','/workspace/research-os/v01600/projects/(?P<id>[A-Za-z0-9._:-]{1,180})/'.$suffix,array('methods'=>$method,'callback'=>array(__CLASS__,str_replace('-','_',$suffix)),'permission_callback'=>array(__CLASS__,'operations_permission')));
  register_rest_route('sc-lab/v1','/workspace/research-os/v01600/projects/(?P<id>[A-Za-z0-9._:-]{1,180})/objects/(?P<object>[A-Za-z0-9._:-]{1,180})/observe',array('methods'=>'POST','callback'=>array(__CLASS__,'observe'),'permission_callback'=>array(__CLASS__,'operations_permission')));
  register_rest_route('sc-lab/v1','/workspace/research-os/v01600/packages/(?P<package>[A-Za-z0-9._:-]{1,180})',array('methods'=>'GET','callback'=>array(__CLASS__,'package_get'),'permission_callback'=>array(__CLASS__,'operations_permission')));
  register_rest_route('sc-lab/v1','/workspace/research-os/v01600/packages/(?P<package>[A-Za-z0-9._:-]{1,180})/handoff',array('methods'=>'POST','callback'=>array(__CLASS__,'handoff'),'permission_callback'=>array(__CLASS__,'operations_permission')));
  register_rest_route('sc-lab/v1','/workspace/research-os/v01600/manifests/verify',array('methods'=>'POST','callback'=>array(__CLASS__,'verify_manifest'),'permission_callback'=>array(__CLASS__,'operations_permission')));
 }
 public static function health(){return self::proxy('/v1/computational-research-operating-system-ii/v01600/health');}
 public static function projects(WP_REST_Request $r){$q='?include_archived='.($r->get_param('include_archived')?'true':'false').'&limit='.max(1,min(1000,absint($r->get_param('limit')?:100)));return self::proxy('/v1/computational-research-operating-system-ii/v01600/projects'.$q);}
 public static function project_create(WP_REST_Request $r){return self::proxy('/v1/computational-research-operating-system-ii/v01600/projects','POST',self::body($r));}
 public static function project_get(WP_REST_Request $r){return self::proxy(self::ppath($r));}
 public static function objects(WP_REST_Request $r){return self::proxy(self::ppath($r,'/objects'),'POST',self::body($r));}
 public static function observe(WP_REST_Request $r){return self::proxy(self::ppath($r,'/objects/'.rawurlencode(self::clean_id($r['object'])).'/observe'),'POST',self::body($r));}
 public static function transition(WP_REST_Request $r){return self::proxy(self::ppath($r,'/transition'),'POST',self::body($r));}
 public static function command_center(WP_REST_Request $r){return self::proxy(self::ppath($r,'/command-center'));}
 public static function validate(WP_REST_Request $r){$target=self::clean_id($r->get_param('target_stage'));return self::proxy(self::ppath($r,'/validate').($target?'?target_stage='.rawurlencode($target):''));}
 public static function packages(WP_REST_Request $r){return self::proxy(self::ppath($r,'/packages'),'POST',self::body($r));}
 public static function manifest(WP_REST_Request $r){return self::proxy(self::ppath($r,'/manifest'));}
 public static function timeline(WP_REST_Request $r){return self::proxy(self::ppath($r,'/timeline').'?limit='.max(1,min(5000,absint($r->get_param('limit')?:500))));}
 public static function archive(WP_REST_Request $r){return self::proxy(self::ppath($r,'/archive'),'POST',self::body($r));}
 public static function package_get(WP_REST_Request $r){return self::proxy('/v1/computational-research-operating-system-ii/v01600/packages/'.rawurlencode(self::clean_id($r['package'])));}
 public static function handoff(WP_REST_Request $r){return self::proxy('/v1/computational-research-operating-system-ii/v01600/packages/'.rawurlencode(self::clean_id($r['package'])).'/handoff','POST',self::body($r));}
 public static function verify_manifest(WP_REST_Request $r){return self::proxy('/v1/computational-research-operating-system-ii/v01600/manifests/verify','POST',self::body($r));}
}
