<?php
/** Sustainable Catalyst Lab v0.47.0 Graph Studio, Scientific Figure Workspace & Interface Reorganization. */
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Graph_Studio_V0470 {
    const VERSION='0.47.0'; private static $initialized=false;
    public static function init(){if(self::$initialized){return;}self::$initialized=true;add_action('rest_api_init',array(__CLASS__,'routes'));add_filter('sc_lab_module_aliases_v02631',array(__CLASS__,'aliases'));add_filter('sc_lab_panel_aliases_v02631',array(__CLASS__,'aliases'));add_shortcode('sc_lab_graph_studio',array(__CLASS__,'shortcode'));}
    public static function aliases($aliases){$aliases=is_array($aliases)?$aliases:array();foreach(array('graph-studio','scientific-figure-workspace','scientific-figures','figure-studio','publication-figures','graphing','graphs') as $alias){$aliases[$alias]='graph-studio';}return $aliases;}
    public static function shortcode(){return do_shortcode('[sc_lab_app module="graph-studio"]');}
    public static function routes(){register_rest_route('sc-lab/v1','/graph-studio/v0470/health',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'health'),'permission_callback'=>'__return_true'));register_rest_route('sc-lab/v1','/graph-studio/v0470/schema',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'schema'),'permission_callback'=>'__return_true'));}
    private static function file_state($relative){$path=SC_LAB_DIR.$relative;return array('exists'=>is_file($path),'sha256'=>is_file($path)?hash_file('sha256',$path):null);}
    public static function schema(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'figureSchema'=>'sc-lab-scientific-figure/0.47.0','workspaceSchema'=>'sc-lab-figure-workspace/0.47.0','graphContract'=>'sc-lab-scientific-graph/0.46.0','sharedVisualizationEngine'=>'SCLabScientificVisualizationEngineV0440','publicationExports'=>array('svg','png','csv','json'),'arbitraryCode'=>false));}
    public static function health(){$required=array('backend/app/graph_studio.py','backend/tests/test_graph_studio_v0470.py','assets/js/modules/graph-studio-v0470.js','assets/js/modules/interface-reorganization-v0470.js','assets/js/modules/scientific-visualization-engine-v0440.js','assets/css/sc-lab-graph-studio-v0470.css','assets/css/sc-lab-interface-v0470.css','contracts/graph-studio-policy-v0470.json','contracts/scientific-figure-v0470.schema.json','contracts/figure-workspace-v0470.schema.json');$files=array();$ok=true;foreach($required as $relative){$files[$relative]=self::file_state($relative);if(empty($files[$relative]['exists'])){$ok=false;}}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'graph-studio-ready':'incomplete','version'=>self::VERSION,'release'=>defined('SC_LAB_RELEASE_VERSION')?SC_LAB_RELEASE_VERSION:null,'platformVersion'=>defined('SC_LAB_PLATFORM_VERSION')?SC_LAB_PLATFORM_VERSION:null,'dedicatedGraphWorkspace'=>true,'figureLibrary'=>true,'largeScientificCanvas'=>true,'modelStudioHandoff'=>true,'collapsibleNavigation'=>true,'modelNavigationGroup'=>true,'visualizeNavigationGroup'=>true,'publicationExports'=>array('svg','png','csv','json'),'sharedVisualizationEngine'=>true,'arbitraryCode'=>false,'files'=>$files,'time'=>gmdate('c')));}
}
