<?php
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Evidence_Synthesis_Intelligence_II_V01340 {
 const VERSION='0.134.0'; const ENGINE_VERSION='15.0.0'; const SCHEMA='sc-lab-evidence-synthesis-intelligence-ii/0.134.0';
 public static function init(){ add_action('rest_api_init',array(__CLASS__,'routes')); }
 public static function routes(){ $ns='sc-lab/v1/analysis/v01340'; foreach(array('health','manifest','schema','catalog') as $r){register_rest_route($ns,'/'.$r,array('methods'=>'GET','callback'=>array(__CLASS__,$r),'permission_callback'=>'__return_true'));}}
 private static function state($r){$p=SC_LAB_DIR.$r;return array('exists'=>is_file($p),'sha256'=>is_file($p)?hash_file('sha256',$p):null);}
 public static function schema(){return rest_ensure_response(array('ok'=>true,'schema'=>self::SCHEMA,'version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'synthesisStateCount'=>5,'apiRouteCount'=>44));}
 public static function catalog(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'synthesisFamilyCount'=>20,'evidenceKindCount'=>12,'figureFamilyCount'=>16,'researcherAdjudicationRequired'=>true,'automaticStudyQualityScoring'=>false,'automaticConsensusCertification'=>false,'determineTruth'=>false));}
 public static function manifest(){return rest_ensure_response(array('ok'=>true,'status'=>'evidence-synthesis-intelligence-ii-ready','version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'crossStudySynthesis'=>true,'quantitativePoolingBridgeV0640'=>true,'contradictionsPreserved'=>true,'heterogeneityPreserved'=>true,'replicationDisagreementPreserved'=>true,'researcherAdjudicationRequired'=>true,'automaticStudyQualityScoring'=>false,'automaticConsensusCertification'=>false,'automaticScientificValidityCertification'=>false,'automaticCoreSubmission'=>false,'determineTruth'=>false));}
 public static function health(){ $req=array('contracts/evidence-synthesis-intelligence-ii-v01340.schema.json','contracts/evidence-synthesis-intelligence-ii-policy-v01340.json','includes/class-sc-lab-evidence-synthesis-intelligence-ii-v01340.php','assets/js/modules/evidence-synthesis-intelligence-ii-v01340.js','assets/css/sc-lab-evidence-synthesis-intelligence-ii-v01340.css');$files=array();$ok=true;foreach($req as $r){$files[$r]=self::state($r);if(empty($files[$r]['exists']))$ok=false;}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'evidence-synthesis-intelligence-ii-ready':'incomplete','version'=>self::VERSION,'labReleaseVersion'=>defined('SC_LAB_RELEASE_VERSION')?SC_LAB_RELEASE_VERSION:self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'synthesisFamilyCount'=>20,'evidenceKindCount'=>12,'figureFamilyCount'=>16,'apiRouteCount'=>44,'files'=>$files,'researcherAdjudicationRequired'=>true,'automaticStudyQualityScoring'=>false,'automaticConsensusCertification'=>false,'automaticScientificValidityCertification'=>false,'automaticCoreSubmission'=>false,'time'=>gmdate('c')));}
}
SC_Lab_Evidence_Synthesis_Intelligence_II_V01340::init();
