<?php
/** Sustainable Catalyst Lab v0.162.0 — Cross-Project Dependency & Research Resource Planning. */
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Cross_Project_Dependency_Resource_Planning_V01620 {
 const VERSION='0.162.0'; private static $initialized=false;
 public static function init(){if(self::$initialized)return;self::$initialized=true;add_action('wp_enqueue_scripts',array(__CLASS__,'enqueue'),PHP_INT_MAX);add_action('wp_print_footer_scripts',array(__CLASS__,'enqueue'),PHP_INT_MAX);add_action('rest_api_init',array(__CLASS__,'routes'));}
 private static function is_lab_request(){if(is_admin())return false;global $post;if($post instanceof WP_Post&&has_shortcode((string)$post->post_content,'sc_lab_app'))return true;if(function_exists('is_page')&&is_page('lab'))return true;$path=isset($_SERVER['REQUEST_URI'])?(string)parse_url((string)$_SERVER['REQUEST_URI'],PHP_URL_PATH):'';return(bool)preg_match('~/(?:lab)/?$~',$path);}
 private static function asset_token($relative){$path=SC_LAB_DIR.ltrim((string)$relative,'/');return self::VERSION.'.'.(is_file($path)?substr(hash_file('sha256',$path),0,16):'missing');}
 public static function enqueue(){if(!self::is_lab_request())return;$css='assets/css/sc-lab-cross-project-resource-planning-v01620.css';$js='assets/js/sc-lab-cross-project-resource-planning-v01620.js';wp_enqueue_style('sc-lab-cross-project-resource-planning-v01620',SC_LAB_URL.$css,array('sc-lab-program-portfolio-v01610'),self::asset_token($css));wp_enqueue_script('sc-lab-cross-project-resource-planning-v01620',SC_LAB_URL.$js,array('sc-lab-program-portfolio-v01610','sc-lab-canonical-repair-v015701'),self::asset_token($js),true);wp_localize_script('sc-lab-cross-project-resource-planning-v01620','SCLabCrossProjectResourcePlanningV01620',array('version'=>self::VERSION,'baseUrl'=>esc_url_raw(rest_url('sc-lab/v1/workspace/cross-project-resource-planning/v01620')),'defaultProgramId'=>is_user_logged_in()?'program:wp-user-'.get_current_user_id():'','nonce'=>wp_create_nonce('wp_rest')));}
 public static function operations_permission(){return is_user_logged_in();}
 private static function settings(){return wp_parse_args((array)get_option('sc_lab_settings',array()),SC_Lab_Admin::defaults());}
 private static function clean_id($v){return substr(preg_replace('/[^A-Za-z0-9._:-]/','',(string)$v),0,180);}
 private static function clean_tree($v,$depth=0,&$nodes=0){$nodes++;if($nodes>30000||$depth>24)return null;if(is_null($v)||is_bool($v)||is_int($v)||is_float($v))return $v;if(is_string($v))return substr(wp_check_invalid_utf8($v,true),0,150000);if(!is_array($v))return null;$out=array();$count=0;foreach($v as $k=>$x){if(++$count>10000)break;$key=is_int($k)?$k:substr(preg_replace('/[^A-Za-z0-9._:-]/','',(string)$k),0,128);if($key===''&&!is_int($k))continue;$out[$key]=self::clean_tree($x,$depth+1,$nodes);}return $out;}
 private static function body(WP_REST_Request $r){$b=$r->get_json_params();$n=0;return self::clean_tree(is_array($b)?$b:array(),0,$n);}
 private static function proxy($path,$method='GET',$payload=null,$limit=8388608){$s=self::settings();if(empty($s['enable_remote_compute'])||empty($s['compute_backend_url']))return new WP_Error('compute_disabled','The Python Compute Core is not enabled or configured.',array('status'=>503));if(!class_exists('SC_Lab_Python_Compute_Core_V0261'))return new WP_Error('compute_proxy_unavailable','The Python Compute Core signing bridge is unavailable.',array('status'=>503));$body=null===$payload?'':wp_json_encode($payload);$args=array('method'=>$method,'timeout'=>max(5,min(120,absint($s['compute_timeout_seconds']))),'redirection'=>2,'sslverify'=>!empty($s['compute_verify_ssl']),'headers'=>SC_Lab_Python_Compute_Core_V0261::signed_headers($path,$method,$body,$s),'limit_response_size'=>max(262144,min(16777216,absint($limit))));if(null!==$payload)$args['body']=$body;$response=wp_safe_remote_request(untrailingslashit($s['compute_backend_url']).$path,$args);if(is_wp_error($response))return new WP_Error('cross_project_resource_backend_unavailable',$response->get_error_message(),array('status'=>502));$status=wp_remote_retrieve_response_code($response);$decoded=json_decode(wp_remote_retrieve_body($response),true);if(!is_array($decoded)){$decoded=array('detail'=>'The cross-project resource-planning backend returned invalid JSON.');$status=502;}return new WP_REST_Response($decoded,$status);}
 private static function base(){return '/v1/cross-project-dependency-resource-planning/v01620';}
 private static function program_path(WP_REST_Request $r,$suffix=''){return self::base().'/programs/'.rawurlencode(self::clean_id($r['id'])).$suffix;}
 public static function routes(){
  register_rest_route('sc-lab/v1','/workspace/cross-project-resource-planning/v01620/health',array('methods'=>'GET','callback'=>array(__CLASS__,'health'),'permission_callback'=>'__return_true'));
  register_rest_route('sc-lab/v1','/workspace/cross-project-resource-planning/v01620/programs/(?P<id>[A-Za-z0-9._:-]{1,180})/dependencies',array(array('methods'=>'GET','callback'=>array(__CLASS__,'dependencies'),'permission_callback'=>array(__CLASS__,'operations_permission')),array('methods'=>'POST','callback'=>array(__CLASS__,'dependency_create'),'permission_callback'=>array(__CLASS__,'operations_permission'))));
  register_rest_route('sc-lab/v1','/workspace/cross-project-resource-planning/v01620/programs/(?P<id>[A-Za-z0-9._:-]{1,180})/dependencies/(?P<object>[A-Za-z0-9._:-]{1,180})/status',array('methods'=>'POST','callback'=>array(__CLASS__,'dependency_status'),'permission_callback'=>array(__CLASS__,'operations_permission')));
  register_rest_route('sc-lab/v1','/workspace/cross-project-resource-planning/v01620/programs/(?P<id>[A-Za-z0-9._:-]{1,180})/resources',array(array('methods'=>'GET','callback'=>array(__CLASS__,'resources'),'permission_callback'=>array(__CLASS__,'operations_permission')),array('methods'=>'POST','callback'=>array(__CLASS__,'resource_create'),'permission_callback'=>array(__CLASS__,'operations_permission'))));
  register_rest_route('sc-lab/v1','/workspace/cross-project-resource-planning/v01620/programs/(?P<id>[A-Za-z0-9._:-]{1,180})/resources/(?P<object>[A-Za-z0-9._:-]{1,180})/state',array('methods'=>'POST','callback'=>array(__CLASS__,'resource_state'),'permission_callback'=>array(__CLASS__,'operations_permission')));
  register_rest_route('sc-lab/v1','/workspace/cross-project-resource-planning/v01620/programs/(?P<id>[A-Za-z0-9._:-]{1,180})/requirements',array(array('methods'=>'GET','callback'=>array(__CLASS__,'requirements'),'permission_callback'=>array(__CLASS__,'operations_permission')),array('methods'=>'POST','callback'=>array(__CLASS__,'requirement_create'),'permission_callback'=>array(__CLASS__,'operations_permission'))));
  register_rest_route('sc-lab/v1','/workspace/cross-project-resource-planning/v01620/programs/(?P<id>[A-Za-z0-9._:-]{1,180})/requirements/(?P<object>[A-Za-z0-9._:-]{1,180})/status',array('methods'=>'POST','callback'=>array(__CLASS__,'requirement_status'),'permission_callback'=>array(__CLASS__,'operations_permission')));
  foreach(array('analysis'=>'GET','plans'=>'GET','command-center'=>'GET','manifest'=>'GET','snapshot'=>'POST','timeline'=>'GET') as $suffix=>$method)register_rest_route('sc-lab/v1','/workspace/cross-project-resource-planning/v01620/programs/(?P<id>[A-Za-z0-9._:-]{1,180})/'.$suffix,array('methods'=>$method,'callback'=>array(__CLASS__,str_replace('-','_',$suffix)),'permission_callback'=>array(__CLASS__,'operations_permission')));
  register_rest_route('sc-lab/v1','/workspace/cross-project-resource-planning/v01620/programs/(?P<id>[A-Za-z0-9._:-]{1,180})/plans',array('methods'=>'POST','callback'=>array(__CLASS__,'plan_create'),'permission_callback'=>array(__CLASS__,'operations_permission')));
  register_rest_route('sc-lab/v1','/workspace/cross-project-resource-planning/v01620/plans/(?P<plan>[A-Za-z0-9._:-]{1,180})',array('methods'=>'GET','callback'=>array(__CLASS__,'plan_get'),'permission_callback'=>array(__CLASS__,'operations_permission')));
  register_rest_route('sc-lab/v1','/workspace/cross-project-resource-planning/v01620/plans/(?P<plan>[A-Za-z0-9._:-]{1,180})/evaluate',array('methods'=>'GET','callback'=>array(__CLASS__,'plan_evaluate'),'permission_callback'=>array(__CLASS__,'operations_permission')));
  register_rest_route('sc-lab/v1','/workspace/cross-project-resource-planning/v01620/plans/(?P<plan>[A-Za-z0-9._:-]{1,180})/transition',array('methods'=>'POST','callback'=>array(__CLASS__,'plan_transition'),'permission_callback'=>array(__CLASS__,'operations_permission')));
  register_rest_route('sc-lab/v1','/workspace/cross-project-resource-planning/v01620/snapshots/(?P<snapshot>[A-Za-z0-9._:-]{1,180})',array('methods'=>'GET','callback'=>array(__CLASS__,'snapshot_get'),'permission_callback'=>array(__CLASS__,'operations_permission')));
  register_rest_route('sc-lab/v1','/workspace/cross-project-resource-planning/v01620/manifests/verify',array('methods'=>'POST','callback'=>array(__CLASS__,'verify_manifest'),'permission_callback'=>array(__CLASS__,'operations_permission')));
 }
 public static function health(){return self::proxy(self::base().'/health');}
 public static function dependencies(WP_REST_Request $r){return self::proxy(self::program_path($r,'/dependencies'));}
 public static function dependency_create(WP_REST_Request $r){return self::proxy(self::program_path($r,'/dependencies'),'POST',self::body($r));}
 public static function dependency_status(WP_REST_Request $r){return self::proxy(self::program_path($r,'/dependencies/'.rawurlencode(self::clean_id($r['object'])).'/status'),'POST',self::body($r));}
 public static function resources(WP_REST_Request $r){return self::proxy(self::program_path($r,'/resources'));}
 public static function resource_create(WP_REST_Request $r){return self::proxy(self::program_path($r,'/resources'),'POST',self::body($r));}
 public static function resource_state(WP_REST_Request $r){return self::proxy(self::program_path($r,'/resources/'.rawurlencode(self::clean_id($r['object'])).'/state'),'POST',self::body($r));}
 public static function requirements(WP_REST_Request $r){return self::proxy(self::program_path($r,'/requirements'));}
 public static function requirement_create(WP_REST_Request $r){return self::proxy(self::program_path($r,'/requirements'),'POST',self::body($r));}
 public static function requirement_status(WP_REST_Request $r){return self::proxy(self::program_path($r,'/requirements/'.rawurlencode(self::clean_id($r['object'])).'/status'),'POST',self::body($r));}
 public static function analysis(WP_REST_Request $r){return self::proxy(self::program_path($r,'/analysis'));}
 public static function plans(WP_REST_Request $r){return self::proxy(self::program_path($r,'/plans'));}
 public static function plan_create(WP_REST_Request $r){return self::proxy(self::program_path($r,'/plans'),'POST',self::body($r));}
 public static function command_center(WP_REST_Request $r){return self::proxy(self::program_path($r,'/command-center'));}
 public static function manifest(WP_REST_Request $r){return self::proxy(self::program_path($r,'/manifest'));}
 public static function snapshot(WP_REST_Request $r){return self::proxy(self::program_path($r,'/snapshot'),'POST',self::body($r));}
 public static function timeline(WP_REST_Request $r){return self::proxy(self::program_path($r,'/timeline'));}
 public static function plan_get(WP_REST_Request $r){return self::proxy(self::base().'/plans/'.rawurlencode(self::clean_id($r['plan'])));}
 public static function plan_evaluate(WP_REST_Request $r){return self::proxy(self::base().'/plans/'.rawurlencode(self::clean_id($r['plan'])).'/evaluate');}
 public static function plan_transition(WP_REST_Request $r){return self::proxy(self::base().'/plans/'.rawurlencode(self::clean_id($r['plan'])).'/transition','POST',self::body($r));}
 public static function snapshot_get(WP_REST_Request $r){return self::proxy(self::base().'/snapshots/'.rawurlencode(self::clean_id($r['snapshot'])));}
 public static function verify_manifest(WP_REST_Request $r){return self::proxy(self::base().'/manifests/verify','POST',self::body($r));}
}
