<?php
/** Sustainable Catalyst Lab v0.43.0 Model Diagnostics, Cross-Validation & Scientific Model Comparison. */
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Model_Studio_V0430 {
    const VERSION='0.43.0'; private static $initialized=false;
    public static function init(){if(self::$initialized){return;}self::$initialized=true;add_action('rest_api_init',array(__CLASS__,'routes'));add_filter('sc_lab_module_aliases_v02631',array(__CLASS__,'aliases'));add_filter('sc_lab_panel_aliases_v02631',array(__CLASS__,'aliases'));add_shortcode('sc_lab_model_studio',array(__CLASS__,'shortcode'));}
    public static function aliases($aliases){$aliases=is_array($aliases)?$aliases:array();foreach(array('model-studio','scientific-model-studio','model-builder','scientific-modeling','equation-builder','model-diagnostics','cross-validation','model-comparison') as $alias){$aliases[$alias]='model-studio';}return $aliases;}
    public static function shortcode(){return do_shortcode('[sc_lab_app module="model-studio"]');}
    public static function routes(){register_rest_route('sc-lab/v1','/model-studio/v0430/health',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'health'),'permission_callback'=>'__return_true'));register_rest_route('sc-lab/v1','/model-studio/v0430/schema',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'schema'),'permission_callback'=>'__return_true'));}
    private static function file_state($relative){$path=SC_LAB_DIR.$relative;return array('exists'=>is_file($path),'sha256'=>is_file($path)?hash_file('sha256',$path):null);}
    public static function schema(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'modelSchema'=>'sc-lab-model-studio-model/0.43.0','graphSchema'=>'sc-lab-scientific-graph/0.43.0','diagnosticsSchema'=>'sc-lab-model-diagnostics/0.43.0','crossValidationSchema'=>'sc-lab-cross-validation/0.43.0','comparisonSchema'=>'sc-lab-scientific-model-comparison/0.43.0','equationSchema'=>'sc-lab-scientific-equation/0.42.0','sharedVisualizationEngine'=>'SCLabScientificVisualizationEngineV0410','arbitraryCode'=>false,'arbitraryFormulaFitting'=>false,'registeredCalibrationForms'=>true));}
    public static function health(){$required=array('backend/app/model_studio.py','backend/app/model_diagnostics.py','backend/app/equation_builder.py','backend/tests/test_model_studio_v0430.py','backend/tests/test_model_diagnostics_v0430.py','assets/js/modules/model-studio-v0430.js','assets/js/modules/scientific-visualization-engine-v0410.js','assets/css/sc-lab-model-studio-v0430.css','contracts/model-studio-policy-v0430.json','contracts/model-studio-model-v0430.schema.json','contracts/model-diagnostics-v0430.schema.json','contracts/cross-validation-v0430.schema.json','contracts/model-comparison-v0430.schema.json','contracts/scientific-graph-v0430.schema.json');$files=array();$ok=true;foreach($required as $relative){$files[$relative]=self::file_state($relative);if(empty($files[$relative]['exists'])){$ok=false;}}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'model-diagnostics-ready':'incomplete','version'=>self::VERSION,'release'=>defined('SC_LAB_RELEASE_VERSION')?SC_LAB_RELEASE_VERSION:null,'platformVersion'=>defined('SC_LAB_PLATFORM_VERSION')?SC_LAB_PLATFORM_VERSION:null,'crossValidation'=>true,'repeatedCrossValidation'=>true,'residualDiagnostics'=>true,'scientificModelComparison'=>true,'sharedVisualizationEngine'=>true,'arbitraryCode'=>false,'arbitraryFormulaFitting'=>false,'files'=>$files,'time'=>gmdate('c')));}
}
