<?php
/** Sustainable Catalyst Lab v0.48.0 Integrated Uncertainty, Sensitivity & Probabilistic Visualization. */
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Probabilistic_Analysis_V0480 {
    const VERSION='0.48.0'; private static $initialized=false;
    public static function init(){if(self::$initialized){return;}self::$initialized=true;add_action('rest_api_init',array(__CLASS__,'routes'));add_filter('sc_lab_module_aliases_v02631',array(__CLASS__,'aliases'));add_filter('sc_lab_panel_aliases_v02631',array(__CLASS__,'aliases'));add_shortcode('sc_lab_probabilistic_analysis',array(__CLASS__,'shortcode'));add_shortcode('sc_lab_uncertainty_studio',array(__CLASS__,'shortcode'));}
    public static function aliases($aliases){$aliases=is_array($aliases)?$aliases:array();foreach(array('probabilistic-analysis','uncertainty-studio','integrated-uncertainty','sensitivity-analysis','probabilistic-visualization','uncertainty-sensitivity') as $alias){$aliases[$alias]='probabilistic-analysis';}return $aliases;}
    public static function shortcode(){return do_shortcode('[sc_lab_app module="probabilistic-analysis"]');}
    public static function routes(){register_rest_route('sc-lab/v1','/probabilistic-analysis/v0480/health',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'health'),'permission_callback'=>'__return_true'));register_rest_route('sc-lab/v1','/probabilistic-analysis/v0480/schema',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'schema'),'permission_callback'=>'__return_true'));}
    private static function file_state($relative){$path=SC_LAB_DIR.$relative;return array('exists'=>is_file($path),'sha256'=>is_file($path)?hash_file('sha256',$path):null);}
    public static function schema(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'studySchema'=>'sc-lab-probabilistic-study/0.48.0','resultSchema'=>'sc-lab-probabilistic-analysis/0.48.0','graphContract'=>'sc-lab-scientific-graph/0.46.0','designs'=>array('monte-carlo','latin-hypercube','sobol','saltelli-sobol'),'distributions'=>array('uniform','normal','lognormal','triangular'),'sensitivity'=>array('pearson','spearman','standardized-regression','saltelli-sobol'),'sharedVisualizationEngine'=>'SCLabScientificVisualizationEngineV0440','graphStudio'=>'0.47.0','arbitraryCode'=>false));}
    public static function health(){$required=array('backend/app/probabilistic_analysis.py','backend/tests/test_probabilistic_analysis_v0480.py','assets/js/modules/probabilistic-analysis-v0480.js','assets/css/sc-lab-probabilistic-analysis-v0480.css','contracts/probabilistic-study-v0480.schema.json','contracts/probabilistic-analysis-v0480.schema.json','contracts/probabilistic-policy-v0480.json');$files=array();$ok=true;foreach($required as $relative){$files[$relative]=self::file_state($relative);if(empty($files[$relative]['exists'])){$ok=false;}}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'integrated-probabilistic-analysis-ready':'incomplete','version'=>self::VERSION,'release'=>defined('SC_LAB_RELEASE_VERSION')?SC_LAB_RELEASE_VERSION:null,'platformVersion'=>defined('SC_LAB_PLATFORM_VERSION')?SC_LAB_PLATFORM_VERSION:null,'safeDeclarativeModels'=>true,'monteCarlo'=>true,'latinHypercube'=>true,'sobolSampling'=>true,'saltelliSobolSensitivity'=>true,'uncertaintyIntervals'=>true,'thresholdProbabilities'=>true,'uncertaintyRibbons'=>true,'graphStudioHandoff'=>true,'legacyRegisteredModelEnsembles'=>'0.34.1','arbitraryCode'=>false,'files'=>$files,'time'=>gmdate('c')));}
}
