<?php
/** Sustainable Catalyst Lab v0.31.0 Distributed Compute Dispatcher. */
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Distributed_Dispatcher_V0310 {
    const VERSION='0.31.0'; private static $initialized=false;
    public static function init(){if(self::$initialized){return;}self::$initialized=true;add_action('rest_api_init',array(__CLASS__,'routes'));add_filter('sc_lab_module_aliases_v02631',array(__CLASS__,'aliases'));add_shortcode('sc_lab_distributed_dispatcher',array(__CLASS__,'shortcode'));}
    public static function aliases($aliases){$aliases=is_array($aliases)?$aliases:array();foreach(array('distributed-dispatcher','distributed-compute','compute-dispatcher','worker-registry','compute-workers') as $a){$aliases[$a]='distributed-dispatcher';}return $aliases;}
    public static function shortcode(){return do_shortcode('[sc_lab_app module="distributed-dispatcher"]');}
    public static function routes(){register_rest_route('sc-lab/v1','/dispatcher/v0310/health',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'health'),'permission_callback'=>'__return_true'));register_rest_route('sc-lab/v1','/dispatcher/v0310/schema',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'schema'),'permission_callback'=>'__return_true'));}
    private static function file_state($rel){$p=SC_LAB_DIR.$rel;return array('exists'=>is_file($p),'sha256'=>is_file($p)?hash_file('sha256',$p):null);}
    public static function schema(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'workerSchema'=>'sc-lab-distributed-worker/0.31.0','workloadSchema'=>'sc-lab-distributed-workload/0.31.0','contractSchema'=>'sc-lab-dispatch-contract/0.31.0','workerTypes'=>array('browser-web-worker','render-cpu','local-python','raspberry-pi','institutional-node'),'persistentWorkerRegistry'=>false,'registeredMethodsOnly'=>true,'arbitraryCallbackUrls'=>false));}
    public static function health(){$required=array('assets/js/modules/distributed-dispatcher-v0310.js','assets/css/sc-lab-distributed-dispatcher-v0310.css','contracts/distributed-compute-policy-v0310.json','contracts/distributed-worker-v0310.schema.json','contracts/distributed-workload-v0310.schema.json','contracts/dispatch-contract-v0310.schema.json','includes/class-sc-lab-distributed-dispatcher-v0310.php');$files=array();$ok=true;foreach($required as $rel){$files[$rel]=self::file_state($rel);if(empty($files[$rel]['exists'])){$ok=false;}}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'ready':'incomplete','version'=>self::VERSION,'release'=>defined('SC_LAB_VERSION')?SC_LAB_VERSION:null,'architecture'=>'governed-distributed-compute-dispatcher','capabilityDiscovery'=>true,'workloadRouting'=>true,'signedDispatchContracts'=>true,'persistentWorkerRegistry'=>false,'files'=>$files,'time'=>gmdate('c')));}
}
