<?php
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Sensitivity_Global_Uncertainty_Analysis_Studio_V01240 {
 const VERSION='0.124.0'; const ENGINE_VERSION='5.0.0'; const SCHEMA='sc-lab-sensitivity-global-uncertainty-analysis-studio/0.124.0';
 public static function init(){ add_action('rest_api_init',array(__CLASS__,'routes')); }
 public static function routes(){ $ns='sc-lab/v1/analysis/v01240'; foreach(array('health','manifest','schema','catalog') as $r){register_rest_route($ns,'/'.$r,array('methods'=>'GET','callback'=>array(__CLASS__,$r),'permission_callback'=>'__return_true'));}}
 private static function state($r){$p=SC_LAB_DIR.$r;return array('exists'=>is_file($p),'sha256'=>is_file($p)?hash_file('sha256',$p):null);}
 public static function schema(){return rest_ensure_response(array('ok'=>true,'schema'=>self::SCHEMA,'version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'maxSobolBaseSamples'=>16384,'maxMorrisTrajectories'=>128,'maxResponseSurfaceEvaluations'=>20000,'apiRouteCount'=>22));}
 public static function catalog(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'methodFamilies'=>array('correlation-src-screening','morris-elementary-effects','quadratic-response-surface','saltelli-sobol','seed-replication','sensitivity-convergence'),'figureFamilyCount'=>12));}
 public static function manifest(){return rest_ensure_response(array('ok'=>true,'status'=>'sensitivity-global-uncertainty-analysis-studio-ready','version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'sobolFirstTotal'=>true,'morrisElementaryEffects'=>true,'varianceDecomposition'=>true,'interactionScreening'=>true,'responseSurfaces'=>true,'sensitivityConvergence'=>true,'seedReplication'=>true,'simulationOutputsAreModeledNotObserved'=>true,'sourceModelsImmutable'=>true,'automaticParameterRanking'=>false,'automaticSignificanceInference'=>false,'automaticCausalInference'=>false,'automaticModelSelection'=>false,'automaticScientificValidityCertification'=>false,'automaticCoreSubmission'=>false,'determineTruth'=>false));}
 public static function health(){ $req=array('contracts/sensitivity-global-uncertainty-analysis-studio-v01240.schema.json','contracts/sensitivity-global-uncertainty-analysis-policy-v01240.json','includes/class-sc-lab-sensitivity-global-uncertainty-analysis-studio-v01240.php','assets/js/modules/sensitivity-global-uncertainty-analysis-studio-v01240.js','assets/css/sc-lab-sensitivity-global-uncertainty-analysis-studio-v01240.css');$files=array();$ok=true;foreach($req as $r){$files[$r]=self::state($r);if(empty($files[$r]['exists']))$ok=false;}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'sensitivity-global-uncertainty-analysis-studio-ready':'incomplete','version'=>self::VERSION,'labReleaseVersion'=>defined('SC_LAB_RELEASE_VERSION')?SC_LAB_RELEASE_VERSION:self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'methodFamilyCount'=>6,'figureFamilyCount'=>12,'apiRouteCount'=>22,'files'=>$files,'simulationOutputsAreModeledNotObserved'=>true,'automaticParameterRanking'=>false,'automaticSignificanceInference'=>false,'automaticCausalInference'=>false,'automaticScientificValidityCertification'=>false,'time'=>gmdate('c')));}
}
SC_Lab_Sensitivity_Global_Uncertainty_Analysis_Studio_V01240::init();
