<?php
/** Sustainable Catalyst Lab v0.154.0 — Reproducible Protocol & Computational Notebook Workspace. */
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Reproducible_Protocol_Notebook_V01540 {
    const VERSION = '0.154.0';
    private static $initialized = false;
    private static $notice_registered = false;
    public static function init() {
        if (self::$initialized) { return; } self::$initialized = true;
        self::replace_integrity_notice();
        add_action('plugins_loaded', array(__CLASS__, 'replace_integrity_notice'), PHP_INT_MAX);
        add_action('admin_init', array(__CLASS__, 'replace_integrity_notice'), PHP_INT_MAX);
        add_action('wp_enqueue_scripts', array(__CLASS__, 'gate_frontend_assets'), PHP_INT_MAX);
        add_action('wp_print_footer_scripts', array(__CLASS__, 'gate_footer_scripts'), PHP_INT_MAX);
        add_action('rest_api_init', array(__CLASS__, 'routes'));
    }
    public static function replace_integrity_notice() {
        foreach (array('SC_Lab_Integrity_V02632','SC_Lab_Production_Safe_Boot_V015206','SC_Lab_Interactive_4D_Front_Door_V015207','SC_Lab_Response_Surface_Parameter_Explorer_V015209','SC_Lab_Uncertainty_Sensitivity_Ensemble_Explorer_V015210','SC_Lab_Linked_Scientific_Views_V015211','SC_Lab_Scene_Persistence_Provenance_Handoff_V015212','SC_Lab_Front_Door_Layout_Render_Recovery_V015213','SC_Lab_4D_Computational_Research_Workspace_V01530') as $class) { remove_action('admin_notices', array($class, 'admin_notice')); }
        if (!self::$notice_registered) { add_action('admin_notices', array(__CLASS__, 'admin_notice'), PHP_INT_MAX); self::$notice_registered = true; }
    }
    public static function admin_notice() {
        if (!current_user_can('activate_plugins')) { return; }
        if (!class_exists('SC_Lab_Integrity_V02632') || !method_exists('SC_Lab_Integrity_V02632', 'health')) { return; }
        $response = SC_Lab_Integrity_V02632::health(); $state = $response instanceof WP_REST_Response ? $response->get_data() : (is_array($response) ? $response : array());
        if (!empty($state['ok'])) { return; }
        $issues=array(); if(!empty($state['partialInstallRisk'])){$issues[]='release files, version markers, plugin identity, or canonical route contracts do not match';} if(!empty($state['duplicatePluginRisk'])){$issues[]='more than one Sustainable Catalyst Lab plugin folder exists in the WordPress plugin directory';} if(!$issues){$issues[]='the canonical runtime health check is not verified';}
        echo '<div class="notice notice-error"><p><strong>Sustainable Catalyst Lab integrity warning:</strong> '.esc_html(implode('; ',$issues)).'. Check <code>/wp-json/sc-lab/v1/runtime/health</code> before continuing upgrades.</p></div>';
    }
    private static function is_lab_request(){if(is_admin()){return false;}global $post;if($post instanceof WP_Post && has_shortcode((string)$post->post_content,'sc_lab_app')){return true;}if(function_exists('is_page')&&is_page('lab')){return true;}$path=isset($_SERVER['REQUEST_URI'])?(string)parse_url((string)$_SERVER['REQUEST_URI'],PHP_URL_PATH):'';return(bool)preg_match('~/(?:lab)/?$~',$path);}
    private static function is_lab_asset_src($src){return(string)$src!==''&&strpos((string)$src,'sustainable-catalyst-lab/')!==false;}
    private static function safe_script_relative(){return 'assets/js/sc-lab-safe-bootstrap-v01540.js';}
    private static function linked_script_relative(){return 'assets/js/sc-lab-linked-scientific-views-v01540.js';}
    private static function persistence_script_relative(){return 'assets/js/sc-lab-scene-persistence-provenance-handoff-v01540.js';}
    private static function workspace_script_relative(){return 'assets/js/sc-lab-4d-computational-research-workspace-v01540.js';}
    private static function notebook_script_relative(){return 'assets/js/sc-lab-reproducible-protocol-notebook-v01540.js';}
    private static function base_style_relative(){return 'assets/css/sc-lab-ui-bundle-v015204.css';}
    private static function linked_style_relative(){return 'assets/css/sc-lab-linked-scientific-views-v015212.css';}
    private static function recovery_style_relative(){return 'assets/css/sc-lab-front-door-layout-render-recovery-v015213.css';}
    private static function workspace_style_relative(){return 'assets/css/sc-lab-4d-computational-research-workspace-v01530.css';}
    private static function notebook_style_relative(){return 'assets/css/sc-lab-reproducible-protocol-notebook-v01540.css';}
    private static function allowed_script_src($src){$src=(string)$src;foreach(array(self::safe_script_relative(),self::linked_script_relative(),self::persistence_script_relative(),self::workspace_script_relative(),self::notebook_script_relative()) as $rel){if(strpos($src,$rel)!==false){return true;}}return false;}
    private static function allowed_style_src($src){$src=(string)$src;foreach(array(self::base_style_relative(),self::linked_style_relative(),self::recovery_style_relative(),self::workspace_style_relative(),self::notebook_style_relative()) as $rel){if(strpos($src,$rel)!==false){return true;}}return false;}
    private static function prune_scripts(){$scripts=wp_scripts();if(!$scripts){return;}foreach((array)$scripts->queue as $handle){$item=isset($scripts->registered[$handle])?$scripts->registered[$handle]:null;if(!$item||empty($item->src)||!self::is_lab_asset_src($item->src)){continue;}if(self::allowed_script_src($item->src)){continue;}wp_dequeue_script($handle);}}
    private static function prune_styles(){$styles=wp_styles();if(!$styles){return;}foreach((array)$styles->queue as $handle){$item=isset($styles->registered[$handle])?$styles->registered[$handle]:null;if(!$item||empty($item->src)||!self::is_lab_asset_src($item->src)){continue;}if(self::allowed_style_src($item->src)){continue;}wp_dequeue_style($handle);}}
    private static function enqueue_runtime(){
        $base=self::base_style_relative();$linkedStyle=self::linked_style_relative();$recovery=self::recovery_style_relative();$workspaceStyle=self::workspace_style_relative();$notebookStyle=self::notebook_style_relative();$safe=self::safe_script_relative();$linked=self::linked_script_relative();$persist=self::persistence_script_relative();$workspace=self::workspace_script_relative();$notebook=self::notebook_script_relative();
        wp_enqueue_style('sc-lab-safe-ui-v01540',SC_LAB_URL.$base,array(),self::asset_token($base));
        wp_enqueue_style('sc-lab-linked-views-v01540',SC_LAB_URL.$linkedStyle,array('sc-lab-safe-ui-v01540'),self::asset_token($linkedStyle));
        wp_enqueue_style('sc-lab-front-door-recovery-v01540',SC_LAB_URL.$recovery,array('sc-lab-linked-views-v01540'),self::asset_token($recovery));
        wp_enqueue_style('sc-lab-4d-workspace-v01540',SC_LAB_URL.$workspaceStyle,array('sc-lab-front-door-recovery-v01540'),self::asset_token($workspaceStyle));
        wp_enqueue_style('sc-lab-protocol-notebook-v01540',SC_LAB_URL.$notebookStyle,array('sc-lab-4d-workspace-v01540'),self::asset_token($notebookStyle));
        wp_enqueue_script('sc-lab-safe-bootstrap-v01540',SC_LAB_URL.$safe,array(),self::asset_token($safe),true);
        wp_enqueue_script('sc-lab-linked-views-v01540',SC_LAB_URL.$linked,array('sc-lab-safe-bootstrap-v01540'),self::asset_token($linked),true);
        wp_enqueue_script('sc-lab-scene-persistence-v01540',SC_LAB_URL.$persist,array('sc-lab-linked-views-v01540'),self::asset_token($persist),true);
        wp_enqueue_script('sc-lab-4d-workspace-v01540',SC_LAB_URL.$workspace,array('sc-lab-scene-persistence-v01540'),self::asset_token($workspace),true);
        wp_enqueue_script('sc-lab-protocol-notebook-v01540',SC_LAB_URL.$notebook,array('sc-lab-4d-workspace-v01540'),self::asset_token($notebook),true);
        wp_localize_script('sc-lab-safe-bootstrap-v01540','SCLabSafeBootV01540',array('version'=>self::VERSION,'releaseVersion'=>defined('SC_LAB_RELEASE_VERSION')?SC_LAB_RELEASE_VERSION:self::VERSION,'featureVersion'=>defined('SC_LAB_FEATURE_VERSION')?SC_LAB_FEATURE_VERSION:self::VERSION,'mode'=>'safe-shell-with-reproducible-protocol-notebook-workspace','healthUrl'=>esc_url_raw(rest_url('sc-lab/v1/frontend-runtime/v01540/health'))));
        wp_localize_script('sc-lab-linked-views-v01540','SCLabLinkedViewsV01540',array('version'=>self::VERSION,'computeHealthUrl'=>esc_url_raw(rest_url('sc-lab/v1/compute/core/health')),'computeCapabilitiesUrl'=>esc_url_raw(rest_url('sc-lab/v1/compute/core/capabilities')),'computeRunUrl'=>esc_url_raw(rest_url('sc-lab/v1/compute/core/run')),'nonce'=>wp_create_nonce('wp_rest'),'maxXSamples'=>41,'maxYLevels'=>7,'maxWSlices'=>5,'maxParallelRequests'=>3,'maxMonteCarloSamples'=>50000,'maxEnsembleMembers'=>7,'selectionHistoryLimit'=>12,'pinLimit'=>8,'graphStudioModule'=>'graph-studio'));
        wp_localize_script('sc-lab-scene-persistence-v01540','SCLabScenePersistenceV01540',array('version'=>self::VERSION,'storageKey'=>'sc-lab-v015212-scenes','handoffKey'=>'sc-lab-v015212-research-object-handoff','maxSavedScenes'=>12,'graphStudioModule'=>'graph-studio','notebookModule'=>'notebook','experimentsModule'=>'experiments','sceneSchema'=>'sc-lab-persisted-4d-scene/1.0','sceneStateSchema'=>'sc-lab-4d-scene-state/1.0','provenanceSchema'=>'sc-lab-4d-scene-provenance/1.0','researchObjectHandoffSchema'=>'sc-lab-research-object-handoff/1.0','canonicalResearchObjectSchema'=>'sc-lab-canonical-research-object/0.105.0','researchObjectType'=>'workspace-snapshot','productRef'=>'product:sustainable-catalyst-lab'));
        wp_localize_script('sc-lab-4d-workspace-v01540','SCLabComputationalWorkspaceV01540',array('version'=>self::VERSION,'healthUrl'=>esc_url_raw(rest_url('sc-lab/v1/workspace/4d/v01530/health')),'assetsUrl'=>esc_url_raw(rest_url('sc-lab/v1/workspace/4d/v01530/assets')),'compareUrl'=>esc_url_raw(rest_url('sc-lab/v1/workspace/4d/v01530/compare')),'sceneStorageKey'=>'sc-lab-v015212-scenes','defaultProjectId'=>is_user_logged_in()?'project:wp-user-'.get_current_user_id():'','nonce'=>wp_create_nonce('wp_rest')));
        wp_localize_script('sc-lab-protocol-notebook-v01540','SCLabProtocolNotebookV01540',array('version'=>self::VERSION,'healthUrl'=>esc_url_raw(rest_url('sc-lab/v1/workspace/reproducible/v01540/health')),'protocolsUrl'=>esc_url_raw(rest_url('sc-lab/v1/workspace/reproducible/v01540/protocols')),'notebooksUrl'=>esc_url_raw(rest_url('sc-lab/v1/workspace/reproducible/v01540/notebooks')),'manifestVerifyUrl'=>esc_url_raw(rest_url('sc-lab/v1/workspace/reproducible/v01540/manifests/verify')),'computeRunUrl'=>esc_url_raw(rest_url('sc-lab/v1/compute/core/run')),'defaultProjectId'=>is_user_logged_in()?'project:wp-user-'.get_current_user_id():'','nonce'=>wp_create_nonce('wp_rest')));
    }
    public static function gate_frontend_assets(){if(!self::is_lab_request()){return;}self::prune_scripts();self::prune_styles();self::enqueue_runtime();}
    public static function gate_footer_scripts(){if(!self::is_lab_request()){return;}self::prune_scripts();self::enqueue_runtime();}
    private static function asset_token($relative){$path=SC_LAB_DIR.ltrim((string)$relative,'/');return self::VERSION.'.'.(is_file($path)?substr(hash_file('sha256',$path),0,16):'missing');}
    private static function state($relative){$path=SC_LAB_DIR.ltrim((string)$relative,'/');return array('exists'=>is_file($path),'bytes'=>is_file($path)?filesize($path):0,'sha256'=>is_file($path)?hash_file('sha256',$path):null);}
    public static function operations_permission(){return is_user_logged_in();}
    private static function settings(){return wp_parse_args((array)get_option('sc_lab_settings',array()),SC_Lab_Admin::defaults());}
    private static function backend_proxy($path,$method='GET',$payload=null,$limit=2097152){
        $settings=self::settings(); if(empty($settings['enable_remote_compute'])||empty($settings['compute_backend_url'])){return new WP_Error('compute_disabled','The Python Compute Core is not enabled or configured.',array('status'=>503));}
        if(!class_exists('SC_Lab_Python_Compute_Core_V0261')){return new WP_Error('compute_proxy_unavailable','The Python Compute Core signing bridge is unavailable.',array('status'=>503));}
        $body=null===$payload?'':wp_json_encode($payload);$url=untrailingslashit($settings['compute_backend_url']).$path;$args=array('method'=>$method,'timeout'=>max(5,min(120,absint($settings['compute_timeout_seconds']))),'redirection'=>2,'sslverify'=>!empty($settings['compute_verify_ssl']),'headers'=>SC_Lab_Python_Compute_Core_V0261::signed_headers($path,$method,$body,$settings),'limit_response_size'=>max(262144,min(8388608,absint($limit))));if(null!==$payload){$args['body']=$body;}
        $response=wp_safe_remote_request($url,$args);if(is_wp_error($response)){return new WP_Error('protocol_notebook_backend_unavailable',$response->get_error_message(),array('status'=>502));}$status=wp_remote_retrieve_response_code($response);$decoded=json_decode(wp_remote_retrieve_body($response),true);if(!is_array($decoded)){$decoded=array('detail'=>'The protocol/notebook backend returned invalid JSON.');$status=502;}return new WP_REST_Response($decoded,$status);
    }
    private static function clean_id($value){return substr(preg_replace('/[^A-Za-z0-9._:-]/','',(string)$value),0,180);}
    private static function clean_tree($value,$depth=0,&$nodes=0){$nodes++;if($nodes>25000||$depth>20){return null;}if(is_null($value)||is_bool($value)||is_int($value)||is_float($value)){return $value;}if(is_string($value)){return substr(wp_check_invalid_utf8($value,true),0,100000);}if(!is_array($value)){return null;}$out=array();$count=0;foreach($value as $k=>$v){if(++$count>5000){break;}$key=is_int($k)?$k:substr(preg_replace('/[^A-Za-z0-9._:-]/','',(string)$k),0,128);if($key===''&&!is_int($k)){continue;}$out[$key]=self::clean_tree($v,$depth+1,$nodes);}return $out;}
    private static function body(WP_REST_Request $r){$b=$r->get_json_params();$n=0;return self::clean_tree(is_array($b)?$b:array(),0,$n);}
    public static function routes(){
        register_rest_route('sc-lab/v1','/frontend-runtime/v01540/health',array('methods'=>'GET','callback'=>array(__CLASS__,'health'),'permission_callback'=>'__return_true'));
        register_rest_route('sc-lab/v1','/workspace/reproducible/v01540/health',array('methods'=>'GET','callback'=>array(__CLASS__,'workspace_health'),'permission_callback'=>'__return_true'));
        register_rest_route('sc-lab/v1','/workspace/reproducible/v01540/protocols',array(array('methods'=>'GET','callback'=>array(__CLASS__,'protocols_list'),'permission_callback'=>array(__CLASS__,'operations_permission')),array('methods'=>'POST','callback'=>array(__CLASS__,'protocol_create'),'permission_callback'=>array(__CLASS__,'operations_permission'))));
        register_rest_route('sc-lab/v1','/workspace/reproducible/v01540/protocols/(?P<id>[A-Za-z0-9._:-]{1,180})',array('methods'=>'GET','callback'=>array(__CLASS__,'protocol_get'),'permission_callback'=>array(__CLASS__,'operations_permission')));
        register_rest_route('sc-lab/v1','/workspace/reproducible/v01540/protocols/(?P<id>[A-Za-z0-9._:-]{1,180})/revisions',array('methods'=>'POST','callback'=>array(__CLASS__,'protocol_revision'),'permission_callback'=>array(__CLASS__,'operations_permission')));
        register_rest_route('sc-lab/v1','/workspace/reproducible/v01540/protocols/(?P<id>[A-Za-z0-9._:-]{1,180})/archive',array('methods'=>'POST','callback'=>array(__CLASS__,'protocol_archive'),'permission_callback'=>array(__CLASS__,'operations_permission')));
        register_rest_route('sc-lab/v1','/workspace/reproducible/v01540/notebooks',array(array('methods'=>'GET','callback'=>array(__CLASS__,'notebooks_list'),'permission_callback'=>array(__CLASS__,'operations_permission')),array('methods'=>'POST','callback'=>array(__CLASS__,'notebook_create'),'permission_callback'=>array(__CLASS__,'operations_permission'))));
        register_rest_route('sc-lab/v1','/workspace/reproducible/v01540/notebooks/(?P<id>[A-Za-z0-9._:-]{1,180})',array('methods'=>'GET','callback'=>array(__CLASS__,'notebook_get'),'permission_callback'=>array(__CLASS__,'operations_permission')));
        register_rest_route('sc-lab/v1','/workspace/reproducible/v01540/notebooks/(?P<id>[A-Za-z0-9._:-]{1,180})/revisions',array('methods'=>'POST','callback'=>array(__CLASS__,'notebook_revision'),'permission_callback'=>array(__CLASS__,'operations_permission')));
        register_rest_route('sc-lab/v1','/workspace/reproducible/v01540/notebooks/(?P<id>[A-Za-z0-9._:-]{1,180})/archive',array('methods'=>'POST','callback'=>array(__CLASS__,'notebook_archive'),'permission_callback'=>array(__CLASS__,'operations_permission')));
        register_rest_route('sc-lab/v1','/workspace/reproducible/v01540/notebooks/(?P<id>[A-Za-z0-9._:-]{1,180})/reproduction-manifest',array('methods'=>'GET','callback'=>array(__CLASS__,'notebook_manifest'),'permission_callback'=>array(__CLASS__,'operations_permission')));
        register_rest_route('sc-lab/v1','/workspace/reproducible/v01540/manifests/verify',array('methods'=>'POST','callback'=>array(__CLASS__,'manifest_verify'),'permission_callback'=>array(__CLASS__,'operations_permission')));
    }
    public static function workspace_health(){return self::backend_proxy('/v1/reproducible-protocol-notebook-workspace/v01540/health');}
    public static function protocols_list(WP_REST_Request $r){$p=self::clean_id($r->get_param('project_id'));if(!$p){return new WP_Error('project_required','Project ID is required.',array('status'=>422));}return self::backend_proxy('/v1/reproducible-protocol-notebook-workspace/v01540/projects/'.rawurlencode($p).'/protocols?limit='.max(1,min(500,absint($r->get_param('limit')?:100))));}
    public static function protocol_create(WP_REST_Request $r){$b=self::body($r);$p=self::clean_id(isset($b['project_id'])?$b['project_id']:'');if(!$p){return new WP_Error('project_required','Project ID is required.',array('status'=>422));}unset($b['project_id']);return self::backend_proxy('/v1/reproducible-protocol-notebook-workspace/v01540/projects/'.rawurlencode($p).'/protocols','POST',$b);}
    public static function protocol_get(WP_REST_Request $r){return self::backend_proxy('/v1/reproducible-protocol-notebook-workspace/v01540/protocols/'.rawurlencode(self::clean_id($r['id'])));}
    public static function protocol_revision(WP_REST_Request $r){return self::backend_proxy('/v1/reproducible-protocol-notebook-workspace/v01540/protocols/'.rawurlencode(self::clean_id($r['id'])).'/revisions','POST',self::body($r));}
    public static function protocol_archive(WP_REST_Request $r){return self::backend_proxy('/v1/reproducible-protocol-notebook-workspace/v01540/protocols/'.rawurlencode(self::clean_id($r['id'])).'/archive','POST',array());}
    public static function notebooks_list(WP_REST_Request $r){$p=self::clean_id($r->get_param('project_id'));if(!$p){return new WP_Error('project_required','Project ID is required.',array('status'=>422));}return self::backend_proxy('/v1/reproducible-protocol-notebook-workspace/v01540/projects/'.rawurlencode($p).'/notebooks?limit='.max(1,min(500,absint($r->get_param('limit')?:100))));}
    public static function notebook_create(WP_REST_Request $r){$b=self::body($r);$p=self::clean_id(isset($b['project_id'])?$b['project_id']:'');if(!$p){return new WP_Error('project_required','Project ID is required.',array('status'=>422));}unset($b['project_id']);return self::backend_proxy('/v1/reproducible-protocol-notebook-workspace/v01540/projects/'.rawurlencode($p).'/notebooks','POST',$b);}
    public static function notebook_get(WP_REST_Request $r){return self::backend_proxy('/v1/reproducible-protocol-notebook-workspace/v01540/notebooks/'.rawurlencode(self::clean_id($r['id'])));}
    public static function notebook_revision(WP_REST_Request $r){return self::backend_proxy('/v1/reproducible-protocol-notebook-workspace/v01540/notebooks/'.rawurlencode(self::clean_id($r['id'])).'/revisions','POST',self::body($r));}
    public static function notebook_archive(WP_REST_Request $r){return self::backend_proxy('/v1/reproducible-protocol-notebook-workspace/v01540/notebooks/'.rawurlencode(self::clean_id($r['id'])).'/archive','POST',array());}
    public static function notebook_manifest(WP_REST_Request $r){return self::backend_proxy('/v1/reproducible-protocol-notebook-workspace/v01540/notebooks/'.rawurlencode(self::clean_id($r['id'])).'/reproduction-manifest');}
    public static function manifest_verify(WP_REST_Request $r){return self::backend_proxy('/v1/reproducible-protocol-notebook-workspace/v01540/manifests/verify','POST',self::body($r));}
    public static function health(){
        $files=array(self::safe_script_relative()=>self::state(self::safe_script_relative()),self::linked_script_relative()=>self::state(self::linked_script_relative()),self::persistence_script_relative()=>self::state(self::persistence_script_relative()),self::workspace_script_relative()=>self::state(self::workspace_script_relative()),self::notebook_script_relative()=>self::state(self::notebook_script_relative()),self::notebook_style_relative()=>self::state(self::notebook_style_relative()),self::recovery_style_relative()=>self::state(self::recovery_style_relative()),'contracts/lab-reproducible-protocol-v01540.schema.json'=>self::state('contracts/lab-reproducible-protocol-v01540.schema.json'),'contracts/lab-computational-notebook-v01540.schema.json'=>self::state('contracts/lab-computational-notebook-v01540.schema.json'),'contracts/lab-notebook-reproduction-manifest-v01540.schema.json'=>self::state('contracts/lab-notebook-reproduction-manifest-v01540.schema.json'));$ok=true;foreach($files as $f){if(empty($f['exists'])||empty($f['bytes'])){$ok=false;}}
        return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'reproducible-protocol-computational-notebook-ready':'incomplete','version'=>self::VERSION,'releaseVersion'=>defined('SC_LAB_RELEASE_VERSION')?SC_LAB_RELEASE_VERSION:self::VERSION,'featureVersion'=>defined('SC_LAB_FEATURE_VERSION')?SC_LAB_FEATURE_VERSION:self::VERSION,'v015213VisualRecoveryBaselineRetained'=>true,'v01530FourDWorkspaceRetained'=>true,'serverBackedProtocols'=>true,'serverBackedComputationalNotebooks'=>true,'immutableProtocolRevisions'=>true,'immutableNotebookRevisions'=>true,'registeredComputeCellSpecifications'=>true,'explicitComputeCellExecution'=>true,'arbitraryCodeExecution'=>false,'reproductionManifests'=>true,'manifestDigestVerification'=>true,'workspaceReferenceBinding'=>true,'computeResultReferenceBinding'=>true,'automaticCompute'=>false,'automaticCoreSubmission'=>false,'automaticScientificValidity'=>false,'restoringNotebookRerunsCompute'=>false,'phpOutputSafetyGateRetained'=>true,'backendBehaviorChanged'=>true,'scientificComputeMethodsChanged'=>false,'scientificBoundary'=>'Protocols and notebooks preserve declared methods, parameters, registered compute-call specifications, result references, workspace references, and immutable revisions. They do not establish evidence, causality, statistical significance, calibration, or scientific validity, and they do not execute arbitrary code.','files'=>$files));
    }
}
