<?php
/** Sustainable Catalyst Lab v0.37.0 Reproducibility Packages and Research Publication Studio. */
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Publication_Studio_V0370 {
 const VERSION='0.37.0'; private static $initialized=false;
 public static function init(){if(self::$initialized){return;}self::$initialized=true;add_action('rest_api_init',array(__CLASS__,'routes'));add_filter('sc_lab_module_aliases_v02631',array(__CLASS__,'aliases'));add_filter('sc_lab_panel_aliases_v02631',array(__CLASS__,'aliases'));add_shortcode('sc_lab_publication_studio',array(__CLASS__,'shortcode'));add_shortcode('sc_lab_reproducibility_packages',array(__CLASS__,'shortcode'));}
 public static function aliases($aliases){$aliases=is_array($aliases)?$aliases:array();foreach(array('publication-studio','research-publication','reproducibility-packages','reproducibility-package','publication') as $alias){$aliases[$alias]='publication-studio';}return $aliases;}
 public static function shortcode(){return do_shortcode('[sc_lab_app module="publication-studio"]');}
 public static function routes(){register_rest_route('sc-lab/v1','/publication-studio/v0370/health',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'health'),'permission_callback'=>'__return_true'));register_rest_route('sc-lab/v1','/publication-studio/v0370/schema',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'schema'),'permission_callback'=>'__return_true'));}
 private static function state($relative){$path=SC_LAB_DIR.$relative;return array('exists'=>is_file($path),'sha256'=>is_file($path)?hash_file('sha256',$path):null);}
 public static function schema(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'packageSchema'=>'sc-lab-reproducibility-package/0.37.0','publicationSchema'=>'sc-lab-research-publication/0.37.0','verificationSchema'=>'sc-lab-reproducibility-verification/0.37.0','exportSchema'=>'sc-lab-publication-export/0.37.0','eventSchema'=>'sc-lab-publication-event/0.37.0','immutableSealedPackages'=>true,'citationCff'=>true,'scientificSignoffGate'=>true,'embeddedRestrictedData'=>false,'arbitraryCode'=>false));}
 public static function health(){$required=array('assets/js/modules/publication-studio-v0370.js','assets/css/sc-lab-publication-studio-v0370.css','contracts/publication-studio-policy-v0370.json','contracts/reproducibility-package-v0370.schema.json','contracts/research-publication-v0370.schema.json','contracts/reproducibility-verification-v0370.schema.json','contracts/publication-export-v0370.schema.json','contracts/publication-event-v0370.schema.json','includes/class-sc-lab-publication-studio-v0370.php');$files=array();$ok=true;foreach($required as $relative){$files[$relative]=self::state($relative);if(empty($files[$relative]['exists'])){$ok=false;}}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'ready':'incomplete','version'=>self::VERSION,'release'=>defined('SC_LAB_VERSION')?SC_LAB_VERSION:null,'architecture'=>'workspace-governed-reproducibility-packages-and-research-publication-studio','databaseSchemaVersion'=>1,'immutableSealedPackages'=>true,'publicationRendering'=>true,'scientificSignoffGate'=>true,'embeddedRestrictedData'=>false,'arbitraryCode'=>false,'hardDelete'=>false,'files'=>$files,'time'=>gmdate('c')));}
}
