<?php
/** Sustainable Catalyst Lab v0.41.0 Model Studio and Scientific Visualization Foundation. */
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Model_Studio_V0410 {
    const VERSION='0.41.0'; private static $initialized=false;
    public static function init(){if(self::$initialized){return;}self::$initialized=true;add_action('rest_api_init',array(__CLASS__,'routes'));add_filter('sc_lab_module_aliases_v02631',array(__CLASS__,'aliases'));add_filter('sc_lab_panel_aliases_v02631',array(__CLASS__,'aliases'));add_shortcode('sc_lab_model_studio',array(__CLASS__,'shortcode'));}
    public static function aliases($aliases){$aliases=is_array($aliases)?$aliases:array();foreach(array('model-studio','scientific-model-studio','model-builder','scientific-modeling') as $alias){$aliases[$alias]='model-studio';}return $aliases;}
    public static function shortcode(){return do_shortcode('[sc_lab_app module="model-studio"]');}
    public static function routes(){register_rest_route('sc-lab/v1','/model-studio/v0410/health',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'health'),'permission_callback'=>'__return_true'));register_rest_route('sc-lab/v1','/model-studio/v0410/schema',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'schema'),'permission_callback'=>'__return_true'));}
    private static function file_state($relative){$path=SC_LAB_DIR.$relative;return array('exists'=>is_file($path),'sha256'=>is_file($path)?hash_file('sha256',$path):null);}
    public static function schema(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'modelSchema'=>'sc-lab-model-studio-model/0.41.0','graphSchema'=>'sc-lab-scientific-graph/0.41.0','resultSchema'=>'sc-lab-model-studio-result/0.41.0','sharedVisualizationEngine'=>'SCLabScientificVisualizationEngineV0410','arbitraryCode'=>false,'arbitraryFormulaExecution'=>false));}
    public static function health(){$required=array('backend/app/model_studio.py','backend/tests/test_model_studio_v0410.py','assets/js/modules/model-studio-v0410.js','assets/js/modules/scientific-visualization-engine-v0410.js','assets/css/sc-lab-model-studio-v0410.css','assets/css/sc-lab-scientific-visualization-engine-v0410.css','contracts/model-studio-policy-v0410.json','contracts/model-studio-model-v0410.schema.json','contracts/scientific-graph-v0410.schema.json','contracts/model-studio-result-v0410.schema.json');$files=array();$ok=true;foreach($required as $relative){$files[$relative]=self::file_state($relative);if(empty($files[$relative]['exists'])){$ok=false;}}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'model-studio-foundation-ready':'incomplete','version'=>self::VERSION,'release'=>defined('SC_LAB_VERSION')?SC_LAB_VERSION:null,'sharedVisualizationEngine'=>true,'registeredModelHandoffs'=>array('model-calibration','design-studies','ensemble-uncertainty','model-registry','workbench'),'arbitraryCode'=>false,'arbitraryFormulaExecution'=>false,'files'=>$files,'time'=>gmdate('c')));}
}
