<?php
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Exploratory_Data_Analysis_Studio_V01200 {
 const VERSION='0.120.0'; const ENGINE_VERSION='4.0.0'; const SCHEMA='sc-lab-exploratory-data-analysis-studio/0.120.0';
 public static function init(){ add_action('rest_api_init',array(__CLASS__,'routes')); }
 public static function routes(){ $ns='sc-lab/v1/analysis/v01200'; foreach(array('health','manifest','schema','catalog') as $r){register_rest_route($ns,'/'.$r,array('methods'=>'GET','callback'=>array(__CLASS__,$r),'permission_callback'=>'__return_true'));}}
 private static function state($r){$p=SC_LAB_DIR.$r;return array('exists'=>is_file($p),'sha256'=>is_file($p)?hash_file('sha256',$p):null);}
 public static function schema(){return rest_ensure_response(array('ok'=>true,'schema'=>self::SCHEMA,'version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'maxRows'=>50000,'maxColumns'=>256,'apiRouteCount'=>20));}
 public static function catalog(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'correlationMethods'=>array('pearson','spearman'),'outlierMethods'=>array('iqr','modified-z','zscore'),'transformations'=>array('center','standardize','minmax','log1p','sqrt','winsorize'),'analysisFamilies'=>array('profile','missingness','distribution','correlation','group-comparison','outlier','relationship','transformation-preview','pca')));}
 public static function manifest(){return rest_ensure_response(array('ok'=>true,'status'=>'exploratory-data-analysis-studio-ready','version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'sourceRowsImmutable'=>true,'descriptiveStatistics'=>true,'missingnessAnalysis'=>true,'distributionAnalysis'=>true,'correlationAnalysis'=>true,'groupComparison'=>true,'robustOutlierFlags'=>true,'transformationPreview'=>true,'pcaExploration'=>true,'reproducibleSnapshots'=>true,'publicationVisualPlans'=>true,'automaticSourceMutation'=>false,'automaticHypothesisConfirmation'=>false,'automaticSignificanceClaims'=>false,'automaticCausalInference'=>false,'automaticScientificValidityCertification'=>false,'automaticCoreSubmission'=>false,'determineTruth'=>false));}
 public static function health(){ $req=array('contracts/exploratory-data-analysis-studio-v01200.schema.json','contracts/exploratory-data-analysis-studio-policy-v01200.json','includes/class-sc-lab-exploratory-data-analysis-studio-v01200.php','assets/js/modules/exploratory-data-analysis-studio-v01200.js','assets/css/sc-lab-exploratory-data-analysis-studio-v01200.css');$files=array();$ok=true;foreach($req as $r){$files[$r]=self::state($r);if(empty($files[$r]['exists']))$ok=false;}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'exploratory-data-analysis-studio-ready':'incomplete','version'=>self::VERSION,'labReleaseVersion'=>defined('SC_LAB_RELEASE_VERSION')?SC_LAB_RELEASE_VERSION:self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'analysisFamilyCount'=>9,'correlationMethodCount'=>2,'outlierMethodCount'=>3,'transformationCount'=>6,'apiRouteCount'=>20,'files'=>$files,'automaticSourceMutation'=>false,'automaticHypothesisConfirmation'=>false,'automaticScientificValidityCertification'=>false,'time'=>gmdate('c')));}
}
SC_Lab_Exploratory_Data_Analysis_Studio_V01200::init();
