<?php
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Method_Selection_Intelligence_V01320 {
 const VERSION='0.132.0'; const ENGINE_VERSION='13.0.0'; const SCHEMA='sc-lab-method-selection-intelligence/0.132.0';
 public static function init(){ add_action('rest_api_init',array(__CLASS__,'routes')); }
 public static function routes(){ $ns='sc-lab/v1/analysis/v01320'; foreach(array('health','manifest','schema','catalog') as $r){register_rest_route($ns,'/'.$r,array('methods'=>'GET','callback'=>array(__CLASS__,$r),'permission_callback'=>'__return_true'));}}
 private static function state($r){$p=SC_LAB_DIR.$r;return array('exists'=>is_file($p),'sha256'=>is_file($p)?hash_file('sha256',$p):null);}
 public static function schema(){return rest_ensure_response(array('ok'=>true,'schema'=>self::SCHEMA,'version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'maxMethods'=>5000,'maxRequirements'=>20000,'maxAssumptions'=>20000,'apiRouteCount'=>37));}
 public static function catalog(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'methodFamilyCount'=>22,'figureFamilyCount'=>12,'methodCatalogCount'=>20,'researcherSelectionRequired'=>true,'automaticMethodSelection'=>false,'automaticMethodRanking'=>false,'automaticTruthDetermination'=>false,'automaticCoreSubmission'=>false));}
 public static function manifest(){return rest_ensure_response(array('ok'=>true,'status'=>'method-selection-intelligence-ready','version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'transparentEligibilityReasoning'=>true,'questionHypothesisAlignment'=>true,'dataDesignEstimandAlignment'=>true,'assumptionRequirementGapAnalysis'=>true,'diagnosticValidationPlanning'=>true,'researcherSelectionRequired'=>true,'automaticMethodSelection'=>false,'automaticMethodRanking'=>false,'automaticHypothesisSelection'=>false,'automaticScientificValidityCertification'=>false,'automaticCoreSubmission'=>false,'determineTruth'=>false));}
 public static function health(){ $req=array('contracts/method-selection-intelligence-v01320.schema.json','contracts/method-selection-intelligence-policy-v01320.json','includes/class-sc-lab-method-selection-intelligence-v01320.php','assets/js/modules/method-selection-intelligence-v01320.js','assets/css/sc-lab-method-selection-intelligence-v01320.css');$files=array();$ok=true;foreach($req as $r){$files[$r]=self::state($r);if(empty($files[$r]['exists']))$ok=false;}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'method-selection-intelligence-ready':'incomplete','version'=>self::VERSION,'labReleaseVersion'=>defined('SC_LAB_RELEASE_VERSION')?SC_LAB_RELEASE_VERSION:self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'methodFamilyCount'=>22,'figureFamilyCount'=>12,'methodCatalogCount'=>20,'apiRouteCount'=>37,'files'=>$files,'researcherSelectionRequired'=>true,'automaticMethodSelection'=>false,'automaticMethodRanking'=>false,'automaticScientificValidityCertification'=>false,'automaticCoreSubmission'=>false,'time'=>gmdate('c')));}
}
SC_Lab_Method_Selection_Intelligence_V01320::init();
