<?php
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Causal_Research_Studio_V01250 {
 const VERSION='0.125.0'; const ENGINE_VERSION='6.0.0'; const SCHEMA='sc-lab-causal-research-studio/0.125.0';
 public static function init(){ add_action('rest_api_init',array(__CLASS__,'routes')); }
 public static function routes(){ $ns='sc-lab/v1/analysis/v01250'; foreach(array('health','manifest','schema','catalog') as $r){register_rest_route($ns,'/'.$r,array('methods'=>'GET','callback'=>array(__CLASS__,$r),'permission_callback'=>'__return_true'));}}
 private static function state($r){$p=SC_LAB_DIR.$r;return array('exists'=>is_file($p),'sha256'=>is_file($p)?hash_file('sha256',$p):null);}
 public static function schema(){return rest_ensure_response(array('ok'=>true,'schema'=>self::SCHEMA,'version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'maxRows'=>20000,'maxCovariates'=>64,'maxDagNodes'=>128,'maxDagEdges'=>512,'apiRouteCount'=>28));}
 public static function catalog(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'methodFamilies'=>array('dag-adjustment','difference-in-differences','interrupted-time-series','inverse-probability-weighting','nearest-neighbor-matching','propensity-score','regression-discontinuity','synthetic-control'),'figureFamilyCount'=>12));}
 public static function manifest(){return rest_ensure_response(array('ok'=>true,'status'=>'causal-research-studio-ready','version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'dagWorkflows'=>true,'propensityScores'=>true,'matching'=>true,'weighting'=>true,'differenceInDifferences'=>true,'interruptedTimeSeries'=>true,'regressionDiscontinuity'=>true,'syntheticControl'=>true,'humanCausalReviewRequired'=>true,'automaticCausalProof'=>false,'automaticAssumptionSatisfaction'=>false,'automaticMethodSelection'=>false,'automaticCovariateSelection'=>false,'automaticScientificValidityCertification'=>false,'automaticCoreSubmission'=>false,'determineTruth'=>false));}
 public static function health(){ $req=array('contracts/causal-research-studio-v01250.schema.json','contracts/causal-research-studio-policy-v01250.json','includes/class-sc-lab-causal-research-studio-v01250.php','assets/js/modules/causal-research-studio-v01250.js','assets/css/sc-lab-causal-research-studio-v01250.css');$files=array();$ok=true;foreach($req as $r){$files[$r]=self::state($r);if(empty($files[$r]['exists']))$ok=false;}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'causal-research-studio-ready':'incomplete','version'=>self::VERSION,'labReleaseVersion'=>defined('SC_LAB_RELEASE_VERSION')?SC_LAB_RELEASE_VERSION:self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'methodFamilyCount'=>8,'figureFamilyCount'=>12,'apiRouteCount'=>28,'files'=>$files,'humanCausalReviewRequired'=>true,'automaticCausalProof'=>false,'automaticAssumptionSatisfaction'=>false,'automaticMethodSelection'=>false,'automaticScientificValidityCertification'=>false,'time'=>gmdate('c')));}
}
SC_Lab_Causal_Research_Studio_V01250::init();
