<?php
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Statistical_Modeling_Diagnostics_Studio_V01210 {
 const VERSION='0.121.0'; const ENGINE_VERSION='4.1.0'; const SCHEMA='sc-lab-statistical-modeling-diagnostics-studio/0.121.0';
 public static function init(){ add_action('rest_api_init',array(__CLASS__,'routes')); }
 public static function routes(){ $ns='sc-lab/v1/analysis/v01210'; foreach(array('health','manifest','schema','catalog') as $r){register_rest_route($ns,'/'.$r,array('methods'=>'GET','callback'=>array(__CLASS__,$r),'permission_callback'=>'__return_true'));}}
 private static function state($r){$p=SC_LAB_DIR.$r;return array('exists'=>is_file($p),'sha256'=>is_file($p)?hash_file('sha256',$p):null);}
 public static function schema(){return rest_ensure_response(array('ok'=>true,'schema'=>self::SCHEMA,'version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'maxRows'=>5000,'maxFeatures'=>40,'apiRouteCount'=>18));}
 public static function catalog(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'families'=>array('gaussian','binomial-logit','poisson-log'),'estimators'=>array('ols','weighted-least-squares','huber','ridge','lasso','elastic-net','glm'),'diagnosticFamilies'=>array('residual-summary','normality','heteroskedasticity','independence','multicollinearity','influence','observed-vs-predicted','calibration','classification','deviance','dispersion')));}
 public static function manifest(){return rest_ensure_response(array('ok'=>true,'status'=>'statistical-modeling-diagnostics-studio-ready','version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'gaussianModels'=>true,'robustRegression'=>true,'regularizedRegression'=>true,'binomialGlm'=>true,'poissonGlm'=>true,'residualDiagnostics'=>true,'influenceDiagnostics'=>true,'calibrationDiagnostics'=>true,'crossValidation'=>true,'sourceRowsImmutable'=>true,'automaticFeatureSelection'=>false,'automaticModelSelection'=>false,'automaticSignificanceLabels'=>false,'automaticCausalInference'=>false,'automaticScientificValidityCertification'=>false,'automaticCoreSubmission'=>false,'determineTruth'=>false));}
 public static function health(){ $req=array('contracts/statistical-modeling-diagnostics-studio-v01210.schema.json','contracts/statistical-modeling-diagnostics-studio-policy-v01210.json','includes/class-sc-lab-statistical-modeling-diagnostics-studio-v01210.php','assets/js/modules/statistical-modeling-diagnostics-studio-v01210.js','assets/css/sc-lab-statistical-modeling-diagnostics-studio-v01210.css');$files=array();$ok=true;foreach($req as $r){$files[$r]=self::state($r);if(empty($files[$r]['exists']))$ok=false;}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'statistical-modeling-diagnostics-studio-ready':'incomplete','version'=>self::VERSION,'labReleaseVersion'=>defined('SC_LAB_RELEASE_VERSION')?SC_LAB_RELEASE_VERSION:self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'familyCount'=>3,'estimatorCount'=>7,'diagnosticFamilyCount'=>11,'apiRouteCount'=>18,'files'=>$files,'automaticFeatureSelection'=>false,'automaticModelSelection'=>false,'automaticSignificanceLabels'=>false,'automaticCausalInference'=>false,'automaticScientificValidityCertification'=>false,'time'=>gmdate('c')));}
}
SC_Lab_Statistical_Modeling_Diagnostics_Studio_V01210::init();
