<?php
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Scientific_Figure_Intelligence_Automatic_Layout_V01190 {
 const VERSION='0.119.0'; const ENGINE_VERSION='3.5.0'; const SCHEMA='sc-lab-scientific-figure-intelligence-automatic-layout/0.119.0';
 public static function init(){ add_action('rest_api_init',array(__CLASS__,'routes')); }
 public static function routes(){ $ns='sc-lab/v1/visualization/v01190'; foreach(array('health','manifest','schema','catalog') as $r){register_rest_route($ns,'/'.$r,array('methods'=>'GET','callback'=>array(__CLASS__,$r),'permission_callback'=>'__return_true'));}}
 private static function state($r){$p=SC_LAB_DIR.$r;return array('exists'=>is_file($p),'sha256'=>is_file($p)?hash_file('sha256',$p):null);}
 public static function schema(){return rest_ensure_response(array('ok'=>true,'schema'=>self::SCHEMA,'version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'panelLimit'=>64,'annotationLimit'=>1000,'apiRouteCount'=>21));}
 public static function catalog(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'layoutModes'=>array('single','two-column','grid','vertical-strip','horizontal-strip','focus-context','small-multiples'),'legendPositions'=>array('inside-top-right','inside-top-left','outside-right','below','above','none'),'labelStrategies'=>array('horizontal','rotate-30','rotate-45','wrap','stagger','outside','declared'),'collisionPolicies'=>array('displace','leader-line','stack','preserve-and-report')));}
 public static function manifest(){return rest_ensure_response(array('ok'=>true,'status'=>'scientific-figure-intelligence-automatic-layout-ready','version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'deterministicLayoutPlanning'=>true,'axisLabelStrategy'=>true,'legendPlacement'=>true,'annotationCollisionAvoidance'=>true,'panelGridPlanning'=>true,'responsiveReflow'=>true,'printLayout'=>true,'qualityAudit'=>true,'accessibilityAudit'=>true,'layoutSnapshots'=>true,'coreVisualBridge'=>true,'automaticDataTransformation'=>false,'automaticDomainInference'=>false,'automaticScaleInference'=>false,'automaticScientificEncodingChanges'=>false,'automaticEvidenceWeighting'=>false,'automaticClaimInference'=>false,'automaticCoreSubmission'=>false,'scientificValidityCertified'=>false));}
 public static function health(){ $req=array('contracts/scientific-figure-intelligence-automatic-layout-v01190.schema.json','contracts/scientific-figure-intelligence-automatic-layout-policy-v01190.json','includes/class-sc-lab-scientific-figure-intelligence-automatic-layout-v01190.php','assets/js/modules/scientific-figure-intelligence-automatic-layout-v01190.js','assets/css/sc-lab-scientific-figure-intelligence-automatic-layout-v01190.css');$files=array();$ok=true;foreach($req as $r){$files[$r]=self::state($r);if(empty($files[$r]['exists']))$ok=false;}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'scientific-figure-intelligence-automatic-layout-ready':'incomplete','version'=>self::VERSION,'labReleaseVersion'=>defined('SC_LAB_RELEASE_VERSION')?SC_LAB_RELEASE_VERSION:self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'layoutModeCount'=>7,'legendPositionCount'=>6,'labelStrategyCount'=>7,'collisionPolicyCount'=>4,'files'=>$files,'automaticScientificEncodingChanges'=>false,'automaticCoreSubmission'=>false,'scientificValidityCertified'=>false,'time'=>gmdate('c')));}
}
SC_Lab_Scientific_Figure_Intelligence_Automatic_Layout_V01190::init();
