<?php
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Spatial_Spatiotemporal_Research_Studio_V01260 {
 const VERSION='0.126.0'; const ENGINE_VERSION='7.0.0'; const SCHEMA='sc-lab-spatial-spatiotemporal-research-studio/0.126.0';
 public static function init(){ add_action('rest_api_init',array(__CLASS__,'routes')); }
 public static function routes(){ $ns='sc-lab/v1/analysis/v01260'; foreach(array('health','manifest','schema','catalog') as $r){register_rest_route($ns,'/'.$r,array('methods'=>'GET','callback'=>array(__CLASS__,$r),'permission_callback'=>'__return_true'));}}
 private static function state($r){$p=SC_LAB_DIR.$r;return array('exists'=>is_file($p),'sha256'=>is_file($p)?hash_file('sha256',$p):null);}
 public static function schema(){return rest_ensure_response(array('ok'=>true,'schema'=>self::SCHEMA,'version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'maxRows'=>50000,'maxLocations'=>10000,'maxNeighbors'=>64,'maxRasterCells'=>1048576,'apiRouteCount'=>28));}
 public static function catalog(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'methodFamilyCount'=>12,'figureFamilyCount'=>14,'retainedSpatialEngine'=>'spatial-geospatial-raster-v0.80.0','automaticReprojection'=>false,'automaticSpatialJoin'=>false,'automaticCausalInterpretation'=>false));}
 public static function manifest(){return rest_ensure_response(array('ok'=>true,'status'=>'spatial-spatiotemporal-research-studio-ready','version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'vectorResearch'=>true,'rasterResearch'=>true,'spatialStatistics'=>true,'spatiotemporalAnalysis'=>true,'trajectoryAnalysis'=>true,'explicitCRSRequired'=>true,'automaticReprojection'=>false,'automaticBandwidthSelection'=>false,'automaticSpatialJoin'=>false,'automaticSignificanceLabels'=>false,'automaticCausalInterpretation'=>false,'automaticScientificValidityCertification'=>false,'automaticCoreSubmission'=>false,'determineTruth'=>false));}
 public static function health(){ $req=array('contracts/spatial-spatiotemporal-research-studio-v01260.schema.json','contracts/spatial-spatiotemporal-research-studio-policy-v01260.json','includes/class-sc-lab-spatial-spatiotemporal-research-studio-v01260.php','assets/js/modules/spatial-spatiotemporal-research-studio-v01260.js','assets/css/sc-lab-spatial-spatiotemporal-research-studio-v01260.css');$files=array();$ok=true;foreach($req as $r){$files[$r]=self::state($r);if(empty($files[$r]['exists']))$ok=false;}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'spatial-spatiotemporal-research-studio-ready':'incomplete','version'=>self::VERSION,'labReleaseVersion'=>defined('SC_LAB_RELEASE_VERSION')?SC_LAB_RELEASE_VERSION:self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'methodFamilyCount'=>12,'figureFamilyCount'=>14,'apiRouteCount'=>28,'files'=>$files,'automaticReprojection'=>false,'automaticSpatialJoin'=>false,'automaticCausalInterpretation'=>false,'automaticScientificValidityCertification'=>false,'time'=>gmdate('c')));}
}
SC_Lab_Spatial_Spatiotemporal_Research_Studio_V01260::init();
