<?php
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Scientific_Research_Project_Studio_V01300 {
 const VERSION='0.130.0'; const ENGINE_VERSION='11.0.0'; const SCHEMA='sc-lab-scientific-research-project-studio/0.130.0';
 public static function init(){ add_action('rest_api_init',array(__CLASS__,'routes')); }
 public static function routes(){ $ns='sc-lab/v1/analysis/v01300'; foreach(array('health','manifest','schema','catalog') as $r){register_rest_route($ns,'/'.$r,array('methods'=>'GET','callback'=>array(__CLASS__,$r),'permission_callback'=>'__return_true'));}}
 private static function state($r){$p=SC_LAB_DIR.$r;return array('exists'=>is_file($p),'sha256'=>is_file($p)?hash_file('sha256',$p):null);}
 public static function schema(){return rest_ensure_response(array('ok'=>true,'schema'=>self::SCHEMA,'version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'maxComponents'=>20000,'maxRelationships'=>50000,'maxWorkstreams'=>500,'maxMilestones'=>5000,'apiRouteCount'=>32));}
 public static function catalog(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'methodFamilyCount'=>18,'figureFamilyCount'=>16,'referenceFirst'=>true,'automaticDomainObjectMutation'=>false,'automaticScientificValidityCertification'=>false,'automaticCoreSubmission'=>false));}
 public static function manifest(){return rest_ensure_response(array('ok'=>true,'status'=>'scientific-research-project-studio-ready','version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'unifiedProjectWorkspace'=>true,'crossProductReferences'=>true,'provenanceAggregation'=>true,'reproducibleSnapshots'=>true,'publicationPlanning'=>true,'domainObjectsRemainAuthoritative'=>true,'automaticDomainObjectMutation'=>false,'automaticScientificInference'=>false,'automaticScientificValidityCertification'=>false,'automaticCoreSubmission'=>false,'determineTruth'=>false));}
 public static function health(){ $req=array('contracts/scientific-research-project-studio-v01300.schema.json','contracts/scientific-research-project-studio-policy-v01300.json','includes/class-sc-lab-scientific-research-project-studio-v01300.php','assets/js/modules/scientific-research-project-studio-v01300.js','assets/css/sc-lab-scientific-research-project-studio-v01300.css');$files=array();$ok=true;foreach($req as $r){$files[$r]=self::state($r);if(empty($files[$r]['exists']))$ok=false;}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'scientific-research-project-studio-ready':'incomplete','version'=>self::VERSION,'labReleaseVersion'=>defined('SC_LAB_RELEASE_VERSION')?SC_LAB_RELEASE_VERSION:self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'methodFamilyCount'=>18,'figureFamilyCount'=>16,'apiRouteCount'=>32,'files'=>$files,'referenceFirst'=>true,'automaticDomainObjectMutation'=>false,'automaticScientificValidityCertification'=>false,'automaticCoreSubmission'=>false,'time'=>gmdate('c')));}
}
SC_Lab_Scientific_Research_Project_Studio_V01300::init();
