<?php
if(!defined('ABSPATH'))exit;
final class SC_Lab_Genomic_Validation_REST_V0243{
 const VERSION='0.24.3';const NAMESPACE='sc-lab/v1';
 public static function boot(){add_action('rest_api_init',array(__CLASS__,'routes'));}
 public static function contract(){$p=dirname(__DIR__).'/contracts/genomic-validation-sequence-provenance-v0243.json';$d=json_decode(file_get_contents($p),true);return is_array($d)?$d:array();}
 private static function norm($v){return strtoupper((string)preg_replace('/\s+/','',(string)($v??'')));}
 private static function finite($v,$l){if(!is_numeric($v)||!is_finite((float)$v))throw new InvalidArgumentException($l.' must be numerical and finite.');return(float)$v;}
 private static function profile($id){foreach(self::contract()['profiles'] as $p)if($p['id']===$id)return$p;throw new InvalidArgumentException('Unknown validation profile: '.$id);}
 private static function check($id,$label,$value,$op,$limit,$passed,$unit=''){return array('id'=>$id,'label'=>$label,'value'=>$value,'operator'=>$op,'limit'=>$limit,'unit'=>$unit,'passed'=>(bool)$passed,'status'=>$passed?'pass':'fail');}
 public static function canonical_json($value){$sort=function(&$v)use(&$sort){if(!is_array($v))return;if(array_keys($v)!==range(0,count($v)-1))ksort($v,SORT_STRING);foreach($v as&$x)$sort($x);};$copy=$value;$sort($copy);return json_encode($copy,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_PRESERVE_ZERO_FRACTION|JSON_THROW_ON_ERROR);}
 public static function fingerprint($value){return hash('sha256',self::canonical_json($value));}
 public static function evaluate($id,$rows,$overrides=array()){
  $p=self::profile($id);if(!is_array($rows)||!count($rows))throw new InvalidArgumentException('Validation requires at least one row.');foreach($rows as$index=>$row)foreach($p['required'] as$key)if(!array_key_exists($key,$row))throw new InvalidArgumentException('Required field '.$key.' is missing from row '.($index+1).'.');
  $L=array_merge($p['thresholds'],is_array($overrides)?$overrides:array());$metrics=array();$checks=array();
  if($id==='sequence-record-integrity'){$ids=array();$invalid=0;foreach($rows as$r){$sid=trim((string)($r['sequenceId']??''));$s=self::norm($r['sequence']??'');$a=strtoupper((string)($r['alphabet']??''));$allowed=in_array($a,array('DNA','DNA-IUPAC'),true)?'ACGTN':(in_array($a,array('RNA','RNA-IUPAC'),true)?'ACGUN':'');$ids[]=$sid;if($sid===''||$s===''||$allowed===''||strlen(preg_replace('/['.$allowed.']/','',$s)))$invalid++;}$duplicates=count($ids)-count(array_unique($ids));$metrics=array('recordCount'=>count($rows),'invalidRecordCount'=>$invalid,'duplicateIdCount'=>$duplicates);$checks=array(self::check('invalid-records','Invalid sequence records',$invalid,'<=',$L['maximumInvalidRecords'],$invalid<=$L['maximumInvalidRecords']),self::check('duplicate-identifiers','Duplicate sequence identifiers',$duplicates,'<=',$L['maximumDuplicateIds'],$duplicates<=$L['maximumDuplicateIds']));}
  elseif($id==='metadata-linkage'){$seq=array();$mids=array();$missing=0;foreach($rows as$r){$seq[(string)$r['sequenceId']]=true;$mid=trim((string)($r['metadataId']??''));if($mid==='')$missing++;else$mids[]=$mid;}$unmatched=0;foreach($mids as$m)if(!isset($seq[$m]))$unmatched++;$metrics=array('sequenceRecordCount'=>count($rows),'missingMetadataCount'=>$missing,'unmatchedMetadataCount'=>$unmatched);$checks=array(self::check('missing-metadata','Missing metadata links',$missing,'<=',$L['maximumMissingMetadata'],$missing<=$L['maximumMissingMetadata']),self::check('unmatched-metadata','Unmatched metadata identifiers',$unmatched,'<=',$L['maximumUnmatchedMetadata'],$unmatched<=$L['maximumUnmatchedMetadata']));}
  elseif($id==='reference-coordinate-context'){$missing=0;$bad=0;foreach($rows as$r){foreach(array('referenceBuild','coordinateSystem','contig')as$k)if(trim((string)($r[$k]??''))===''){$missing++;break;}if(self::finite($r['position'],'position')<(float)$L['minimumPosition'])$bad++;}$metrics=array('recordCount'=>count($rows),'missingContextCount'=>$missing,'invalidPositionCount'=>$bad);$checks=array(self::check('missing-context','Missing reference context',$missing,'<=',$L['maximumMissingContext'],$missing<=$L['maximumMissingContext']),self::check('minimum-position','Positions below minimum',$bad,'=',0,$bad===0));}
  elseif($id==='sequence-quality'){$failures=0;$summaries=array();foreach($rows as$r){$s=self::norm($r['sequence']);$length=strlen($s);$valid=$length-strlen(preg_replace('/[ACGTUN]/','',$s));$amb=strlen(preg_replace('/[ACGTU]/','',$s));$vp=$length?$valid/$length*100:0;$ap=$length?$amb/$length*100:100;$passed=$length>=(float)$L['minimumLength']&&$vp>=(float)$L['minimumValidBasePercent']&&$ap<=(float)$L['maximumAmbiguousPercent'];if(!$passed)$failures++;$summaries[]=array('sequenceId'=>$r['sequenceId'],'length'=>$length,'validBasePercent'=>$vp,'ambiguousPercent'=>$ap,'passed'=>$passed);}$metrics=array('recordCount'=>count($rows),'failureCount'=>$failures,'sequences'=>$summaries);$checks=array(self::check('sequence-quality-failures','Sequences failing quality criteria',$failures,'=',0,$failures===0));}
  elseif($id==='variant-record-integrity'){$invalid=0;$vars=array();foreach($rows as$r){$ref=self::norm($r['referenceBase']);$alt=self::norm($r['alternateBase']);$pos=self::finite($r['position'],'position');$depth=self::finite($r['readDepth'],'readDepth');$ad=self::finite($r['alternateDepth'],'alternateDepth');$passed=strlen($ref)===1&&strlen($alt)===1&&strpos('ACGT',$ref)!==false&&strpos('ACGT',$alt)!==false&&$ref!==$alt&&$pos>=1&&$depth>=(float)$L['minimumReadDepth']&&$ad>=0&&$ad<=$depth;if(!$passed)$invalid++;$vars[]=array('variantId'=>$r['variantId'],'passed'=>$passed,'alleleFraction'=>$depth?$ad/$depth:null);}$metrics=array('variantCount'=>count($rows),'invalidVariantCount'=>$invalid,'variants'=>$vars);$checks=array(self::check('invalid-variants','Invalid variant records',$invalid,'<=',$L['maximumInvalidVariants'],$invalid<=$L['maximumInvalidVariants']));}
  elseif($id==='analysis-reproducibility'){$incomplete=0;foreach($rows as$r){foreach($p['required'] as$k)if(trim((string)($r[$k]??''))===''){$incomplete++;break;}}$metrics=array('stepCount'=>count($rows),'incompleteStepCount'=>$incomplete);$checks=array(self::check('incomplete-steps','Incomplete reproducibility records',$incomplete,'<=',$L['maximumIncompleteSteps'],$incomplete<=$L['maximumIncompleteSteps']));}
  elseif($id==='annotation-evidence'){$invalid=0;$evidence=0;foreach($rows as$r){$start=self::finite($r['start'],'start');$end=self::finite($r['end'],'end');$has=trim((string)($r['evidence']??''))!=='';if($has)$evidence++;if(trim((string)($r['annotationId']??''))===''||trim((string)($r['type']??''))===''||$start<0||$end<$start||!$has)$invalid++;}$coverage=$evidence/count($rows)*100;$metrics=array('annotationCount'=>count($rows),'invalidAnnotationCount'=>$invalid,'evidenceCoveragePercent'=>$coverage);$checks=array(self::check('invalid-annotations','Invalid annotations',$invalid,'<=',$L['maximumInvalidAnnotations'],$invalid<=$L['maximumInvalidAnnotations']),self::check('annotation-evidence','Annotation evidence coverage',$coverage,'>=',$L['minimumEvidenceCoveragePercent'],$coverage>=$L['minimumEvidenceCoveragePercent'],'%'));}
  elseif($id==='release-readiness'){$failed=0;$evidence=0;foreach($rows as$r){$status=strtolower((string)$r['status']);$critical=in_array(strtolower((string)$r['critical']),array('1','true','yes','critical'),true);$complete=in_array($status,array('pass','passed','closed','complete','accepted'),true);if($critical&&!$complete)$failed++;if(trim((string)($r['evidence']??''))!=='')$evidence++;}$coverage=$evidence/count($rows)*100;$metrics=array('checkCount'=>count($rows),'failedCriticalCheckCount'=>$failed,'evidenceCoveragePercent'=>$coverage);$checks=array(self::check('failed-critical','Failed critical checks',$failed,'<=',$L['maximumFailedCriticalChecks'],$failed<=$L['maximumFailedCriticalChecks']),self::check('release-evidence','Release evidence coverage',$coverage,'>=',$L['minimumEvidenceCoveragePercent'],$coverage>=$L['minimumEvidenceCoveragePercent'],'%'));}
  $failed=array_filter($checks,fn($x)=>!$x['passed']);return array('schema'=>'sc-lab-genomic-validation-result/1.0','version'=>self::VERSION,'profile'=>$p,'thresholds'=>$L,'metrics'=>$metrics,'checks'=>$checks,'decision'=>count($failed)?'fail':'pass','failedCheckCount'=>count($failed),'releaseRecommendation'=>count($failed)?'hold':'release');
 }
 public static function create_manifest($sequences=array(),$metadata=array(),$reference=array(),$pipeline=array(),$variants=array(),$annotations=array()){$components=compact('sequences','metadata','reference','pipeline','variants','annotations');$manifest=array('schema'=>'sc-lab-genomic-dataset-manifest/1.0','version'=>self::VERSION,'createdAt'=>gmdate('c'),'components'=>array());foreach($components as$k=>$v)$manifest['components'][$k]=array('count'=>is_array($v)?(array_keys($v)===range(0,count($v)-1)?count($v):(count($v)?1:0)):0,'hash'=>self::fingerprint($v));$manifest['manifestHash']=self::fingerprint($manifest);return$manifest;}
 public static function create_record($payload,$metadata=array(),$previous=null){$c=self::contract();$event=$metadata['eventType']??$c['defaults']['eventType'];if(!in_array($event,array_column($c['eventTypes'],'id'),true))throw new InvalidArgumentException('Unknown event type: '.$event);$record=array('schema'=>'sc-lab-genomic-sequence-provenance/1.0','version'=>self::VERSION,'recordId'=>$metadata['recordId']??('scgen-'.gmdate('YmdHis').'-'.bin2hex(random_bytes(5))),'eventType'=>$event,'timestamp'=>$metadata['timestamp']??gmdate('c'),'datasetId'=>$metadata['datasetId']??null,'sequenceId'=>$metadata['sequenceId']??null,'variantId'=>$metadata['variantId']??null,'referenceBuild'=>$metadata['referenceBuild']??null,'coordinateSystem'=>$metadata['coordinateSystem']??null,'pipelineVersion'=>$metadata['pipelineVersion']??null,'analyst'=>$metadata['analyst']??null,'reviewer'=>$metadata['reviewer']??null,'organization'=>$metadata['organization']??$c['defaults']['organization'],'sourceRecordIds'=>array_values($metadata['sourceRecordIds']??array()),'evidenceLinks'=>array_values($metadata['evidenceLinks']??array()),'disposition'=>$metadata['disposition']??$c['defaults']['disposition'],'notes'=>$metadata['notes']??null,'previousHash'=>$previous,'payloadHash'=>self::fingerprint($payload),'payload'=>$payload,'engine'=>array('genomicsRelease'=>'0.24.0','productionRelease'=>'0.24.1','visualizationRelease'=>'0.24.2','validationRelease'=>self::VERSION));$record['recordHash']=self::fingerprint($record);return$record;}
 public static function verify_ledger($records){$results=array();$previous=null;foreach($records as$r){$copy=$r;$stored=(string)($copy['recordHash']??'');unset($copy['recordHash']);$calculated=self::fingerprint($copy);$payloadValid=($r['payloadHash']??'')===self::fingerprint($r['payload']??null);$hashValid=hash_equals($stored,$calculated);$chainValid=($r['previousHash']??null)===$previous;$results[]=array('recordId'=>$r['recordId']??null,'payloadValid'=>$payloadValid,'hashValid'=>$hashValid,'chainValid'=>$chainValid,'valid'=>$payloadValid&&$hashValid&&$chainValid,'storedHash'=>$stored,'calculatedHash'=>$calculated);$previous=$stored;}$valid=true;foreach($results as$x)if(!$x['valid']){$valid=false;break;}return array('schema'=>'sc-lab-genomic-ledger-verification/1.0','version'=>self::VERSION,'valid'=>$valid,'recordCount'=>count($records),'results'=>$results);}
 public static function create_dossier($validation,$manifest,$records,$disposition=null){$failed=array_filter($validation,fn($x)=>($x['decision']??null)!=='pass');$ledger=self::verify_ledger($records);$copy=$manifest;unset($copy['manifestHash']);$manifestValid=($manifest['manifestHash']??'')===self::fingerprint($copy);$resolved=$disposition??(count($failed)||!$ledger['valid']||!$manifestValid?'hold':'release');$d=array('schema'=>'sc-lab-genomic-validation-dossier/1.0','version'=>self::VERSION,'createdAt'=>gmdate('c'),'summary'=>array('validationResultCount'=>count($validation),'failedValidationCount'=>count($failed),'recordCount'=>count($records),'ledgerValid'=>$ledger['valid'],'manifestValid'=>$manifestValid,'disposition'=>$resolved),'manifest'=>$manifest,'validationResults'=>$validation,'provenanceLedger'=>$records,'ledgerVerification'=>$ledger,'responsibleUse'=>self::contract()['responsibleUse']);$d['summary']['releaseReady']=count($failed)===0&&$ledger['valid']&&$manifestValid&&$resolved==='release';$d['dossierHash']=self::fingerprint($d);return$d;}
 public static function routes(){register_rest_route(self::NAMESPACE,'/compute/genomics/validation/profiles',array('methods'=>'GET','callback'=>fn()=>rest_ensure_response(self::contract()),'permission_callback'=>'__return_true'));register_rest_route(self::NAMESPACE,'/compute/genomics/validation/evaluate',array('methods'=>'POST','callback'=>array(__CLASS__,'eval_response'),'permission_callback'=>'__return_true'));register_rest_route(self::NAMESPACE,'/compute/genomics/provenance/manifest',array('methods'=>'POST','callback'=>array(__CLASS__,'manifest_response'),'permission_callback'=>'__return_true'));register_rest_route(self::NAMESPACE,'/compute/genomics/provenance/record',array('methods'=>'POST','callback'=>array(__CLASS__,'record_response'),'permission_callback'=>'__return_true'));register_rest_route(self::NAMESPACE,'/compute/genomics/provenance/verify',array('methods'=>'POST','callback'=>array(__CLASS__,'verify_response'),'permission_callback'=>'__return_true'));register_rest_route(self::NAMESPACE,'/compute/genomics/validation/dossier',array('methods'=>'POST','callback'=>array(__CLASS__,'dossier_response'),'permission_callback'=>'__return_true'));}
 public static function eval_response($r){try{$p=$r->get_json_params();return rest_ensure_response(self::evaluate((string)($p['profileId']??''),$p['rows']??array(),$p['thresholds']??array()));}catch(Throwable$e){return new WP_Error('sc_lab_v0243_validation_error',$e->getMessage(),array('status'=>422));}}
 public static function manifest_response($r){$p=$r->get_json_params();return rest_ensure_response(self::create_manifest($p['sequences']??array(),$p['metadata']??array(),$p['reference']??array(),$p['pipeline']??array(),$p['variants']??array(),$p['annotations']??array()));}
 public static function record_response($r){try{$p=$r->get_json_params();return rest_ensure_response(self::create_record($p['payload']??null,$p['metadata']??array(),$p['previousHash']??null));}catch(Throwable$e){return new WP_Error('sc_lab_v0243_provenance_error',$e->getMessage(),array('status'=>422));}}
 public static function verify_response($r){$p=$r->get_json_params();return rest_ensure_response(self::verify_ledger($p['records']??array()));}
 public static function dossier_response($r){$p=$r->get_json_params();return rest_ensure_response(self::create_dossier($p['validationResults']??array(),$p['manifest']??array(),$p['records']??array(),$p['disposition']??null));}
}
SC_Lab_Genomic_Validation_REST_V0243::boot();
