<?php
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Laboratory_Instrumentation_REST_V0250 {
 const VERSION='0.25.0'; const NAMESPACE='sc-lab/v1';
 public static function boot(){add_action('rest_api_init',array(__CLASS__,'register_routes'));}
 private static function path(){return dirname(__DIR__).'/contracts/laboratory-data-instrumentation-v0250.json';}
 public static function catalog(){$d=json_decode(file_get_contents(self::path()),true);return is_array($d)?$d:array();}
 private static function finite($v,$n){if(!is_numeric($v)||!is_finite((float)$v))throw new InvalidArgumentException($n.' must be numerical and finite.');return (float)$v;}
 private static function positive($v,$n){$x=self::finite($v,$n);if($x<=0)throw new InvalidArgumentException($n.' must be greater than zero.');return $x;}
 private static function values($v,$n='values'){if(is_string($v)){$d=json_decode(trim($v),true);$v=is_array($d)?$d:preg_split('/[\s,]+/',trim($v),-1,PREG_SPLIT_NO_EMPTY);}if(!is_array($v)||!count($v))throw new InvalidArgumentException($n.' must be a non-empty array.');return array_map(static fn($x)=>(float)$x,$v);}
 private static function mean($x){return array_sum($x)/count($x);} private static function sd($x){if(count($x)<2)return 0.0;$m=self::mean($x);$s=0.0;foreach($x as $v)$s+=($v-$m)**2;return sqrt($s/(count($x)-1));}
 private static function method($id){foreach(self::catalog()['methods'] as $m)if($m['id']===$id)return $m;throw new InvalidArgumentException('Unknown instrumentation method: '.$id);}
 public static function execute($id,$inputs){$m=self::method($id);$op=$m['operation'];$i=is_array($inputs)?$inputs:array();$p=static fn($k)=>self::finite($i[$k]??null,$k);$pos=static fn($k)=>self::positive($i[$k]??null,$k);$x=array_key_exists('values',$i)?self::values($i['values']):array();
 switch($op){
 case'sample_rate_from_interval':$r=1/$pos('intervalSeconds');break;case'sample_interval_ms':$r=1000/$pos('sampleRateHz');break;case'sample_count':$r=round($p('durationSeconds')*$pos('sampleRateHz'));break;case'acquisition_duration':$r=$p('sampleCount')/$pos('sampleRateHz');break;case'data_throughput':$r=$p('sampleRateHz')*$p('channelCount')*$p('bytesPerSample');break;case'storage_size':$r=$p('durationSeconds')*$p('throughputBytesPerSecond')/1e6;break;case'adc_levels':$r=2**(int)$pos('bits');break;case'quantization_step':$r=$pos('inputRange')/(2**(int)$pos('bits')-1);break;
 case'two_point_gain':$r=($p('referenceHigh')-$p('referenceLow'))/($p('rawHigh')-$p('rawLow'));break;case'two_point_offset':$r=$p('referenceLow')-$p('gain')*$p('rawLow');break;case'apply_calibration':$r=$p('gain')*$p('rawValue')+$p('offset');break;case'inverse_calibration':$r=($p('calibratedValue')-$p('offset'))/$p('gain');break;case'absolute_error':$r=abs($p('measured')-$p('reference'));break;case'percent_error':$r=abs($p('measured')-$p('reference'))/abs($p('reference'))*100;break;case'drift_rate':$r=($p('finalValue')-$p('initialValue'))/$pos('elapsedHours');break;case'calibration_due_days':$r=$p('intervalDays')-$p('daysSinceCalibration');break;
 case'mean':$r=self::mean($x);break;case'median':sort($x,SORT_NUMERIC);$n=count($x);$r=$n%2?$x[(int)(($n-1)/2)]:($x[$n/2-1]+$x[$n/2])/2;break;case'sd':$r=self::sd($x);break;case'cv':$r=self::sd($x)/abs(self::mean($x))*100;break;case'minimum':$r=min($x);break;case'maximum':$r=max($x);break;case'range':$r=max($x)-min($x);break;case'rms':$r=sqrt(array_sum(array_map(static fn($v)=>$v*$v,$x))/count($x));break;
 case'moving_average_latest':$w=(int)$pos('windowSize');if($w>count($x))throw new InvalidArgumentException('windowSize cannot exceed sample count.');$r=self::mean(array_slice($x,-$w));break;case'smoothing_alpha':$r=$p('sampleIntervalSeconds')/($pos('timeConstantSeconds')+$p('sampleIntervalSeconds'));break;case'linear_interpolation':$r=$p('y0')+($p('x')-$p('x0'))*($p('y1')-$p('y0'))/($p('x1')-$p('x0'));break;case'trapezoid_area':$r=($p('x1')-$p('x0'))*($p('y0')+$p('y1'))/2;break;case'finite_difference':$r=($p('y1')-$p('y0'))/($p('x1')-$p('x0'));break;case'baseline_corrected':$r=$p('value')-$p('baseline');break;
 case'c_to_f':$r=$p('celsius')*9/5+32;break;case'f_to_c':$r=($p('fahrenheit')-32)*5/9;break;case'c_to_k':$r=$p('celsius')+273.15;break;case'k_to_c':$r=$p('kelvin')-273.15;break;case'pa_to_kpa':$r=$p('pascal')/1000;break;case'ml_to_l':$r=$p('milliliter')/1000;break;case'mg_to_g':$r=$p('milligram')/1000;break;case'ug_to_mg':$r=$p('microgram')/1000;break;
 case'elapsed_seconds':$r=$p('endEpochSeconds')-$p('startEpochSeconds');break;case'timezone_adjusted_epoch':$r=$p('epochSeconds')+$p('offsetMinutes')*60;break;case'events_per_hour':$r=$p('eventCount')*3600/$pos('durationSeconds');break;case'schedule_progress':$r=$p('elapsedSeconds')/$pos('plannedSeconds')*100;break;case'missing_percent':$r=$p('missingCount')/$pos('totalCount')*100;break;case'duplicate_percent':$r=$p('duplicateCount')/$pos('totalCount')*100;break;case'out_of_range_percent':$r=$p('outOfRangeCount')/$pos('totalCount')*100;break;case'data_quality_index':$r=max(0,min(100,100-2*$p('missingPercent')-1.5*$p('duplicatePercent')-2*$p('outOfRangePercent')));break;case'custody_completeness':$r=$p('completedSteps')/$pos('requiredSteps')*100;break;case'uptime_percent':$r=$p('availableSeconds')/$pos('scheduledSeconds')*100;break;default:throw new InvalidArgumentException('Unsupported operation: '.$op);}
 return array('schema'=>'sc-lab-instrumentation-result/1.0','version'=>self::VERSION,'method'=>$m,'inputs'=>$inputs,'value'=>$r,'unit'=>$m['output']['unit']);}
 private static function canonicalize($v){if(!is_array($v))return $v;if(array_keys($v)===range(0,count($v)-1))return array_map(array(__CLASS__,'canonicalize'),$v);ksort($v,SORT_STRING);foreach($v as $k=>$x)$v[$k]=self::canonicalize($x);return $v;}
 public static function fingerprint($v){return hash('sha256',json_encode(self::canonicalize($v),JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_PRESERVE_ZERO_FRACTION|JSON_THROW_ON_ERROR));}
 public static function create_record($type,$data,$metadata=array()){if(!in_array($type,self::catalog()['recordTypes'],true))throw new InvalidArgumentException('Unknown record type: '.$type);$payload=array('recordType'=>$type,'data'=>$data,'metadata'=>$metadata);return array('schema'=>'sc-lab-instrumentation-record/1.0','version'=>self::VERSION,'recordId'=>$metadata['recordId']??('sclab-'.bin2hex(random_bytes(8))),'recordType'=>$type,'createdAt'=>$metadata['createdAt']??gmdate('c'),'payload'=>$payload,'payloadHash'=>self::fingerprint($payload));}
 public static function create_manifest($records){$components=array_map(static fn($r)=>array('recordId'=>$r['recordId']??null,'recordType'=>$r['recordType']??null,'payloadHash'=>$r['payloadHash']??null),$records);$m=array('schema'=>'sc-lab-instrumentation-manifest/1.0','version'=>self::VERSION,'recordCount'=>count($records),'components'=>$components);$m['manifestHash']=self::fingerprint($m);return $m;}
 public static function create_custody_event($sample,$action,$actor,$location,$previous=null,$notes=null){$e=array('schema'=>'sc-lab-custody-event/1.0','version'=>self::VERSION,'eventId'=>'custody-'.bin2hex(random_bytes(8)),'timestamp'=>gmdate('c'),'sampleId'=>$sample,'action'=>$action,'actor'=>$actor,'location'=>$location,'notes'=>$notes,'previousHash'=>$previous);$e['eventHash']=self::fingerprint($e);return $e;}
 public static function verify_custody($events){$prev=null;$results=array();foreach($events as $e){$copy=$e;$stored=$copy['eventHash']??'';unset($copy['eventHash']);$calc=self::fingerprint($copy);$hash=hash_equals((string)$stored,(string)$calc);$chain=($e['previousHash']??null)===$prev;$results[]=array('eventId'=>$e['eventId']??null,'hashValid'=>$hash,'chainValid'=>$chain,'valid'=>$hash&&$chain);$prev=$stored;}return array('schema'=>'sc-lab-custody-verification/1.0','version'=>self::VERSION,'valid'=>!in_array(false,array_column($results,'valid'),true),'eventCount'=>count($events),'results'=>$results);}
 public static function normalize_measurements($rows,$map=array()){$out=array();foreach($rows as $idx=>$row){$value=self::finite($row['value']??null,'value row '.($idx+1));$factor=self::finite($map[(string)($row['unit']??'')]??1,'unit factor row '.($idx+1));$row['normalizedValue']=$value*$factor;$row['sourceIndex']=$idx+1;$row['qualityFlags']=array_values($row['qualityFlags']??array());$out[]=$row;}return array('schema'=>'sc-lab-measurement-ingest/1.0','version'=>self::VERSION,'rowCount'=>count($out),'rows'=>$out,'datasetHash'=>self::fingerprint($out));}
 public static function health_payload(){$c=self::catalog();$ok=($c['version']??null)===self::VERSION&&count($c['methods']??array())===48&&count($c['benchmarks']??array())===48&&count($c['categories']??array())===8;return array('ok'=>$ok,'status'=>$ok?'ready':'contract-incomplete','release'=>self::VERSION,'methodCount'=>count($c['methods']??array()),'benchmarkCount'=>count($c['benchmarks']??array()),'categoryCount'=>count($c['categories']??array()),'recordTypeCount'=>count($c['recordTypes']??array()),'connectionProfileCount'=>count($c['connectionProfiles']??array()));}
 public static function register_routes(){foreach(array(
  array('/compute/instrumentation/methods','GET','methods_response'),array('/compute/instrumentation/health','GET','health_response'),array('/compute/instrumentation/run','POST','run_response'),array('/compute/instrumentation/records','POST','record_response'),array('/compute/instrumentation/manifest','POST','manifest_response'),array('/compute/instrumentation/custody','POST','custody_response'),array('/compute/instrumentation/custody/verify','POST','verify_response'),array('/compute/instrumentation/measurements/ingest','POST','ingest_response')) as $r)register_rest_route(self::NAMESPACE,$r[0],array('methods'=>$r[1],'callback'=>array(__CLASS__,$r[2]),'permission_callback'=>'__return_true'));}
 public static function methods_response(){return rest_ensure_response(self::catalog());} public static function health_response(){return rest_ensure_response(self::health_payload());}
 private static function body($request){return $request->get_json_params();}
 public static function run_response($request){try{$p=self::body($request);return rest_ensure_response(self::execute((string)($p['methodId']??''),$p['inputs']??array()));}catch(Throwable $e){return new WP_Error('sc_lab_v0250_error',$e->getMessage(),array('status'=>422));}}
 public static function record_response($request){$p=self::body($request);return rest_ensure_response(self::create_record((string)($p['recordType']??''),$p['data']??array(),$p['metadata']??array()));}
 public static function manifest_response($request){$p=self::body($request);return rest_ensure_response(self::create_manifest($p['records']??array()));}
 public static function custody_response($request){$p=self::body($request);return rest_ensure_response(self::create_custody_event((string)($p['sampleId']??''),(string)($p['action']??''),(string)($p['actor']??''),(string)($p['location']??''),$p['previousHash']??null,$p['notes']??null));}
 public static function verify_response($request){$p=self::body($request);return rest_ensure_response(self::verify_custody($p['events']??array()));}
 public static function ingest_response($request){$p=self::body($request);return rest_ensure_response(self::normalize_measurements($p['rows']??array(),$p['unitMap']??array()));}
}
SC_Lab_Laboratory_Instrumentation_REST_V0250::boot();
