<?php
/** Sustainable Catalyst Lab v0.28.0 Project and Workspace Data Architecture. */
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Project_Workspace_V0280 {
    const VERSION='0.28.0';
    private static $initialized=false;
    public static function init(){if(self::$initialized){return;}self::$initialized=true;add_action('rest_api_init',array(__CLASS__,'routes'));add_filter('sc_lab_module_aliases_v02631',array(__CLASS__,'aliases'));}
    public static function aliases($aliases){$aliases=is_array($aliases)?$aliases:array();foreach(array('project-architecture','project-workspace','workspace-architecture','research-project') as $alias){$aliases[$alias]='project-workspace';}return $aliases;}
    public static function routes(){register_rest_route('sc-lab/v1','/workspace/v0280/health',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'health'),'permission_callback'=>'__return_true'));register_rest_route('sc-lab/v1','/workspace/v0280/schema',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'schema'),'permission_callback'=>'__return_true'));}
    private static function file_state($relative){$path=SC_LAB_DIR.$relative;return array('exists'=>is_file($path),'sha256'=>is_file($path)?hash_file('sha256',$path):null);}
    public static function schema(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'schema'=>'sc-lab-project-workspace/0.28.0','canonicalRecordTypes'=>array('experiment','dataset','model','calculation','note','source','report','compute-job'),'storageModes'=>array('browser-local','memory-safe-start'),'serverBackedStorage'=>false,'compatibility'=>array('legacyProjectSchema'=>'0.20.0','unknownFieldsPreserved'=>true,'migrationInPlace'=>true)));}
    public static function health(){ $required=array('assets/js/modules/projects.js','assets/js/modules/project-workspace-v0280.js','assets/css/sc-lab-project-workspace-v0280.css','contracts/project-record-v0280.schema.json','contracts/project-workspace-v0280.schema.json','contracts/project-bundle-v0280.schema.json','includes/class-sc-lab-project-workspace-v0280.php');$files=array();foreach($required as $rel){$files[$rel]=self::file_state($rel);} $ok=!in_array(false,array_map(function($row){return !empty($row['exists']);},$files),true);return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'ready':'incomplete','version'=>self::VERSION,'release'=>defined('SC_LAB_VERSION')?SC_LAB_VERSION:null,'architecture'=>'shared-browser-project-workspace','projectSchema'=>'0.28.0','legacyCompatibility'=>'0.20.0','canonicalRecordTypes'=>8,'capabilities'=>array('autosave'=>true,'checkpoints'=>true,'relationships'=>true,'recordIndex'=>true,'search'=>true,'importExport'=>true,'migrationHistory'=>true,'safeStart'=>true),'storage'=>array('default'=>'browser-local','serverBacked'=>false,'safeStart'=>'memory-only'),'files'=>$files,'time'=>gmdate('c')));}
}
