<?php
/** Sustainable Catalyst Lab v0.30.2 Scientific Model Calibration and Validation. */
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Model_Calibration_V0302 {
    const VERSION='0.30.2'; private static $initialized=false;
    public static function init(){if(self::$initialized){return;}self::$initialized=true;add_action('rest_api_init',array(__CLASS__,'routes'));add_filter('sc_lab_module_aliases_v02631',array(__CLASS__,'aliases'));}
    public static function aliases($aliases){$aliases=is_array($aliases)?$aliases:array();foreach(array('model-calibration','scientific-model-calibration','calibration-validation','model-validation','parameter-fitting') as $a){$aliases[$a]='model-calibration';}return $aliases;}
    public static function routes(){register_rest_route('sc-lab/v1','/model-calibration/v0302/health',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'health'),'permission_callback'=>'__return_true'));register_rest_route('sc-lab/v1','/model-calibration/v0302/schema',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'schema'),'permission_callback'=>'__return_true'));}
    private static function file_state($rel){$p=SC_LAB_DIR.$rel;return array('exists'=>is_file($p),'sha256'=>is_file($p)?hash_file('sha256',$p):null);}
    public static function schema(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'studySchema'=>'sc-lab-model-calibration-study/0.30.2','resultSchema'=>'sc-lab-model-calibration-result/0.30.2','validationSchema'=>'sc-lab-model-validation/0.30.2','comparisonSchema'=>'sc-lab-model-comparison/0.30.2','bundleSchema'=>'sc-lab-model-calibration-bundle/0.30.2','storage'=>'browser-local-project-records','pythonFitting'=>true,'registeredModelFormsOnly'=>true,'serverBackedRegistry'=>false));}
    public static function health(){$required=array('assets/js/modules/model-calibration-v0302.js','assets/css/sc-lab-model-calibration-v0302.css','contracts/model-calibration-policy-v0302.json','contracts/model-calibration-study-v0302.schema.json','contracts/model-calibration-result-v0302.schema.json','contracts/model-validation-v0302.schema.json','contracts/model-comparison-v0302.schema.json','includes/class-sc-lab-model-calibration-v0302.php');$files=array();foreach($required as $rel){$files[$rel]=self::file_state($rel);} $ok=true;foreach($files as $row){if(empty($row['exists'])){$ok=false;break;}}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'ready':'incomplete','version'=>self::VERSION,'release'=>defined('SC_LAB_VERSION')?SC_LAB_VERSION:null,'architecture'=>'project-scoped-model-calibration-validation','serverBackedRegistry'=>false,'files'=>$files,'time'=>gmdate('c')));}
}
