<?php
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Competing_Model_Hypothesis_Analysis_V01350 {
 const VERSION='0.135.0'; const ENGINE_VERSION='16.0.0'; const SCHEMA='sc-lab-competing-model-hypothesis-analysis/0.135.0';
 public static function init(){ add_action('rest_api_init',array(__CLASS__,'routes')); }
 public static function routes(){ $ns='sc-lab/v1/analysis/v01350'; foreach(array('health','manifest','schema','catalog') as $r){register_rest_route($ns,'/'.$r,array('methods'=>'GET','callback'=>array(__CLASS__,$r),'permission_callback'=>'__return_true'));}}
 private static function state($r){$p=SC_LAB_DIR.$r;return array('exists'=>is_file($p),'sha256'=>is_file($p)?hash_file('sha256',$p):null);}
 public static function schema(){return rest_ensure_response(array('ok'=>true,'schema'=>self::SCHEMA,'version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'relationStateCount'=>7,'apiRouteCount'=>49));}
 public static function catalog(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'comparisonFamilyCount'=>24,'hypothesisKindCount'=>8,'modelKindCount'=>10,'relationStateCount'=>7,'figureFamilyCount'=>17,'researcherAdjudicationRequired'=>true,'automaticHypothesisRanking'=>false,'automaticModelRanking'=>false,'automaticWinnerSelection'=>false,'determineTruth'=>false));}
 public static function manifest(){return rest_ensure_response(array('ok'=>true,'status'=>'competing-model-hypothesis-analysis-ready','version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'v01310HypothesisReferenceBridge'=>true,'v01330DiagnosticReferenceBridge'=>true,'v01340EvidenceSynthesisReferenceBridge'=>true,'contradictionsPreserved'=>true,'replicationDisagreementPreserved'=>true,'researcherAdjudicationRequired'=>true,'automaticWinnerSelection'=>false,'automaticScientificValidityCertification'=>false,'automaticCoreSubmission'=>false,'determineTruth'=>false));}
 public static function health(){ $req=array('contracts/competing-model-hypothesis-analysis-v01350.schema.json','contracts/competing-model-hypothesis-analysis-policy-v01350.json','includes/class-sc-lab-competing-model-hypothesis-analysis-v01350.php','assets/js/modules/competing-model-hypothesis-analysis-v01350.js','assets/css/sc-lab-competing-model-hypothesis-analysis-v01350.css');$files=array();$ok=true;foreach($req as $r){$files[$r]=self::state($r);if(empty($files[$r]['exists']))$ok=false;}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'competing-model-hypothesis-analysis-ready':'incomplete','version'=>self::VERSION,'labReleaseVersion'=>defined('SC_LAB_RELEASE_VERSION')?SC_LAB_RELEASE_VERSION:self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'comparisonFamilyCount'=>24,'hypothesisKindCount'=>8,'modelKindCount'=>10,'figureFamilyCount'=>17,'apiRouteCount'=>49,'files'=>$files,'researcherAdjudicationRequired'=>true,'automaticHypothesisRanking'=>false,'automaticModelRanking'=>false,'automaticWinnerSelection'=>false,'automaticScientificValidityCertification'=>false,'automaticCoreSubmission'=>false,'time'=>gmdate('c')));}
}
SC_Lab_Competing_Model_Hypothesis_Analysis_V01350::init();
