<?php
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Research_Question_Hypothesis_Workspace_V01310 {
 const VERSION='0.131.0'; const ENGINE_VERSION='12.0.0'; const SCHEMA='sc-lab-research-question-hypothesis-workspace/0.131.0';
 public static function init(){ add_action('rest_api_init',array(__CLASS__,'routes')); }
 public static function routes(){ $ns='sc-lab/v1/analysis/v01310'; foreach(array('health','manifest','schema','catalog') as $r){register_rest_route($ns,'/'.$r,array('methods'=>'GET','callback'=>array(__CLASS__,$r),'permission_callback'=>'__return_true'));}}
 private static function state($r){$p=SC_LAB_DIR.$r;return array('exists'=>is_file($p),'sha256'=>is_file($p)?hash_file('sha256',$p):null);}
 public static function schema(){return rest_ensure_response(array('ok'=>true,'schema'=>self::SCHEMA,'version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'maxQuestions'=>5000,'maxHypotheses'=>10000,'maxVariables'=>10000,'maxObservables'=>20000,'apiRouteCount'=>33));}
 public static function catalog(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'methodFamilyCount'=>20,'figureFamilyCount'=>14,'researcherSelectionRequired'=>true,'automaticHypothesisSelection'=>false,'automaticTruthDetermination'=>false,'automaticCoreSubmission'=>false));}
 public static function manifest(){return rest_ensure_response(array('ok'=>true,'status'=>'research-question-hypothesis-workspace-ready','version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'questionFormalization'=>true,'competingHypotheses'=>true,'operationalization'=>true,'falsificationAndDisconfirmation'=>true,'preregistrationLocking'=>true,'researcherSelectionRequired'=>true,'automaticHypothesisGeneration'=>false,'automaticHypothesisSelection'=>false,'automaticEvidenceWeighting'=>false,'automaticScientificValidityCertification'=>false,'automaticCoreSubmission'=>false,'determineTruth'=>false));}
 public static function health(){ $req=array('contracts/research-question-hypothesis-workspace-v01310.schema.json','contracts/research-question-hypothesis-workspace-policy-v01310.json','includes/class-sc-lab-research-question-hypothesis-workspace-v01310.php','assets/js/modules/research-question-hypothesis-workspace-v01310.js','assets/css/sc-lab-research-question-hypothesis-workspace-v01310.css');$files=array();$ok=true;foreach($req as $r){$files[$r]=self::state($r);if(empty($files[$r]['exists']))$ok=false;}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'research-question-hypothesis-workspace-ready':'incomplete','version'=>self::VERSION,'labReleaseVersion'=>defined('SC_LAB_RELEASE_VERSION')?SC_LAB_RELEASE_VERSION:self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'methodFamilyCount'=>20,'figureFamilyCount'=>14,'apiRouteCount'=>33,'files'=>$files,'researcherSelectionRequired'=>true,'automaticHypothesisSelection'=>false,'automaticScientificValidityCertification'=>false,'automaticCoreSubmission'=>false,'time'=>gmdate('c')));}
}
SC_Lab_Research_Question_Hypothesis_Workspace_V01310::init();
