<?php
/** Sustainable Catalyst Lab v0.45.0 Dynamic Systems, ODE Models & Parameter Estimation. */
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Model_Studio_V0450 {
    const VERSION='0.45.0'; private static $initialized=false;
    public static function init(){if(self::$initialized){return;}self::$initialized=true;add_action('rest_api_init',array(__CLASS__,'routes'));add_filter('sc_lab_module_aliases_v02631',array(__CLASS__,'aliases'));add_filter('sc_lab_panel_aliases_v02631',array(__CLASS__,'aliases'));add_shortcode('sc_lab_model_studio',array(__CLASS__,'shortcode'));}
    public static function aliases($aliases){$aliases=is_array($aliases)?$aliases:array();foreach(array('model-studio','scientific-model-studio','model-builder','scientific-modeling','equation-builder','model-diagnostics','cross-validation','model-comparison','publication-graphics','scientific-graphs','interactive-graphs','dynamic-systems','ode-models','ode-modeling','parameter-estimation','phase-portrait') as $alias){$aliases[$alias]='model-studio';}return $aliases;}
    public static function shortcode(){return do_shortcode('[sc_lab_app module="model-studio"]');}
    public static function routes(){register_rest_route('sc-lab/v1','/model-studio/v0450/health',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'health'),'permission_callback'=>'__return_true'));register_rest_route('sc-lab/v1','/model-studio/v0450/schema',array('methods'=>WP_REST_Server::READABLE,'callback'=>array(__CLASS__,'schema'),'permission_callback'=>'__return_true'));}
    private static function file_state($relative){$path=SC_LAB_DIR.$relative;return array('exists'=>is_file($path),'sha256'=>is_file($path)?hash_file('sha256',$path):null);}
    public static function schema(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'modelSchema'=>'sc-lab-model-studio-model/0.45.0','graphSchema'=>'sc-lab-scientific-graph/0.45.0','dynamicSystemSchema'=>'sc-lab-dynamic-system/0.45.0','simulationSchema'=>'sc-lab-dynamic-system-simulation/0.45.0','parameterEstimationSchema'=>'sc-lab-dynamic-parameter-estimation/0.45.0','diagnosticsSchema'=>'sc-lab-model-diagnostics/0.43.0','crossValidationSchema'=>'sc-lab-cross-validation/0.43.0','comparisonSchema'=>'sc-lab-scientific-model-comparison/0.43.0','equationSchema'=>'sc-lab-scientific-equation/0.42.0','sharedVisualizationEngine'=>'SCLabScientificVisualizationEngineV0440','arbitraryCode'=>false,'arbitraryFormulaFitting'=>false,'safeDerivativeExpressions'=>true,'boundedODEParameterEstimation'=>true));}
    public static function health(){$required=array('backend/app/model_studio.py','backend/app/model_diagnostics.py','backend/app/equation_builder.py','backend/app/dynamic_systems.py','backend/tests/test_model_studio_v0450.py','backend/tests/test_dynamic_systems_v0450.py','assets/js/modules/model-studio-v0450.js','assets/js/modules/scientific-visualization-engine-v0440.js','assets/css/sc-lab-model-studio-v0450.css','assets/css/sc-lab-scientific-visualization-engine-v0440.css','contracts/model-studio-policy-v0450.json','contracts/model-studio-model-v0450.schema.json','contracts/scientific-graph-v0450.schema.json','contracts/dynamic-system-v0450.schema.json','contracts/dynamic-system-simulation-v0450.schema.json','contracts/dynamic-parameter-estimation-v0450.schema.json');$files=array();$ok=true;foreach($required as $relative){$files[$relative]=self::file_state($relative);if(empty($files[$relative]['exists'])){$ok=false;}}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'dynamic-systems-ready':'incomplete','version'=>self::VERSION,'release'=>defined('SC_LAB_RELEASE_VERSION')?SC_LAB_RELEASE_VERSION:null,'platformVersion'=>defined('SC_LAB_PLATFORM_VERSION')?SC_LAB_PLATFORM_VERSION:null,'dynamicSystems'=>true,'coupledODEs'=>true,'safeDerivativeExpressions'=>true,'boundedParameterEstimation'=>true,'robustLosses'=>true,'identifiabilityDiagnostics'=>true,'phasePortraits'=>true,'crossValidation'=>true,'scientificModelComparison'=>true,'interactiveZoom'=>true,'interactivePan'=>true,'publicationExports'=>array('svg','png','csv','json'),'sharedVisualizationEngine'=>true,'arbitraryCode'=>false,'arbitraryFormulaFitting'=>false,'files'=>$files,'time'=>gmdate('c')));}
}
