<?php
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Bayesian_Analysis_Workbench_V01220 {
 const VERSION='0.122.0'; const ENGINE_VERSION='4.2.0'; const SCHEMA='sc-lab-bayesian-analysis-workbench-ii/0.122.0';
 public static function init(){ add_action('rest_api_init',array(__CLASS__,'routes')); }
 public static function routes(){ $ns='sc-lab/v1/analysis/v01220'; foreach(array('health','manifest','schema','catalog') as $r){register_rest_route($ns,'/'.$r,array('methods'=>'GET','callback'=>array(__CLASS__,$r),'permission_callback'=>'__return_true'));}}
 private static function state($r){$p=SC_LAB_DIR.$r;return array('exists'=>is_file($p),'sha256'=>is_file($p)?hash_file('sha256',$p):null);}
 public static function schema(){return rest_ensure_response(array('ok'=>true,'schema'=>self::SCHEMA,'version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'maxRows'=>5000,'maxModels'=>10,'maxHierarchicalUnits'=>500,'apiRouteCount'=>20));}
 public static function catalog(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'families'=>array('gaussian','binomial-logit','poisson-log'),'diagnostics'=>array('split-rhat','ess','mcse','acceptance-rate','posterior-predictive','prior-posterior','trace'),'hierarchicalModels'=>array('normal-normal-random-effects'),'figureFamilyCount'=>12));}
 public static function manifest(){return rest_ensure_response(array('ok'=>true,'status'=>'bayesian-analysis-workbench-ii-ready','version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'priorPosteriorComparison'=>true,'posteriorDiagnostics'=>true,'posteriorPredictiveChecks'=>true,'probabilityStatements'=>true,'hierarchicalNormalRandomEffects'=>true,'modelComparison'=>true,'sourceRowsImmutable'=>true,'automaticPriorSelection'=>false,'automaticConvergenceCertification'=>false,'automaticModelSelection'=>false,'automaticSignificanceLabels'=>false,'automaticCausalInference'=>false,'automaticGeneralization'=>false,'automaticScientificValidityCertification'=>false,'automaticCoreSubmission'=>false,'determineTruth'=>false));}
 public static function health(){ $req=array('contracts/bayesian-analysis-workbench-v01220.schema.json','contracts/bayesian-analysis-workbench-policy-v01220.json','includes/class-sc-lab-bayesian-analysis-workbench-v01220.php','assets/js/modules/bayesian-analysis-workbench-v01220.js','assets/css/sc-lab-bayesian-analysis-workbench-v01220.css');$files=array();$ok=true;foreach($req as $r){$files[$r]=self::state($r);if(empty($files[$r]['exists']))$ok=false;}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'bayesian-analysis-workbench-ii-ready':'incomplete','version'=>self::VERSION,'labReleaseVersion'=>defined('SC_LAB_RELEASE_VERSION')?SC_LAB_RELEASE_VERSION:self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'familyCount'=>3,'diagnosticCount'=>7,'figureFamilyCount'=>12,'apiRouteCount'=>20,'files'=>$files,'automaticPriorSelection'=>false,'automaticConvergenceCertification'=>false,'automaticModelSelection'=>false,'automaticScientificValidityCertification'=>false,'time'=>gmdate('c')));}
}
SC_Lab_Bayesian_Analysis_Workbench_V01220::init();
