<?php
/** Sustainable Catalyst Lab v0.37.2 Public Reproduction and Verification Portal. */
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Public_Reproduction_V0372 {
 const VERSION='0.37.2'; private static $initialized=false;
 public static function init(){if(self::$initialized){return;}self::$initialized=true;add_action('rest_api_init',array(__CLASS__,'routes'));}
 public static function routes(){register_rest_route('sc-lab/v1','/public-reproduction/schema',array('methods'=>'GET','callback'=>array(__CLASS__,'schema'),'permission_callback'=>'__return_true'));register_rest_route('sc-lab/v1','/public-reproduction/integrity',array('methods'=>'GET','callback'=>array(__CLASS__,'health'),'permission_callback'=>'__return_true'));}
 private static function state($relative){$path=SC_LAB_DIR.$relative;return array('exists'=>is_file($path),'sha256'=>is_file($path)?hash_file('sha256',$path):null);}
 public static function schema(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'recordSchema'=>'sc-lab-public-reproduction-record/0.37.2','challengeSchema'=>'sc-lab-reproduction-challenge/0.37.2','receiptSchema'=>'sc-lab-reproduction-verification-receipt/0.37.2','eventSchema'=>'sc-lab-public-reproduction-event/0.37.2','publicCodeExecution'=>false,'embeddedRestrictedData'=>false));}
 public static function health(){$required=array('backend/app/public_reproduction_portal.py','assets/js/modules/public-reproduction-v0372.js','assets/css/sc-lab-public-reproduction-v0372.css','contracts/public-reproduction-policy-v0372.json','contracts/public-reproduction-record-v0372.schema.json','contracts/public-reproduction-challenge-v0372.schema.json','contracts/public-reproduction-receipt-v0372.schema.json','contracts/public-reproduction-event-v0372.schema.json','contracts/public-reproduction-manifest-v0372.schema.json','includes/class-sc-lab-public-reproduction-v0372.php');$files=array();$ok=true;foreach($required as $relative){$files[$relative]=self::state($relative);if(empty($files[$relative]['exists'])){$ok=false;}}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'ready':'incomplete','version'=>self::VERSION,'release'=>defined('SC_LAB_VERSION')?SC_LAB_VERSION:null,'architecture'=>'public-reproduction-verification-challenges-and-signed-receipts','databaseSchemaVersion'=>1,'publicVerificationRecords'=>true,'nonceChallenges'=>true,'signedReceipts'=>true,'tamperDetection'=>true,'publicCodeExecution'=>false,'embeddedRestrictedData'=>false,'hardDelete'=>false,'files'=>$files,'time'=>gmdate('c')));}
}
SC_Lab_Public_Reproduction_V0372::init();
