<?php
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Research_Reproduction_Replication_Studio_V01290 {
 const VERSION='0.129.0'; const ENGINE_VERSION='10.0.0'; const SCHEMA='sc-lab-research-reproduction-replication-studio/0.129.0';
 public static function init(){ add_action('rest_api_init',array(__CLASS__,'routes')); }
 public static function routes(){ $ns='sc-lab/v1/analysis/v01290'; foreach(array('health','manifest','schema','catalog') as $r){register_rest_route($ns,'/'.$r,array('methods'=>'GET','callback'=>array(__CLASS__,$r),'permission_callback'=>'__return_true'));}}
 private static function state($r){$p=SC_LAB_DIR.$r;return array('exists'=>is_file($p),'sha256'=>is_file($p)?hash_file('sha256',$p):null);}
 public static function schema(){return rest_ensure_response(array('ok'=>true,'schema'=>self::SCHEMA,'version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'maxArtifacts'=>5000,'maxMetrics'=>1000,'maxDeviations'=>2000,'maxReplications'=>500,'apiRouteCount'=>30));}
 public static function catalog(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'methodFamilyCount'=>15,'figureFamilyCount'=>14,'automaticExecution'=>false,'automaticClaimConfirmation'=>false,'automaticReplicationSuccess'=>false,'automaticScientificValidityCertification'=>false));}
 public static function manifest(){return rest_ensure_response(array('ok'=>true,'status'=>'research-reproduction-replication-studio-ready','version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'reproductionPlanning'=>true,'replicationPlanning'=>true,'artifactIntegrity'=>true,'environmentLocking'=>true,'resultComparison'=>true,'deviationRegister'=>true,'claimLinkage'=>true,'packageAssembly'=>true,'automaticExecution'=>false,'automaticClaimConfirmation'=>false,'automaticReplicationSuccess'=>false,'automaticScientificValidityCertification'=>false,'automaticCoreSubmission'=>false,'determineTruth'=>false));}
 public static function health(){ $req=array('contracts/research-reproduction-replication-studio-v01290.schema.json','contracts/research-reproduction-replication-studio-policy-v01290.json','includes/class-sc-lab-research-reproduction-replication-studio-v01290.php','assets/js/modules/research-reproduction-replication-studio-v01290.js','assets/css/sc-lab-research-reproduction-replication-studio-v01290.css');$files=array();$ok=true;foreach($req as $r){$files[$r]=self::state($r);if(empty($files[$r]['exists']))$ok=false;}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'research-reproduction-replication-studio-ready':'incomplete','version'=>self::VERSION,'labReleaseVersion'=>defined('SC_LAB_RELEASE_VERSION')?SC_LAB_RELEASE_VERSION:self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'methodFamilyCount'=>15,'figureFamilyCount'=>14,'apiRouteCount'=>30,'files'=>$files,'automaticExecution'=>false,'automaticClaimConfirmation'=>false,'automaticReplicationSuccess'=>false,'automaticScientificValidityCertification'=>false,'time'=>gmdate('c')));}
}
SC_Lab_Research_Reproduction_Replication_Studio_V01290::init();
