<?php
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Simulation_Monte_Carlo_Research_Studio_V01230 {
 const VERSION='0.123.0'; const ENGINE_VERSION='4.3.0'; const SCHEMA='sc-lab-simulation-monte-carlo-research-studio/0.123.0';
 public static function init(){ add_action('rest_api_init',array(__CLASS__,'routes')); }
 public static function routes(){ $ns='sc-lab/v1/analysis/v01230'; foreach(array('health','manifest','schema','catalog') as $r){register_rest_route($ns,'/'.$r,array('methods'=>'GET','callback'=>array(__CLASS__,$r),'permission_callback'=>'__return_true'));}}
 private static function state($r){$p=SC_LAB_DIR.$r;return array('exists'=>is_file($p),'sha256'=>is_file($p)?hash_file('sha256',$p):null);}
 public static function schema(){return rest_ensure_response(array('ok'=>true,'schema'=>self::SCHEMA,'version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'maxBaseSamples'=>65536,'maxEvaluations'=>250000,'maxSweepEvaluations'=>20000,'maxScenarios'=>32,'maxReplications'=>12,'apiRouteCount'=>22));}
 public static function catalog(){return rest_ensure_response(array('ok'=>true,'version'=>self::VERSION,'samplingDesigns'=>array('latin-hypercube','monte-carlo','saltelli-sobol','sobol'),'studyFamilies'=>array('uncertainty-propagation','parameter-sweep','scenario-ensemble','seed-replication','convergence-study'),'figureFamilyCount'=>12));}
 public static function manifest(){return rest_ensure_response(array('ok'=>true,'status'=>'simulation-monte-carlo-research-studio-ready','version'=>self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'monteCarlo'=>true,'latinHypercube'=>true,'sobolSampling'=>true,'saltelliSobol'=>true,'parameterSweeps'=>true,'scenarioEnsembles'=>true,'convergenceDiagnostics'=>true,'seedReplication'=>true,'uncertaintyPropagation'=>true,'simulationOutputsAreModeledNotObserved'=>true,'sourceModelsImmutable'=>true,'automaticConvergenceCertification'=>false,'automaticScenarioSelection'=>false,'automaticEvidencePromotion'=>false,'automaticCausalInference'=>false,'automaticScientificValidityCertification'=>false,'automaticCoreSubmission'=>false,'determineTruth'=>false));}
 public static function health(){ $req=array('contracts/simulation-monte-carlo-research-studio-v01230.schema.json','contracts/simulation-monte-carlo-research-studio-policy-v01230.json','includes/class-sc-lab-simulation-monte-carlo-research-studio-v01230.php','assets/js/modules/simulation-monte-carlo-research-studio-v01230.js','assets/css/sc-lab-simulation-monte-carlo-research-studio-v01230.css');$files=array();$ok=true;foreach($req as $r){$files[$r]=self::state($r);if(empty($files[$r]['exists']))$ok=false;}return rest_ensure_response(array('ok'=>$ok,'status'=>$ok?'simulation-monte-carlo-research-studio-ready':'incomplete','version'=>self::VERSION,'labReleaseVersion'=>defined('SC_LAB_RELEASE_VERSION')?SC_LAB_RELEASE_VERSION:self::VERSION,'engineVersion'=>self::ENGINE_VERSION,'samplingDesignCount'=>4,'figureFamilyCount'=>12,'apiRouteCount'=>22,'files'=>$files,'simulationOutputsAreModeledNotObserved'=>true,'automaticConvergenceCertification'=>false,'automaticScenarioSelection'=>false,'automaticEvidencePromotion'=>false,'automaticScientificValidityCertification'=>false,'time'=>gmdate('c')));}
}
SC_Lab_Simulation_Monte_Carlo_Research_Studio_V01230::init();
