<?php
/** Sustainable Catalyst Lab v0.161.0 — Research Program & Portfolio Orchestration. */
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Research_Program_Portfolio_Orchestration_V01610 {
 const VERSION='0.161.0'; private static $initialized=false;
 public static function init(){if(self::$initialized)return;self::$initialized=true;add_action('wp_enqueue_scripts',array(__CLASS__,'enqueue'),PHP_INT_MAX);add_action('wp_print_footer_scripts',array(__CLASS__,'enqueue'),PHP_INT_MAX);add_action('rest_api_init',array(__CLASS__,'routes'));}
 private static function is_lab_request(){if(is_admin())return false;global $post;if($post instanceof WP_Post&&has_shortcode((string)$post->post_content,'sc_lab_app'))return true;if(function_exists('is_page')&&is_page('lab'))return true;$path=isset($_SERVER['REQUEST_URI'])?(string)parse_url((string)$_SERVER['REQUEST_URI'],PHP_URL_PATH):'';return(bool)preg_match('~/(?:lab)/?$~',$path);}
 private static function asset_token($relative){$path=SC_LAB_DIR.ltrim((string)$relative,'/');return self::VERSION.'.'.(is_file($path)?substr(hash_file('sha256',$path),0,16):'missing');}
 public static function enqueue(){if(!self::is_lab_request())return;$css='assets/css/sc-lab-research-program-portfolio-v01610.css';$js='assets/js/sc-lab-research-program-portfolio-v01610.js';wp_enqueue_style('sc-lab-program-portfolio-v01610',SC_LAB_URL.$css,array('sc-lab-research-os-v01600'),self::asset_token($css));wp_enqueue_script('sc-lab-program-portfolio-v01610',SC_LAB_URL.$js,array('sc-lab-research-os-v01600','sc-lab-canonical-repair-v015701'),self::asset_token($js),true);wp_localize_script('sc-lab-program-portfolio-v01610','SCLabProgramPortfolioV01610',array('version'=>self::VERSION,'healthUrl'=>esc_url_raw(rest_url('sc-lab/v1/workspace/program-portfolio/v01610/health')),'programsUrl'=>esc_url_raw(rest_url('sc-lab/v1/workspace/program-portfolio/v01610/programs')),'portfoliosUrl'=>esc_url_raw(rest_url('sc-lab/v1/workspace/program-portfolio/v01610/portfolios')),'snapshotsUrl'=>esc_url_raw(rest_url('sc-lab/v1/workspace/program-portfolio/v01610/snapshots')),'verifyUrl'=>esc_url_raw(rest_url('sc-lab/v1/workspace/program-portfolio/v01610/manifests/verify')),'defaultProgramId'=>is_user_logged_in()?'program:wp-user-'.get_current_user_id():'','defaultPortfolioId'=>is_user_logged_in()?'portfolio:wp-user-'.get_current_user_id():'','nonce'=>wp_create_nonce('wp_rest')));}
 public static function operations_permission(){return is_user_logged_in();}
 private static function settings(){return wp_parse_args((array)get_option('sc_lab_settings',array()),SC_Lab_Admin::defaults());}
 private static function clean_id($v){return substr(preg_replace('/[^A-Za-z0-9._:-]/','',(string)$v),0,180);}
 private static function clean_tree($v,$depth=0,&$nodes=0){$nodes++;if($nodes>30000||$depth>24)return null;if(is_null($v)||is_bool($v)||is_int($v)||is_float($v))return $v;if(is_string($v))return substr(wp_check_invalid_utf8($v,true),0,150000);if(!is_array($v))return null;$out=array();$count=0;foreach($v as $k=>$x){if(++$count>10000)break;$key=is_int($k)?$k:substr(preg_replace('/[^A-Za-z0-9._:-]/','',(string)$k),0,128);if($key===''&&!is_int($k))continue;$out[$key]=self::clean_tree($x,$depth+1,$nodes);}return $out;}
 private static function body(WP_REST_Request $r){$b=$r->get_json_params();$n=0;return self::clean_tree(is_array($b)?$b:array(),0,$n);}
 private static function proxy($path,$method='GET',$payload=null,$limit=8388608){$s=self::settings();if(empty($s['enable_remote_compute'])||empty($s['compute_backend_url']))return new WP_Error('compute_disabled','The Python Compute Core is not enabled or configured.',array('status'=>503));if(!class_exists('SC_Lab_Python_Compute_Core_V0261'))return new WP_Error('compute_proxy_unavailable','The Python Compute Core signing bridge is unavailable.',array('status'=>503));$body=null===$payload?'':wp_json_encode($payload);$url=untrailingslashit($s['compute_backend_url']).$path;$args=array('method'=>$method,'timeout'=>max(5,min(120,absint($s['compute_timeout_seconds']))),'redirection'=>2,'sslverify'=>!empty($s['compute_verify_ssl']),'headers'=>SC_Lab_Python_Compute_Core_V0261::signed_headers($path,$method,$body,$s),'limit_response_size'=>max(262144,min(16777216,absint($limit))));if(null!==$payload)$args['body']=$body;$response=wp_safe_remote_request($url,$args);if(is_wp_error($response))return new WP_Error('program_portfolio_backend_unavailable',$response->get_error_message(),array('status'=>502));$status=wp_remote_retrieve_response_code($response);$decoded=json_decode(wp_remote_retrieve_body($response),true);if(!is_array($decoded)){$decoded=array('detail'=>'The program/portfolio backend returned invalid JSON.');$status=502;}return new WP_REST_Response($decoded,$status);}
 private static function ppath(WP_REST_Request $r,$suffix=''){return '/v1/research-program-portfolio-orchestration/v01610/programs/'.rawurlencode(self::clean_id($r['id'])).$suffix;}
 private static function fpath(WP_REST_Request $r,$suffix=''){return '/v1/research-program-portfolio-orchestration/v01610/portfolios/'.rawurlencode(self::clean_id($r['id'])).$suffix;}
 public static function routes(){
  register_rest_route('sc-lab/v1','/workspace/program-portfolio/v01610/health',array('methods'=>'GET','callback'=>array(__CLASS__,'health'),'permission_callback'=>'__return_true'));
  register_rest_route('sc-lab/v1','/workspace/program-portfolio/v01610/programs',array(array('methods'=>'GET','callback'=>array(__CLASS__,'programs'),'permission_callback'=>array(__CLASS__,'operations_permission')),array('methods'=>'POST','callback'=>array(__CLASS__,'program_create'),'permission_callback'=>array(__CLASS__,'operations_permission'))));
  register_rest_route('sc-lab/v1','/workspace/program-portfolio/v01610/programs/(?P<id>[A-Za-z0-9._:-]{1,180})',array('methods'=>'GET','callback'=>array(__CLASS__,'program_get'),'permission_callback'=>array(__CLASS__,'operations_permission')));
  foreach(array('projects'=>'POST','objectives'=>'POST','milestones'=>'POST','transition'=>'POST','command-center'=>'GET','evaluate'=>'GET','manifest'=>'GET','snapshot'=>'POST','timeline'=>'GET') as $suffix=>$method)register_rest_route('sc-lab/v1','/workspace/program-portfolio/v01610/programs/(?P<id>[A-Za-z0-9._:-]{1,180})/'.$suffix,array('methods'=>$method,'callback'=>array(__CLASS__,'program_'.str_replace('-','_',$suffix)),'permission_callback'=>array(__CLASS__,'operations_permission')));
  register_rest_route('sc-lab/v1','/workspace/program-portfolio/v01610/programs/(?P<id>[A-Za-z0-9._:-]{1,180})/memberships/(?P<membership>[A-Za-z0-9._:-]{1,180})/status',array('methods'=>'POST','callback'=>array(__CLASS__,'program_membership_status'),'permission_callback'=>array(__CLASS__,'operations_permission')));
  register_rest_route('sc-lab/v1','/workspace/program-portfolio/v01610/programs/(?P<id>[A-Za-z0-9._:-]{1,180})/objectives/(?P<objective>[A-Za-z0-9._:-]{1,180})/projects',array('methods'=>'POST','callback'=>array(__CLASS__,'objective_project'),'permission_callback'=>array(__CLASS__,'operations_permission')));
  register_rest_route('sc-lab/v1','/workspace/program-portfolio/v01610/programs/(?P<id>[A-Za-z0-9._:-]{1,180})/objectives/(?P<objective>[A-Za-z0-9._:-]{1,180})/status',array('methods'=>'POST','callback'=>array(__CLASS__,'objective_status'),'permission_callback'=>array(__CLASS__,'operations_permission')));
  register_rest_route('sc-lab/v1','/workspace/program-portfolio/v01610/programs/(?P<id>[A-Za-z0-9._:-]{1,180})/milestones/(?P<milestone>[A-Za-z0-9._:-]{1,180})/status',array('methods'=>'POST','callback'=>array(__CLASS__,'milestone_status'),'permission_callback'=>array(__CLASS__,'operations_permission')));
  register_rest_route('sc-lab/v1','/workspace/program-portfolio/v01610/portfolios',array(array('methods'=>'GET','callback'=>array(__CLASS__,'portfolios'),'permission_callback'=>array(__CLASS__,'operations_permission')),array('methods'=>'POST','callback'=>array(__CLASS__,'portfolio_create'),'permission_callback'=>array(__CLASS__,'operations_permission'))));
  register_rest_route('sc-lab/v1','/workspace/program-portfolio/v01610/portfolios/(?P<id>[A-Za-z0-9._:-]{1,180})',array('methods'=>'GET','callback'=>array(__CLASS__,'portfolio_get'),'permission_callback'=>array(__CLASS__,'operations_permission')));
  foreach(array('programs'=>'POST','transition'=>'POST','command-center'=>'GET','evaluate'=>'GET','manifest'=>'GET','snapshot'=>'POST','timeline'=>'GET') as $suffix=>$method)register_rest_route('sc-lab/v1','/workspace/program-portfolio/v01610/portfolios/(?P<id>[A-Za-z0-9._:-]{1,180})/'.$suffix,array('methods'=>$method,'callback'=>array(__CLASS__,'portfolio_'.str_replace('-','_',$suffix)),'permission_callback'=>array(__CLASS__,'operations_permission')));
  register_rest_route('sc-lab/v1','/workspace/program-portfolio/v01610/snapshots/(?P<snapshot>[A-Za-z0-9._:-]{1,180})',array('methods'=>'GET','callback'=>array(__CLASS__,'snapshot_get'),'permission_callback'=>array(__CLASS__,'operations_permission')));
  register_rest_route('sc-lab/v1','/workspace/program-portfolio/v01610/manifests/verify',array('methods'=>'POST','callback'=>array(__CLASS__,'verify_manifest'),'permission_callback'=>array(__CLASS__,'operations_permission')));
 }
 public static function health(){return self::proxy('/v1/research-program-portfolio-orchestration/v01610/health');}
 public static function programs(WP_REST_Request $r){$q='?include_archived='.($r->get_param('include_archived')?'true':'false').'&limit='.max(1,min(1000,absint($r->get_param('limit')?:100)));return self::proxy('/v1/research-program-portfolio-orchestration/v01610/programs'.$q);}
 public static function program_create(WP_REST_Request $r){return self::proxy('/v1/research-program-portfolio-orchestration/v01610/programs','POST',self::body($r));}
 public static function program_get(WP_REST_Request $r){return self::proxy(self::ppath($r));}
 public static function program_projects(WP_REST_Request $r){return self::proxy(self::ppath($r,'/projects'),'POST',self::body($r));}
 public static function program_membership_status(WP_REST_Request $r){return self::proxy(self::ppath($r,'/memberships/'.rawurlencode(self::clean_id($r['membership'])).'/status'),'POST',self::body($r));}
 public static function program_objectives(WP_REST_Request $r){return self::proxy(self::ppath($r,'/objectives'),'POST',self::body($r));}
 public static function objective_project(WP_REST_Request $r){return self::proxy(self::ppath($r,'/objectives/'.rawurlencode(self::clean_id($r['objective'])).'/projects'),'POST',self::body($r));}
 public static function objective_status(WP_REST_Request $r){return self::proxy(self::ppath($r,'/objectives/'.rawurlencode(self::clean_id($r['objective'])).'/status'),'POST',self::body($r));}
 public static function program_milestones(WP_REST_Request $r){return self::proxy(self::ppath($r,'/milestones'),'POST',self::body($r));}
 public static function milestone_status(WP_REST_Request $r){return self::proxy(self::ppath($r,'/milestones/'.rawurlencode(self::clean_id($r['milestone'])).'/status'),'POST',self::body($r));}
 public static function program_transition(WP_REST_Request $r){return self::proxy(self::ppath($r,'/transition'),'POST',self::body($r));}
 public static function program_command_center(WP_REST_Request $r){return self::proxy(self::ppath($r,'/command-center'));}
 public static function program_evaluate(WP_REST_Request $r){$target=self::clean_id($r->get_param('target_state'));return self::proxy(self::ppath($r,'/evaluate').($target?'?target_state='.rawurlencode($target):''));}
 public static function program_manifest(WP_REST_Request $r){return self::proxy(self::ppath($r,'/manifest'));}
 public static function program_snapshot(WP_REST_Request $r){return self::proxy(self::ppath($r,'/snapshot'),'POST',self::body($r));}
 public static function program_timeline(WP_REST_Request $r){return self::proxy(self::ppath($r,'/timeline').'?limit='.max(1,min(5000,absint($r->get_param('limit')?:500))));}
 public static function portfolios(WP_REST_Request $r){$q='?include_archived='.($r->get_param('include_archived')?'true':'false').'&limit='.max(1,min(1000,absint($r->get_param('limit')?:100)));return self::proxy('/v1/research-program-portfolio-orchestration/v01610/portfolios'.$q);}
 public static function portfolio_create(WP_REST_Request $r){return self::proxy('/v1/research-program-portfolio-orchestration/v01610/portfolios','POST',self::body($r));}
 public static function portfolio_get(WP_REST_Request $r){return self::proxy(self::fpath($r));}
 public static function portfolio_programs(WP_REST_Request $r){return self::proxy(self::fpath($r,'/programs'),'POST',self::body($r));}
 public static function portfolio_transition(WP_REST_Request $r){return self::proxy(self::fpath($r,'/transition'),'POST',self::body($r));}
 public static function portfolio_command_center(WP_REST_Request $r){return self::proxy(self::fpath($r,'/command-center'));}
 public static function portfolio_evaluate(WP_REST_Request $r){$target=self::clean_id($r->get_param('target_state'));return self::proxy(self::fpath($r,'/evaluate').($target?'?target_state='.rawurlencode($target):''));}
 public static function portfolio_manifest(WP_REST_Request $r){return self::proxy(self::fpath($r,'/manifest'));}
 public static function portfolio_snapshot(WP_REST_Request $r){return self::proxy(self::fpath($r,'/snapshot'),'POST',self::body($r));}
 public static function portfolio_timeline(WP_REST_Request $r){return self::proxy(self::fpath($r,'/timeline').'?limit='.max(1,min(5000,absint($r->get_param('limit')?:500))));}
 public static function snapshot_get(WP_REST_Request $r){return self::proxy('/v1/research-program-portfolio-orchestration/v01610/snapshots/'.rawurlencode(self::clean_id($r['snapshot'])));}
 public static function verify_manifest(WP_REST_Request $r){return self::proxy('/v1/research-program-portfolio-orchestration/v01610/manifests/verify','POST',self::body($r));}
}
