<?php
/** Sustainable Catalyst Lab v0.159.0 — Integrated Scientific Review, Validation & Publication Gate. */
if (!defined('ABSPATH')) { exit; }
final class SC_Lab_Integrated_Scientific_Review_Validation_Publication_Gate_V01590 {
 const VERSION='0.159.0'; private static $initialized=false;
 public static function init(){if(self::$initialized)return;self::$initialized=true;add_action('wp_enqueue_scripts',array(__CLASS__,'enqueue'),PHP_INT_MAX);add_action('wp_print_footer_scripts',array(__CLASS__,'enqueue'),PHP_INT_MAX);add_action('rest_api_init',array(__CLASS__,'routes'));}
 private static function is_lab_request(){if(is_admin())return false;global $post;if($post instanceof WP_Post&&has_shortcode((string)$post->post_content,'sc_lab_app'))return true;if(function_exists('is_page')&&is_page('lab'))return true;$path=isset($_SERVER['REQUEST_URI'])?(string)parse_url((string)$_SERVER['REQUEST_URI'],PHP_URL_PATH):'';return(bool)preg_match('~/(?:lab)/?$~',$path);}
 private static function asset_token($relative){$path=SC_LAB_DIR.ltrim((string)$relative,'/');return self::VERSION.'.'.(is_file($path)?substr(hash_file('sha256',$path),0,16):'missing');}
 public static function enqueue(){if(!self::is_lab_request())return;$css='assets/css/sc-lab-integrated-scientific-review-publication-gate-v01590.css';$js='assets/js/sc-lab-integrated-scientific-review-publication-gate-v01590.js';wp_enqueue_style('sc-lab-review-gate-v01590',SC_LAB_URL.$css,array('sc-lab-replication-network-v01580'),self::asset_token($css));wp_enqueue_script('sc-lab-review-gate-v01590',SC_LAB_URL.$js,array('sc-lab-replication-network-v01580','sc-lab-canonical-repair-v015701'),self::asset_token($js),true);wp_localize_script('sc-lab-review-gate-v01590','SCLabReviewGateV01590',array('version'=>self::VERSION,'healthUrl'=>esc_url_raw(rest_url('sc-lab/v1/workspace/review-gate/v01590/health')),'dossiersUrl'=>esc_url_raw(rest_url('sc-lab/v1/workspace/review-gate/v01590/dossiers')),'verifyUrl'=>esc_url_raw(rest_url('sc-lab/v1/workspace/review-gate/v01590/manifests/verify')),'defaultProjectId'=>is_user_logged_in()?'project:wp-user-'.get_current_user_id():'','nonce'=>wp_create_nonce('wp_rest')));}
 public static function operations_permission(){return is_user_logged_in();}
 private static function settings(){return wp_parse_args((array)get_option('sc_lab_settings',array()),SC_Lab_Admin::defaults());}
 private static function clean_id($v){return substr(preg_replace('/[^A-Za-z0-9._:-]/','',(string)$v),0,180);}
 private static function clean_tree($v,$depth=0,&$nodes=0){$nodes++;if($nodes>30000||$depth>24)return null;if(is_null($v)||is_bool($v)||is_int($v)||is_float($v))return $v;if(is_string($v))return substr(wp_check_invalid_utf8($v,true),0,150000);if(!is_array($v))return null;$out=array();$count=0;foreach($v as $k=>$x){if(++$count>10000)break;$key=is_int($k)?$k:substr(preg_replace('/[^A-Za-z0-9._:-]/','',(string)$k),0,128);if($key===''&&!is_int($k))continue;$out[$key]=self::clean_tree($x,$depth+1,$nodes);}return $out;}
 private static function body(WP_REST_Request $r){$b=$r->get_json_params();$n=0;return self::clean_tree(is_array($b)?$b:array(),0,$n);}
 private static function proxy($path,$method='GET',$payload=null,$limit=8388608){$s=self::settings();if(empty($s['enable_remote_compute'])||empty($s['compute_backend_url']))return new WP_Error('compute_disabled','The Python Compute Core is not enabled or configured.',array('status'=>503));if(!class_exists('SC_Lab_Python_Compute_Core_V0261'))return new WP_Error('compute_proxy_unavailable','The Python Compute Core signing bridge is unavailable.',array('status'=>503));$body=null===$payload?'':wp_json_encode($payload);$url=untrailingslashit($s['compute_backend_url']).$path;$args=array('method'=>$method,'timeout'=>max(5,min(120,absint($s['compute_timeout_seconds']))),'redirection'=>2,'sslverify'=>!empty($s['compute_verify_ssl']),'headers'=>SC_Lab_Python_Compute_Core_V0261::signed_headers($path,$method,$body,$s),'limit_response_size'=>max(262144,min(16777216,absint($limit))));if(null!==$payload)$args['body']=$body;$response=wp_safe_remote_request($url,$args);if(is_wp_error($response))return new WP_Error('review_gate_backend_unavailable',$response->get_error_message(),array('status'=>502));$status=wp_remote_retrieve_response_code($response);$decoded=json_decode(wp_remote_retrieve_body($response),true);if(!is_array($decoded)){$decoded=array('detail'=>'The review-gate backend returned invalid JSON.');$status=502;}return new WP_REST_Response($decoded,$status);}
 private static function pq(WP_REST_Request $r){return '?project_id='.rawurlencode(self::clean_id($r->get_param('project_id'))).'&include_archived='.($r->get_param('include_archived')?'true':'false').'&limit='.max(1,min(1000,absint($r->get_param('limit')?:100)));}
 public static function routes(){
  register_rest_route('sc-lab/v1','/workspace/review-gate/v01590/health',array('methods'=>'GET','callback'=>array(__CLASS__,'health'),'permission_callback'=>'__return_true'));
  register_rest_route('sc-lab/v1','/workspace/review-gate/v01590/dossiers',array(array('methods'=>'GET','callback'=>array(__CLASS__,'dossiers'),'permission_callback'=>array(__CLASS__,'operations_permission')),array('methods'=>'POST','callback'=>array(__CLASS__,'dossier_create'),'permission_callback'=>array(__CLASS__,'operations_permission'))));
  register_rest_route('sc-lab/v1','/workspace/review-gate/v01590/dossiers/(?P<id>[A-Za-z0-9._:-]{1,180})',array('methods'=>'GET','callback'=>array(__CLASS__,'dossier_get'),'permission_callback'=>array(__CLASS__,'operations_permission')));
  foreach(array('evidence-snapshot'=>'POST','checks'=>'POST','findings'=>'POST','reviews'=>'POST','gate'=>'GET','transition'=>'POST','publication-packet'=>'GET','manifest'=>'GET','timeline'=>'GET','archive'=>'POST') as $suffix=>$method)register_rest_route('sc-lab/v1','/workspace/review-gate/v01590/dossiers/(?P<id>[A-Za-z0-9._:-]{1,180})/'.$suffix,array('methods'=>$method,'callback'=>array(__CLASS__,str_replace('-','_',$suffix)),'permission_callback'=>array(__CLASS__,'operations_permission')));
  register_rest_route('sc-lab/v1','/workspace/review-gate/v01590/dossiers/(?P<id>[A-Za-z0-9._:-]{1,180})/findings/(?P<finding>[A-Za-z0-9._:-]{1,180})/resolve',array('methods'=>'POST','callback'=>array(__CLASS__,'finding_resolve'),'permission_callback'=>array(__CLASS__,'operations_permission')));
  register_rest_route('sc-lab/v1','/workspace/review-gate/v01590/manifests/verify',array('methods'=>'POST','callback'=>array(__CLASS__,'verify_manifest'),'permission_callback'=>array(__CLASS__,'operations_permission')));
 }
 public static function health(){return self::proxy('/v1/integrated-scientific-review-validation-publication-gate/v01590/health');}
 public static function dossiers(WP_REST_Request $r){return self::proxy('/v1/integrated-scientific-review-validation-publication-gate/v01590/dossiers'.self::pq($r));}
 public static function dossier_create(WP_REST_Request $r){$b=self::body($r);$pid=self::clean_id($b['project_id']??'');unset($b['project_id']);return self::proxy('/v1/integrated-scientific-review-validation-publication-gate/v01590/projects/'.rawurlencode($pid).'/dossiers','POST',$b);}
 public static function dossier_get(WP_REST_Request $r){return self::proxy('/v1/integrated-scientific-review-validation-publication-gate/v01590/dossiers/'.rawurlencode($r['id']));}
 private static function dpath(WP_REST_Request $r,$suffix){return '/v1/integrated-scientific-review-validation-publication-gate/v01590/dossiers/'.rawurlencode($r['id']).'/'.$suffix;}
 public static function evidence_snapshot(WP_REST_Request $r){return self::proxy(self::dpath($r,'evidence-snapshot'),'POST',self::body($r));}
 public static function checks(WP_REST_Request $r){return self::proxy(self::dpath($r,'checks'),'POST',self::body($r));}
 public static function findings(WP_REST_Request $r){return self::proxy(self::dpath($r,'findings'),'POST',self::body($r));}
 public static function reviews(WP_REST_Request $r){return self::proxy(self::dpath($r,'reviews'),'POST',self::body($r));}
 public static function gate(WP_REST_Request $r){return self::proxy(self::dpath($r,'gate'));}
 public static function transition(WP_REST_Request $r){return self::proxy(self::dpath($r,'transition'),'POST',self::body($r));}
 public static function publication_packet(WP_REST_Request $r){return self::proxy(self::dpath($r,'publication-packet'));}
 public static function manifest(WP_REST_Request $r){return self::proxy(self::dpath($r,'manifest'));}
 public static function timeline(WP_REST_Request $r){return self::proxy(self::dpath($r,'timeline'));}
 public static function archive(WP_REST_Request $r){return self::proxy(self::dpath($r,'archive'),'POST',self::body($r));}
 public static function finding_resolve(WP_REST_Request $r){return self::proxy(self::dpath($r,'findings').'/'.rawurlencode($r['finding']).'/resolve','POST',self::body($r));}
 public static function verify_manifest(WP_REST_Request $r){return self::proxy('/v1/integrated-scientific-review-validation-publication-gate/v01590/manifests/verify','POST',self::body($r));}
}
